# frozen_string_literal: true

source 'https://rubygems.org'

gem 'kreuzberg', '~> 4.7'
gem 'rspec', '~> 3.12'
gem 'rubocop', '~> 1.66'
gem 'rubocop-performance', '~> 1.21'
gem 'rubocop-rspec', '~> 3.0'
