// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d88e4421254b9fa1b82437ca829a5c9521e8c35f24513e85da61ae73e1ba1fbb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['tests/**/*.test.ts'],
  },
});
