# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require_relative 'kreuzberg/version'
require_relative 'kreuzberg/native'

module Kreuzberg
  # Re-export all types and functions from native extension
end
