# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d8d2a73265657eb1c04c8a7107831a2c3afcc3e5a5e4da8f4cce1dfe4a3a6a2f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: batch
defmodule E2e.BatchTest do
  use ExUnit.Case, async: true

  describe "batch_bytes_invalid_mime" do
    test "batch_extract_bytes_sync invalid MIME" do
      {:ok, result} = Kreuzberg.batch_extract_bytes_sync("")
    end
  end

  describe "batch_file_async_basic" do
    test "Extract text from multiple files asynchronously" do
      {:ok, result} = Kreuzberg.batch_extract_file_async("")
    end
  end

  describe "batch_file_async_not_found" do
    test "batch_extract_file async nonexistent" do
      {:ok, result} = Kreuzberg.batch_extract_file_async("")
    end
  end

  describe "batch_file_not_found" do
    test "batch_extract_file_sync nonexistent" do
      {:ok, result} = Kreuzberg.batch_extract_file_sync("")
    end
  end

  describe "batch_file_partial" do
    test "batch_extract_file_sync mixed" do
      {:ok, result} = Kreuzberg.batch_extract_file_sync("")
    end
  end

  describe "batch_file_sync_basic" do
    test "Extract text from multiple files synchronously" do
      {:ok, result} = Kreuzberg.batch_extract_file_sync("")
    end
  end
end
