# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a86573590aaf57844a3c390657b521d99bab6999f23724b4908cb83219dca6ef
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: document_extractor_management
defmodule E2e.DocumentExtractorManagementTest do
  use ExUnit.Case, async: true

  describe "extractors_clear" do
    test "Clear all document extractors and verify list is empty" do
      {:ok, result} = Kreuzberg.extract_file_async("")
      assert is_nil(result.result) or String.trim(result.result) == ""
    end
  end

  describe "extractors_list" do
    test "List all registered document extractors" do
      {:ok, result} = Kreuzberg.list_document_extractors("")
    end
  end

  describe "extractors_unregister" do
    test "Unregister nonexistent document extractor gracefully" do
      {:ok, result} = Kreuzberg.extract_file_async("")
    end
  end
end
