# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: document
defmodule E2e.DocumentTest do
  use ExUnit.Case, async: true

  describe "doc_metadata_docx" do
    test "Extract DOCX metadata" do
      {:ok, result} = Kreuzberg.extract_file_sync("vendored/markitdown/test.docx")
      assert result.metadata != ""
    end
  end

  describe "doc_metadata_pdf" do
    test "Extract PDF metadata" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf")
      assert result.metadata != ""
    end
  end

  describe "doc_structure_docx" do
    test "Extract DOCX document structure with include_document_structure config" do
      {:ok, result} = Kreuzberg.extract_file_sync("vendored/markitdown/test.docx", %{"include_document_structure" => true})
      assert result.document_structure != ""
    end
  end

  describe "doc_structure_html" do
    test "Extract HTML document structure with include_document_structure config" do
      {:ok, result} = Kreuzberg.extract_file_sync("html/html.html", %{"include_document_structure" => true})
      assert result.document_structure != ""
    end
  end

  describe "doc_structure_pdf" do
    test "Extract PDF document structure with include_document_structure config" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"include_document_structure" => true})
      assert result.document_structure != ""
    end
  end
end
