# This file is auto-generated by alef. DO NOT EDIT.
# E2e tests for category: embeddings
defmodule E2e.EmbeddingsTest do
  use ExUnit.Case, async: true

  describe "embedding_disabled" do
    test "Tests chunking without embeddings - chunks should not have embedding vectors" do
      {:ok, result} = Kreuzberg.extract_file_async("")
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert length(result.chunks) >= 1
      # TODO: unsupported assertion type: is_true
    end
  end
end
