# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:daa99e45dc4090fc908d8cec2006562a6e1fbe5dab7dc000a8e165416670cabd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: embed_extra
defmodule E2e.EmbedExtraTest do
  use ExUnit.Case, async: true

  describe "embed_normalize_unit" do
    test "Normalize unit vector" do
      {:ok, result} = Kreuzberg.normalize("")
    end
  end

  describe "embed_normalize_zero" do
    test "Normalize zero vector" do
      {:ok, result} = Kreuzberg.normalize("")
    end
  end
end
