# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f9ce07f77d6784e3ea8fd3931aa43d70cd56ccda3b7fede8958b5ae5217f084d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: language
defmodule E2e.LanguageTest do
  use ExUnit.Case, async: true

  describe "lang_detect_config" do
    test "Language detection with specific language config" do
      {:ok, result} = Kreuzberg.extract_file_sync("semantic/mixed_topics.txt", %{"language_detection" => %{"enabled" => true, "languages" => ["en", "de", "fr"]}})
    end
  end

  describe "lang_detect_english" do
    test "Language detection works on English text" do
      {:ok, result} = Kreuzberg.extract_file_sync("semantic/mixed_topics.txt", %{"language_detection" => %{"enabled" => true}})
    end
  end
end
