# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e442f00e784e4b5e168221a19c72f32779d6e36b1d3fa9e166ba990a11add8d2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: parsing
defmodule E2e.ParsingTest do
  use ExUnit.Case, async: true

  describe "parse_json" do
    test "Parse JSON document format" do
      {:ok, result} = Kreuzberg.extract_file_sync("json/simple.json")
      assert String.length(result.content) >= 5
    end
  end

  describe "parse_toml" do
    test "Parse TOML document format" do
      {:ok, result} = Kreuzberg.extract_file_sync("data_formats/cargo.toml")
      assert String.length(result.content) >= 5
    end
  end

  describe "parse_xml" do
    test "Parse XML document format" do
      {:ok, result} = Kreuzberg.extract_file_sync("xml/simple_note.xml")
      assert String.length(result.content) >= 5
    end
  end

  describe "parse_yaml" do
    test "Parse YAML document format" do
      {:ok, result} = Kreuzberg.extract_file_sync("test_fixtures/config.yaml")
      assert String.length(result.content) >= 5
    end
  end
end
