# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6d5e15ccf05c83ee23a128ae3dc5fdb16981a84505d2f8b7ad83a302e31979f7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: uri
defmodule E2e.UriTest do
  use ExUnit.Case, async: true

  describe "classify_uri_anchor" do
    test "Classify fragment URI" do
      {:ok, result} = Kreuzberg.classify_uri("")
    end
  end

  describe "classify_uri_email" do
    test "Classify mailto URI" do
      {:ok, result} = Kreuzberg.classify_uri("")
    end
  end

  describe "classify_uri_https" do
    test "Classify HTTPS URL" do
      {:ok, result} = Kreuzberg.classify_uri("")
    end
  end
end
