// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:da416776d7481d1f4a1570c454ed14033bfbf3111a13156e900c066c56bece99
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: cache_ops.</summary>
public class CacheOpsTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public void Test_GenerateCacheKeyComplex()
    {
        // Complex cache key
        var result = Kreuzberg.GenerateCacheKey(new[] { "hash_abc", "config_v2", "markdown" });
        Assert.True(result.Result.Length >= 5, "expected length >= 5");
    }

    [Fact]
    public void Test_ValidateCacheKeyInvalid()
    {
        // Invalid cache key
        Assert.Throws<KreuzbergException>(() => Kreuzberg.ValidateCacheKey(""));
    }
}
