// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: document_extractor_management.</summary>
public class DocumentExtractorManagementTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public async Task Test_ExtractorsClear()
    {
        // Clear all document extractors and verify list is empty
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.True(string.IsNullOrEmpty(result.Result?.ToString()));
    }

    [Fact]
    public void Test_ExtractorsList()
    {
        // List all registered document extractors
        var result = Kreuzberg.ListDocumentExtractors("{\"setup\":{\"lazy_init_required\":{\"init_action\":\"extract_file_sync\",\"init_data\":{\"create_temp_file\":true,\"temp_file_content\":\"%PDF-1.4\\n%EOF\\n\",\"temp_file_name\":\"test.pdf\"},\"languages\":[\"go\"]}}}");
    }

    [Fact]
    public async Task Test_ExtractorsUnregister()
    {
        // Unregister nonexistent document extractor gracefully
        var result = await Kreuzberg.ExtractFile("", null, null);
    }
}
