// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9536ec9536176a1600efd1d0c3634972e709cc87d61a8b92d19c478820a442c2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: embed_extra.</summary>
public class EmbedExtraTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public void Test_EmbedNormalizeUnit()
    {
        // Normalize unit vector
        var result = KreuzbergLib.Normalize(new[] { 1.0d, 0.0d, 0.0d });
    }

    [Fact]
    public void Test_EmbedNormalizeZero()
    {
        // Normalize zero vector
        var result = KreuzbergLib.Normalize(new[] { 0.0d, 0.0d, 0.0d });
    }
}
