// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:01d8dd8ef45182e3101206dade6dd54962772ceaf5ffe3140fa67ac3b84e4e0d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: embed_extra.</summary>
public class EmbedExtraTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public void Test_EmbedNormalizeUnit()
    {
        // Normalize unit vector
        var result = Kreuzberg.Normalize(new[] { 1.0d, 0.0d, 0.0d });
    }

    [Fact]
    public void Test_EmbedNormalizeZero()
    {
        // Normalize zero vector
        var result = Kreuzberg.Normalize(new[] { 0.0d, 0.0d, 0.0d });
    }
}
