// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2628638a70bf477a5c25848feecdd53f71fbdbfc92f65560d53d8a75ec942e7e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: html.</summary>
public class HtmlTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public async Task Test_HtmlComplexLayout()
    {
        // Large Wikipedia HTML page to validate complex conversion.
        var result = await Kreuzberg.ExtractFile("html/taylor_swift.html", null, null);
        Assert.Equal("text/html", result.MimeType.Trim());
        Assert.True(result.Content.Length >= 1000, "expected length >= 1000");
    }

    [Fact]
    public async Task Test_HtmlSimpleTable()
    {
        // HTML table converted to markdown should retain structure.
        var result = await Kreuzberg.ExtractFile("html/simple_table.html", null, null);
        Assert.Equal("text/html", result.MimeType.Trim());
        Assert.True(result.Content.Length >= 100, "expected length >= 100");
        Assert.Contains("product", result.Content.ToString().ToLower());
        Assert.Contains("category", result.Content.ToString().ToLower());
        Assert.Contains("price", result.Content.ToString().ToLower());
        Assert.Contains("stock", result.Content.ToString().ToLower());
        Assert.Contains("laptop", result.Content.ToString().ToLower());
        Assert.Contains("electronics", result.Content.ToString().ToLower());
        Assert.Contains("sample data table", result.Content.ToString().ToLower());
    }
}
