// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1114284771dbeea97143ff6f5431fddee55f75b015744decb7947a921aa3cab1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: language.</summary>
public class LanguageTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public void Test_LangDetectConfig()
    {
        // Language detection with specific language config
        var result = Kreuzberg.ExtractFileSync("semantic/mixed_topics.txt", null, new ExtractionConfig { LanguageDetection = "{\"enabled\":true,\"languages\":[\"en\",\"de\",\"fr\"]}" });
    }

    [Fact]
    public void Test_LangDetectEnglish()
    {
        // Language detection works on English text
        var result = Kreuzberg.ExtractFileSync("semantic/mixed_topics.txt", null, new ExtractionConfig { LanguageDetection = "{\"enabled\":true}" });
    }
}
