// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f38b5029479445cf678bd1221b92280506643073456067a55ca1ca3c2cb84a8c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: registry.</summary>
public class RegistryTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public void Test_ListDocumentExtractors()
    {
        // List document extractors
        var result = Kreuzberg.ListDocumentExtractors("{}");
    }

    [Fact]
    public void Test_ListOcrBackends()
    {
        // List OCR backends
        var result = Kreuzberg.ListOcrBackends("{}");
    }

    [Fact]
    public void Test_ListPostProcessors()
    {
        // List post-processors
        var result = Kreuzberg.ListPostProcessors("{}");
    }

    [Fact]
    public void Test_ListValidators()
    {
        // List validators
        var result = Kreuzberg.ListValidators("{}");
    }
}
