// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4da324d44e130381831996f9b4f5096a126dee681918cdd3a13dd62f0008b9b9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: table_operations.</summary>
public class TableOperationsTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public void Test_CellsMarkdownBasic()
    {
        // Convert basic 2D cell array to markdown table format
        var result = Kreuzberg.CellsToMarkdown("[[\"Name\",\"Age\"],[\"Alice\",\"30\"],[\"Bob\",\"25\"]]");
        Assert.Contains("|", result.Result.ToString().ToLower());
    }

    [Fact]
    public void Test_CellsMarkdownSingle()
    {
        // Convert single-column cell array to markdown table
        var result = Kreuzberg.CellsToMarkdown("[[\"Header\"],[\"Value\"]]");
    }

    [Fact]
    public void Test_CellsTextBasic()
    {
        // Convert basic 2D cell array to space-separated text
        var result = Kreuzberg.CellsToText("[[\"Name\",\"Age\"],[\"Alice\",\"30\"],[\"Bob\",\"25\"]]");
        Assert.Contains("alice", result.Result.ToString().ToLower());
    }

    [Fact]
    public void Test_CellsTextSingle()
    {
        // Convert simple 2x2 cell array to text
        var result = Kreuzberg.CellsToText("[[\"A\",\"B\"],[\"1\",\"2\"]]");
    }
}
