// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e41c913d31a1918a165322146e4432d43fc5ed0b245ac250641ad3d725b85262
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: validator_management.</summary>
public class ValidatorManagementTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public async Task Test_ValidatorsClear()
    {
        // Clear all validators and verify list is empty
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.True(string.IsNullOrEmpty(result.Result?.ToString()));
    }

    [Fact]
    public void Test_ValidatorsList()
    {
        // List all registered validators
        var result = Kreuzberg.ListValidators(null);
    }
}
