// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:076ee04a456a7dd9d6794aa56a20ee9339a6bed1ea444f81a5a135c4eda8eb44
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: cache_ops

use kreuzberg::{generate_cache_key, validate_cache_key};

#[test]
fn test_generate_cache_key_complex() {
    // Complex cache key
    let parts_json = serde_json::json!(["hash_abc", "config_v2", "markdown"]);
    let parts = serde_json::from_value(parts_json).unwrap();
    let result = generate_cache_key(&parts).expect("should succeed");
    assert!(
        result.result.len() >= 5,
        "expected length >= 5, got {}",
        result.result.len()
    );
}

#[test]
fn test_validate_cache_key_invalid() {
    // Invalid cache key
    let key = r#""#;
    let result = validate_cache_key(&key);
    assert!(result.is_err(), "expected call to fail");
}
