// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:20d466236253b6012f3995bcee42201f5ba2c9cea0cc53fda40a38b8b288d154
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: embeddings

use kreuzberg::extract_file_sync;

#[test]
fn test_embedding_disabled() {
    // Tests chunking without embeddings - chunks should not have embedding vectors
    let path = r#"pdf/fake_memo.pdf"#;
    let mime_type = None;
    let config_json = serde_json::json!({"chunking": {"max_chars": 500, "max_overlap": 50}});
    let config = Some(serde_json::from_value(config_json).unwrap());
    let result = extract_file_sync(&path, &mime_type, &config).expect("should succeed");
    assert_eq!(result.mime_type.trim(), r#"application/pdf"#, "equals assertion failed");
    assert!(
        result.content.len() >= 10,
        "expected length >= 10, got {}",
        result.content.len()
    );
    assert!(!result.chunks.is_empty(), "expected >= 1");
    assert!(result.chunks_have_content, "expected true");
}
