// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2b22080e17569b5f4370b4ad4a2040466109ae6f12de87e0ac9775eeb609a902
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: image_operations

use kreuzberg::calculate_optimal_dpi;

#[test]
fn test_optimal_dpi_large() {
    // Calculate optimal DPI for large image (3000x4000 pixels, 5MB target)
    let width = 0;
    let height = 0;
    let target_size_mb = 0.0_f64;
    let _ = calculate_optimal_dpi(width, height, target_size_mb);
}

#[test]
fn test_optimal_dpi_small() {
    // Calculate optimal DPI for small image (800x600 pixels, 1MB target)
    let width = 0;
    let height = 0;
    let target_size_mb = 0.0_f64;
    let _ = calculate_optimal_dpi(width, height, target_size_mb);
}

#[test]
fn test_optimal_dpi_tiny() {
    // Calculate optimal DPI for tiny image (100x100 pixels, 0.1MB target)
    let width = 0;
    let height = 0;
    let target_size_mb = 0.0_f64;
    let _ = calculate_optimal_dpi(width, height, target_size_mb);
}
