// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a3637e6b7da4249027463e045d80de5bf112f7ddc6117a9d748103751a1d944f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: language

use kreuzberg::extract_file_sync;

#[test]
fn test_lang_detect_config() {
    // Language detection with specific language config
    let path = r#"semantic/mixed_topics.txt"#;
    let mime_type = None;
    let config_json = serde_json::json!({"language_detection": {"enabled": true, "languages": ["en", "de", "fr"]}});
    let config = Some(serde_json::from_value(config_json).unwrap());
    let _ = extract_file_sync(&path, &mime_type, &config);
}

#[test]
fn test_lang_detect_english() {
    // Language detection works on English text
    let path = r#"semantic/mixed_topics.txt"#;
    let mime_type = None;
    let config_json = serde_json::json!({"language_detection": {"enabled": true}});
    let config = Some(serde_json::from_value(config_json).unwrap());
    let _ = extract_file_sync(&path, &mime_type, &config);
}
