// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fc850e9f6549fb5c407f98fdf2c4f606f3c1480725ddb04c77d2525a383b3bef
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: post_processor_management

use kreuzberg::{extract_file, list_post_processors};

#[tokio::test]
async fn test_post_processors_clear() {
    // Clear all post-processors and verify list is empty
    let path = String::new();
    let mime_type = None;
    let config = Default::default();
    let _ = extract_file(&path, &mime_type, &config).await;
}

#[test]
fn test_post_processors_list() {
    // List all registered post-processors
    let _ = list_post_processors();
}
