// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0fc4a1adecaa77241ad2bee9d93fd1da76b8a8e83bd15672ed9a939d3c005fc3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: registry_operations

use kreuzberg::{get_extensions_for_mime, list_supported_formats};

#[test]
fn test_extensions_docx() {
    // Get file extensions for DOCX MIME type
    let mime_type = String::new();
    let _ = get_extensions_for_mime(&mime_type);
}

#[test]
fn test_extensions_html() {
    // Get file extensions for HTML MIME type
    let mime_type = String::new();
    let _ = get_extensions_for_mime(&mime_type);
}

#[test]
fn test_extensions_pdf() {
    // Get file extensions for PDF MIME type
    let mime_type = String::new();
    let result = get_extensions_for_mime(&mime_type).expect("should succeed");
    assert!(
        format!("{:?}", result.result).contains(r#"pdf"#),
        "expected to contain: {}",
        r#"pdf"#
    );
}

#[test]
fn test_list_formats_all() {
    // List all supported formats and their extensions
    let _ = list_supported_formats();
}
