// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:de4e194bf16fbb2656bb15bd4d7dc750a1662e7a141b614704d9ad9ed8a10d62
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: table

use kreuzberg::extract_file_sync;

#[test]
fn test_table_csv_extraction() {
    // CSV file extraction produces content
    let path = r#"csv/stanley_cups.csv"#;
    let mime_type: Option<String> = None;
    let config = Default::default();
    let result = extract_file_sync(&path, mime_type.as_deref(), &config).expect("should succeed");
    assert!(
        result.content.len() >= 10,
        "expected length >= 10, got {}",
        result.content.len()
    );
}

#[test]
fn test_table_html_extraction() {
    // HTML table extraction produces markdown format
    let path = r#"html/simple_table.html"#;
    let mime_type: Option<String> = None;
    let config_json = serde_json::json!({"output_format": "markdown"});
    let config = Some(serde_json::from_value(config_json).unwrap());
    let result = extract_file_sync(&path, mime_type.as_deref(), &config).expect("should succeed");
    assert!(
        result.content.contains(r#"|"#),
        "expected to contain at least one of the specified values"
    );
}

#[test]
fn test_table_xlsx_markdown() {
    // XLSX extraction produces markdown table format
    let path = r#"xlsx/stanley_cups.xlsx"#;
    let mime_type: Option<String> = None;
    let config_json = serde_json::json!({"output_format": "markdown"});
    let config = Some(serde_json::from_value(config_json).unwrap());
    let result = extract_file_sync(&path, mime_type.as_deref(), &config).expect("should succeed");
    assert!(
        result.content.contains(r#"|"#) || result.content.contains(r#"---"#),
        "expected to contain at least one of the specified values"
    );
}
