// This file is auto-generated by alef. DO NOT EDIT.
//! E2e tests for category: token_reduction

use kreuzberg::extract_file;

#[tokio::test]
async fn test_token_reduction_aggressive() {
    // Tests aggressive token reduction mode significantly reduces content
    let path = String::new();
    let mime_type = None;
    let config = None;
    let result = extract_file(&path, &mime_type, config).await.expect("should succeed");
    assert_eq!(result.mime_type.trim(), r#"application/pdf"#, "equals assertion failed");
    assert!(
        result.content.len() >= 5,
        "expected length >= 5, got {}",
        result.content.len()
    );
    assert!(
        result.content.len() <= 150,
        "expected length <= 150, got {}",
        result.content.len()
    );
    assert!(result.content.is_some(), "expected content to be present");
}

#[tokio::test]
async fn test_token_reduction_basic() {
    // Tests basic token reduction on PDF document
    let path = String::new();
    let mime_type = None;
    let config = None;
    let result = extract_file(&path, &mime_type, config).await.expect("should succeed");
    assert_eq!(result.mime_type.trim(), r#"application/pdf"#, "equals assertion failed");
    assert!(
        result.content.len() >= 5,
        "expected length >= 5, got {}",
        result.content.len()
    );
    assert!(
        result.content.len() <= 200,
        "expected length <= 200, got {}",
        result.content.len()
    );
    assert!(result.content.is_some(), "expected content to be present");
}

#[tokio::test]
async fn test_token_reduction_light() {
    // Tests light token reduction mode preserves most content
    let path = String::new();
    let mime_type = None;
    let config = None;
    let result = extract_file(&path, &mime_type, config).await.expect("should succeed");
    assert_eq!(result.mime_type.trim(), r#"application/pdf"#, "equals assertion failed");
    assert!(
        result.content.len() >= 10,
        "expected length >= 10, got {}",
        result.content.len()
    );
    assert!(result.content.is_some(), "expected content to be present");
}

#[tokio::test]
async fn test_token_reduction_with_chunking() {
    // Tests token reduction combined with chunking
    let path = String::new();
    let mime_type = None;
    let config = None;
    let result = extract_file(&path, &mime_type, config).await.expect("should succeed");
    assert_eq!(result.mime_type.trim(), r#"application/pdf"#, "equals assertion failed");
    assert!(
        result.content.len() >= 5,
        "expected length >= 5, got {}",
        result.content.len()
    );
    assert!(
        result.content.len() <= 200,
        "expected length <= 200, got {}",
        result.content.len()
    );
    assert!(result.content.is_some(), "expected content to be present");
    assert!(
        result.chunks.len() >= 1,
        "expected at least 1 elements, got {}",
        result.chunks.len()
    );
    // TODO: unsupported assertion type: is_true
}
