// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: validator_management

use kreuzberg::{extract_file, list_validators};

#[tokio::test]
async fn test_validators_clear() {
    // Clear all validators and verify list is empty
    let path = String::new();
    let mime_type = None;
    let config = Default::default();
    let result = extract_file(&path, &mime_type, &config).await.expect("should succeed");
    assert!(result.result.is_empty(), "expected empty value");
}

#[test]
fn test_validators_list() {
    // List all registered validators
    let _ = list_validators();
}
