// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8ea774897a9a8d91f1a518579fb19c992509f2d22c4cf2d1087bef905798c082
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: xml

use kreuzberg::extract_file;

#[tokio::test]
async fn test_xml_plant_catalog() {
    // XML plant catalog to validate streaming XML extraction.
    let path = r#"xml/plant_catalog.xml"#;
    let mime_type = None;
    let config = Default::default();
    let result = extract_file(&path, &mime_type, &config).await.expect("should succeed");
    assert_eq!(result.mime_type.trim(), r#"application/xml"#, "equals assertion failed");
    assert!(
        result.content.len() >= 100,
        "expected length >= 100, got {}",
        result.content.len()
    );
}
