<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0b28b8bd5e153f2259e3c9c40551fcc323b7b53e85c3e7a5da970b873f548dc3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: html. */
final class HtmlTest extends TestCase
{
    /** Large Wikipedia HTML page to validate complex conversion. */
    public function test_html_complex_layout(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile_async("html/taylor_swift.html");
        $this->assertEquals("text/html", $result->mime_type);
        $this->assertGreaterThanOrEqual(1000, strlen($result->content));
    }

    /** HTML table converted to markdown should retain structure. */
    public function test_html_simple_table(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile_async("html/simple_table.html");
        $this->assertEquals("text/html", $result->mime_type);
        $this->assertGreaterThanOrEqual(100, strlen($result->content));
        $this->assertStringContainsString("Product", $result->content);
        $this->assertStringContainsString("Category", $result->content);
        $this->assertStringContainsString("Price", $result->content);
        $this->assertStringContainsString("Stock", $result->content);
        $this->assertStringContainsString("Laptop", $result->content);
        $this->assertStringContainsString("Electronics", $result->content);
        $this->assertStringContainsString("Sample Data Table", $result->content);
    }
}
