<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a3dfb3f156051507eb4353e870cbf5b51a367794db37833c970bfa13d23e80d7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: image_ops. */
final class ImageOpsTest extends TestCase
{
    /** DPI for large image */
    public function test_calculate_dpi_large(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::calculate_optimal_dpi(10000, 10000, 0.5);
    }

    /** DPI for small image */
    public function test_calculate_dpi_small(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::calculate_optimal_dpi(100, 100, 1.0);
    }
}
