<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6834b62f7e79c509831a9cbce622a56aa93592e09d44c818034c26363bd73f58
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: uri. */
final class UriTest extends TestCase
{
    /** Classify fragment URI */
    public function test_classify_uri_anchor(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::classify_uri("#section-header");
    }

    /** Classify mailto URI */
    public function test_classify_uri_email(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::classify_uri("mailto:user@example.com");
    }

    /** Classify HTTPS URL */
    public function test_classify_uri_https(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::classify_uri("https://example.com/page");
    }
}
