// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9fb7b1ef7f3fbc1deac56ba1bbaef34a04c295615e88568a6a75951c8c1c2239
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// OpenAPI documentation structure.
///
/// Defines all endpoints, request/response schemas, and examples
/// for the Kreuzberg document extraction API.
/// </summary>
public sealed class ApiDoc : IDisposable
{
    internal IntPtr Handle { get; }

    internal ApiDoc(IntPtr handle)
    {
        Handle = handle;
    }

    public void Dispose()
    {
        // Native free will be called by the runtime
    }
}
