// This file is auto-generated by alef. DO NOT EDIT.
using System;

namespace Kreuzberg;

/// <summary>
/// OpenAPI documentation structure.
///
/// Defines all endpoints, request/response schemas, and examples
/// for the Kreuzberg document extraction API.
/// </summary>
public sealed class ApiDoc : IDisposable
{
    internal IntPtr Handle { get; }

    internal ApiDoc(IntPtr handle)
    {
        Handle = handle;
    }

    public void Dispose()
    {
        // Native free will be called by the runtime
    }
}
