// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A single file extracted from an archive.
///
/// When archives (ZIP, TAR, 7Z, GZIP) are extracted with recursive extraction
/// enabled, each processable file produces its own full `ExtractionResult`.
/// </summary>
public sealed class ArchiveEntry
{
    /// <summary>
    /// Archive-relative file path (e.g. "folder/document.pdf").
    /// </summary>
    [JsonPropertyName("path")]
    public string Path { get; set; } = "";

    /// <summary>
    /// Detected MIME type of the file.
    /// </summary>
    [JsonPropertyName("mime_type")]
    public string MimeType { get; set; } = "";

    /// <summary>
    /// Full extraction result for this file.
    /// </summary>
    [JsonPropertyName("result")]
    public ExtractionResult Result { get; set; } = default!;

}
