// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Bounding box coordinates for element positioning.
/// </summary>
public sealed class BoundingBox
{
    /// <summary>
    /// Left x-coordinate
    /// </summary>
    [JsonPropertyName("x0")]
    public double X0 { get; set; } = 0.0;

    /// <summary>
    /// Bottom y-coordinate
    /// </summary>
    [JsonPropertyName("y0")]
    public double Y0 { get; set; } = 0.0;

    /// <summary>
    /// Right x-coordinate
    /// </summary>
    [JsonPropertyName("x1")]
    public double X1 { get; set; } = 0.0;

    /// <summary>
    /// Top y-coordinate
    /// </summary>
    [JsonPropertyName("y1")]
    public double Y1 { get; set; } = 0.0;

}
