// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d5bf073671ca5df56ddbe6c0945670d9981da4728851df59b16c977d64912152
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// Convenience type alias for a pooled Vec<u8>.
/// </summary>
public sealed class ByteBufferPool : IDisposable
{
    internal IntPtr Handle { get; }

    internal ByteBufferPool(IntPtr handle)
    {
        Handle = handle;
    }

    public void Dispose()
    {
        // Native free will be called by the runtime
    }
}
