// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:54a16a2875e5e1e9cf3e130a0cb13ec0f9928b9530cd919767ef40cefa6a69e3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Cache clear response.
/// </summary>
public sealed class CacheClearResponse
{
    /// <summary>
    /// Cache directory path
    /// </summary>
    [JsonPropertyName("directory")]
    public string Directory { get; set; } = "";

    /// <summary>
    /// Number of files removed
    /// </summary>
    [JsonPropertyName("removed_files")]
    public ulong RemovedFiles { get; set; } = 0;

    /// <summary>
    /// Space freed in MB
    /// </summary>
    [JsonPropertyName("freed_mb")]
    public double FreedMb { get; set; } = 0.0;

}
