// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e8e1e95c005a46ae7adfeeef6ded34e7f7ea45cf36dac93a16fe7651538492ec
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Request parameters for cache warm (model download).
/// </summary>
public sealed class CacheWarmParams
{
    /// <summary>
    /// Download all embedding model presets
    /// </summary>
    [JsonPropertyName("all_embeddings")]
    public bool AllEmbeddings { get; set; } = false;

    /// <summary>
    /// Specific embedding preset name to download (e.g. "balanced", "speed", "quality")
    /// </summary>
    [JsonPropertyName("embedding_model")]
    public string? EmbeddingModel { get; set; } = null;

}
