// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Cache statistics.
///
/// Provides information about the extraction result cache,
/// including size, file count, and age distribution.
/// </summary>
public sealed class CacheStats
{
    /// <summary>
    /// Total number of cached files
    /// </summary>
    [JsonPropertyName("total_files")]
    public ulong TotalFiles { get; set; } = 0;

    /// <summary>
    /// Total cache size in megabytes
    /// </summary>
    [JsonPropertyName("total_size_mb")]
    public double TotalSizeMb { get; set; } = 0.0;

    /// <summary>
    /// Available disk space in megabytes
    /// </summary>
    [JsonPropertyName("available_space_mb")]
    public double AvailableSpaceMb { get; set; } = 0.0;

    /// <summary>
    /// Age of the oldest cached file in days
    /// </summary>
    [JsonPropertyName("oldest_file_age_days")]
    public double OldestFileAgeDays { get; set; } = 0.0;

    /// <summary>
    /// Age of the newest cached file in days
    /// </summary>
    [JsonPropertyName("newest_file_age_days")]
    public double NewestFileAgeDays { get; set; } = 0.0;

}
