// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:02fba52087ccec12170a2d25818c6645f05025acf79dc238589a6278d35d4abe
#nullable enable

using System;

namespace Kreuzberg;

public class CancelledException : KreuzbergErrorException
{
    public CancelledException(string message) : base(message) { }

    public CancelledException(string message, Exception innerException) : base(message, innerException) { }
}
