// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a8bda7a7f79b8b99ea87d4b0355a21111e513e7d8f1204e961c6cda9caec8bf7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Chunk response with chunks and metadata.
/// </summary>
public sealed class ChunkResponse
{
    /// <summary>
    /// List of chunks
    /// </summary>
    [JsonPropertyName("chunks")]
    public List<string> Chunks { get; set; } = [];

    /// <summary>
    /// Total number of chunks
    /// </summary>
    [JsonPropertyName("chunk_count")]
    public ulong ChunkCount { get; set; } = 0;

    /// <summary>
    /// Configuration used for chunking
    /// </summary>
    [JsonPropertyName("config")]
    public string Config { get; set; } = "";

    /// <summary>
    /// Input text size in bytes
    /// </summary>
    [JsonPropertyName("input_size_bytes")]
    public ulong InputSizeBytes { get; set; } = 0;

    /// <summary>
    /// Chunker type used for chunking
    /// </summary>
    [JsonPropertyName("chunker_type")]
    public string ChunkerType { get; set; } = "";

}
