// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Chunk request with text and configuration.
/// </summary>
public sealed class ChunkRequest
{
    /// <summary>
    /// Text to chunk (must not be empty)
    /// </summary>
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

    /// <summary>
    /// Optional chunking configuration
    /// </summary>
    [JsonPropertyName("config")]
    public string? Config { get; set; } = null;

    /// <summary>
    /// Chunker type (text or markdown)
    /// </summary>
    [JsonPropertyName("chunker_type")]
    public string ChunkerType { get; set; } = "";

}
