// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Color scheme containing all 12 standard Office theme colors.
/// </summary>
public sealed class ColorScheme
{
    /// <summary>
    /// Color scheme name.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    /// <summary>
    /// Dark 1 (dark background) color.
    /// </summary>
    [JsonPropertyName("dk1")]
    public JsonElement? Dk1 { get; set; } = null;

    /// <summary>
    /// Light 1 (light background) color.
    /// </summary>
    [JsonPropertyName("lt1")]
    public JsonElement? Lt1 { get; set; } = null;

    /// <summary>
    /// Dark 2 color.
    /// </summary>
    [JsonPropertyName("dk2")]
    public JsonElement? Dk2 { get; set; } = null;

    /// <summary>
    /// Light 2 color.
    /// </summary>
    [JsonPropertyName("lt2")]
    public JsonElement? Lt2 { get; set; } = null;

    /// <summary>
    /// Accent color 1.
    /// </summary>
    [JsonPropertyName("accent1")]
    public JsonElement? Accent1 { get; set; } = null;

    /// <summary>
    /// Accent color 2.
    /// </summary>
    [JsonPropertyName("accent2")]
    public JsonElement? Accent2 { get; set; } = null;

    /// <summary>
    /// Accent color 3.
    /// </summary>
    [JsonPropertyName("accent3")]
    public JsonElement? Accent3 { get; set; } = null;

    /// <summary>
    /// Accent color 4.
    /// </summary>
    [JsonPropertyName("accent4")]
    public JsonElement? Accent4 { get; set; } = null;

    /// <summary>
    /// Accent color 5.
    /// </summary>
    [JsonPropertyName("accent5")]
    public JsonElement? Accent5 { get; set; } = null;

    /// <summary>
    /// Accent color 6.
    /// </summary>
    [JsonPropertyName("accent6")]
    public JsonElement? Accent6 { get; set; } = null;

    /// <summary>
    /// Hyperlink color.
    /// </summary>
    [JsonPropertyName("hlink")]
    public JsonElement? Hlink { get; set; } = null;

    /// <summary>
    /// Followed hyperlink color.
    /// </summary>
    [JsonPropertyName("fol_hlink")]
    public JsonElement? FolHlink { get; set; } = null;

}
