// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:98b4c096e3d7df0ea1a9b871e330dcfefefa145f8303394b13c3ea664248eeda
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// Custom properties from docProps/custom.xml
///
/// Maps property names to their values. Values are converted to JSON types
/// based on the VT (Variant Type) specified in the XML.
/// </summary>
public sealed class CustomProperties : IDisposable
{
    internal IntPtr Handle { get; }

    internal CustomProperties(IntPtr handle)
    {
        Handle = handle;
    }

    public void Dispose()
    {
        // Native free will be called by the runtime
    }
}
