// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:57a670af48083426a263b15c48ce0e6768a632510787a5fb051a58e5ca814739
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// dBASE field information.
/// </summary>
public sealed class DbfFieldInfo
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonPropertyName("field_type")]
    public string FieldType { get; set; } = "";

}
