// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6d647ba95d8d663102ec290284d6565d77fd2eee6cc2089bedf8d2ee387fec4c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A detected structural boundary in the text.
/// </summary>
public sealed class DetectedBoundary
{
    /// <summary>
    /// Byte offset of the start of the line in the original text.
    /// </summary>
    [JsonPropertyName("byte_offset")]
    public ulong ByteOffset { get; set; } = 0;

    /// <summary>
    /// Whether this boundary looks like a header/section title.
    /// </summary>
    [JsonPropertyName("is_header")]
    public bool IsHeader { get; set; } = false;

}
