// This file is auto-generated by alef. DO NOT EDIT.
using System;

namespace Kreuzberg;

/// <summary>
/// Djot markup extractor with metadata and table support.
///
/// Parses Djot documents with YAML frontmatter, extracting:
/// - Metadata from YAML frontmatter
/// - Plain text content
/// - Tables as structured data
/// - Document structure (headings, links, code blocks)
/// </summary>
public sealed class DjotExtractor : IDisposable
{
    internal IntPtr Handle { get; }

    internal DjotExtractor(IntPtr handle)
    {
        Handle = handle;
    }

    public void Dispose()
    {
        // Native free will be called by the runtime
    }
}
