// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// OpenWebUI "Docling" engine response format.
///
/// Returned by `POST /v1/convert/file` for docling-serve compatibility.
/// </summary>
public sealed class DoclingCompatResponse
{
    /// <summary>
    /// Converted document content
    /// </summary>
    [JsonPropertyName("document")]
    public DoclingCompatDocument Document { get; set; } = default!;

    /// <summary>
    /// Processing status
    /// </summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = "";

}
