// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A drawing object extracted from `<w:drawing>`.
/// </summary>
public sealed class Drawing
{
    [JsonPropertyName("drawing_type")]
    public string DrawingType { get; set; } = "";

    [JsonPropertyName("extent")]
    public string? Extent { get; set; } = null;

    [JsonPropertyName("doc_properties")]
    public string? DocProperties { get; set; } = null;

    [JsonPropertyName("image_ref")]
    public string? ImageRef { get; set; } = null;

}
