// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:27d90a82107d62ff2de3abf7dd87b4347645d9edb2780d2eccf908527acd8166
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A drawing object extracted from `<w:drawing>`.
/// </summary>
public sealed class Drawing
{
    [JsonPropertyName("drawing_type")]
    public string DrawingType { get; set; } = "";

    [JsonPropertyName("extent")]
    public string? Extent { get; set; } = null;

    [JsonPropertyName("doc_properties")]
    public string? DocProperties { get; set; } = null;

    [JsonPropertyName("image_ref")]
    public string? ImageRef { get; set; } = null;

}
