// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A drawing object extracted from `<w:drawing>`.
/// </summary>
public sealed class Drawing
{
    [JsonPropertyName("drawing_type")]
    public JsonElement DrawingType { get; set; } = default!;

    [JsonPropertyName("extent")]
    public Extent? Extent { get; set; } = null;

    [JsonPropertyName("doc_properties")]
    public DocProperties? DocProperties { get; set; } = null;

    [JsonPropertyName("image_ref")]
    public string? ImageRef { get; set; } = null;

}
