// This file is auto-generated by alef. DO NOT EDIT.
using System;

namespace Kreuzberg;

/// <summary>
/// Helper struct for validating entity/string length.
/// </summary>
public sealed class EntityValidator : IDisposable
{
    internal IntPtr Handle { get; }

    internal EntityValidator(IntPtr handle)
    {
        Handle = handle;
    }

    public void Dispose()
    {
        // Native free will be called by the runtime
    }
}
