// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3539d73033e053b5faf21d8f84f3fe9c6c650d1aa8f3407811022ea33278953b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Error metadata (for batch operations).
/// </summary>
public sealed class ErrorMetadata
{
    [JsonPropertyName("error_type")]
    public string ErrorType { get; set; } = "";

    [JsonPropertyName("message")]
    public string Message { get; set; } = "";

}
