// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f7c445ecbd311efef96e04101d360cf5c6879ad6842773add39cdc6c5e5a54cd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Excel workbook representation.
///
/// Contains all sheets from an Excel file (.xlsx, .xls, etc.) with
/// extracted content and metadata.
/// </summary>
public sealed class ExcelWorkbook
{
    /// <summary>
    /// All sheets in the workbook
    /// </summary>
    [JsonPropertyName("sheets")]
    public List<ExcelSheet> Sheets { get; set; } = [];

    /// <summary>
    /// Workbook-level metadata (author, creation date, etc.)
    /// </summary>
    [JsonPropertyName("metadata")]
    public Dictionary<string, string> Metadata { get; set; } = default!;

}
