// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4e55b2afdc29e0f2f83db0f55b4744401e04ada03e9dd4fa077d55a14e21f667
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Excel/spreadsheet metadata.
///
/// Contains information about sheets in Excel, OpenDocument Calc, and other
/// spreadsheet formats (.xlsx, .xls, .ods, etc.).
/// </summary>
public sealed class ExcelMetadata
{
    /// <summary>
    /// Total number of sheets in the workbook
    /// </summary>
    [JsonPropertyName("sheet_count")]
    public ulong SheetCount { get; set; } = 0;

    /// <summary>
    /// Names of all sheets in order
    /// </summary>
    [JsonPropertyName("sheet_names")]
    public List<string> SheetNames { get; set; } = [];

}
