// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class FileHeader
{
    [JsonPropertyName("flags")]
    public uint Flags { get; set; } = 0;

}
