// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3c856a1381ac3b8430c4515dceead495b7dd0f01ba5f4facd26422c08e136330
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Health check response.
/// </summary>
public sealed class HealthResponse
{
    /// <summary>
    /// Health status
    /// </summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = "";

    /// <summary>
    /// API version
    /// </summary>
    [JsonPropertyName("version")]
    public string Version { get; set; } = "";

    /// <summary>
    /// Plugin status (optional)
    /// </summary>
    [JsonPropertyName("plugins")]
    public string? Plugins { get; set; } = null;

}
