// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Result of HTML extraction with optional images and warnings.
/// </summary>
public sealed class HtmlExtractionResult
{
    [JsonPropertyName("markdown")]
    public string Markdown { get; set; } = "";

    [JsonPropertyName("images")]
    public List<ExtractedInlineImage> Images { get; set; } = [];

    [JsonPropertyName("warnings")]
    public List<string> Warnings { get; set; } = [];

}
