// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:aa56f5fcc82cc0c2eb4d97ea67db9616732714a1e02f4fdf86f49ade68bf8e06
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Result of HTML extraction with optional images and warnings.
/// </summary>
public sealed class HtmlExtractionResult
{
    [JsonPropertyName("markdown")]
    public string Markdown { get; set; } = "";

    [JsonPropertyName("images")]
    public List<ExtractedInlineImage> Images { get; set; } = [];

    [JsonPropertyName("warnings")]
    public List<string> Warnings { get; set; } = [];

}
