// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:311d48a907d16ff7adec8eb6af91bd3c0646ef61787ff909f2f71ded7198d73e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Built-in HTML theme selection.
/// </summary>
public enum HtmlTheme
{
    /// <summary>
    /// Sensible defaults: system font stack, neutral colours, readable line
    /// measure. CSS custom properties (`--kb-*`) are all defined so user CSS
    /// can override individual values.
    /// </summary>
    [JsonPropertyName("default")]
    Default,
    /// <summary>
    /// GitHub Markdown-inspired palette and spacing.
    /// </summary>
    [JsonPropertyName("github")]
    GitHub,
    /// <summary>
    /// Dark background, light text.
    /// </summary>
    [JsonPropertyName("dark")]
    Dark,
    /// <summary>
    /// Minimal light theme with generous whitespace.
    /// </summary>
    [JsonPropertyName("light")]
    Light,
    /// <summary>
    /// No built-in stylesheet emitted. CSS custom properties are still defined
    /// on `:root` so user stylesheets can reference `var(--kb-*)` tokens.
    /// </summary>
    [JsonPropertyName("unstyled")]
    Unstyled,
}
