// This file is auto-generated by alef. DO NOT EDIT.
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Error type for HWP parsing.
/// </summary>
public enum HwpError
{
    /// <summary>
    /// The file does not match the HWP 5.0 format.
    /// </summary>
    [JsonPropertyName("invalidformat")]
    InvalidFormat,
    /// <summary>
    /// The HWP version or a feature is not supported (e.g. password-encrypted docs).
    /// </summary>
    [JsonPropertyName("unsupportedversion")]
    UnsupportedVersion,
    /// <summary>
    /// An underlying I/O error occurred.
    /// </summary>
    [JsonPropertyName("io")]
    Io,
    /// <summary>
    /// A CFB compound-file error (stream not found, corrupt container, etc.).
    /// </summary>
    [JsonPropertyName("cfb")]
    Cfb,
    /// <summary>
    /// Decompression of a zlib/deflate stream failed.
    /// </summary>
    [JsonPropertyName("compressionerror")]
    CompressionError,
    /// <summary>
    /// The binary record stream could not be parsed.
    /// </summary>
    [JsonPropertyName("parseerror")]
    ParseError,
    /// <summary>
    /// A UTF-16LE string contained invalid data.
    /// </summary>
    [JsonPropertyName("encodingerror")]
    EncodingError,
    /// <summary>
    /// A requested stream was not present in the compound file.
    /// </summary>
    [JsonPropertyName("notfound")]
    NotFound,
}
