// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e0208f9aae9271d8ea1e5f41dc1a17fc91936af5a072982a335e1463b1280bba
#nullable enable

using System;

namespace Kreuzberg;

public class ImageProcessingException : KreuzbergErrorException
{
    public ImageProcessingException(string message) : base(message) { }

    public ImageProcessingException(string message, Exception innerException) : base(message, innerException) { }
}
