// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Server information response.
/// </summary>
public sealed class InfoResponse
{
    /// <summary>
    /// API version
    /// </summary>
    [JsonPropertyName("version")]
    public string Version { get; set; } = "";

    /// <summary>
    /// Whether using Rust backend
    /// </summary>
    [JsonPropertyName("rust_backend")]
    public bool RustBackend { get; set; } = false;

}
