// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class JsonExtractionConfig
{
    [JsonPropertyName("extract_schema")]
    public bool ExtractSchema { get; set; } = false;

    [JsonPropertyName("max_depth")]
    public ulong MaxDepth { get; set; } = 20;

    [JsonPropertyName("array_item_limit")]
    public ulong ArrayItemLimit { get; set; } = 500;

    [JsonPropertyName("include_type_info")]
    public bool IncludeTypeInfo { get; set; } = false;

    [JsonPropertyName("flatten_nested_objects")]
    public bool FlattenNestedObjects { get; set; } = true;

    [JsonPropertyName("custom_text_field_patterns")]
    public List<string> CustomTextFieldPatterns { get; set; } = [];

}
