// This file is auto-generated by alef. DO NOT EDIT.
using System;

namespace Kreuzberg;

/// <summary>
/// Kreuzberg MCP server.
///
/// Provides document extraction capabilities via MCP tools.
///
/// The server loads a default extraction configuration from kreuzberg.toml/yaml/json
/// via discovery. Per-request OCR settings override the defaults.
/// </summary>
public sealed class KreuzbergMcp : IDisposable
{
    internal IntPtr Handle { get; }

    internal KreuzbergMcp(IntPtr handle)
    {
        Handle = handle;
    }

    public void Dispose()
    {
        // Native free will be called by the runtime
    }
}
