// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2f7cdca883b7fafa315a67ff5b8e7b3b75b3f42a4e8527c708d26ca46b9fb292
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A single layout detection result.
/// </summary>
public sealed class LayoutDetection
{
    [JsonPropertyName("class_name")]
    public LayoutClass ClassName { get; set; } = default!;

    [JsonPropertyName("confidence")]
    public float Confidence { get; set; } = 0.0f;

    [JsonPropertyName("bbox")]
    public BBox Bbox { get; set; } = default!;

}
