// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Layout detection configuration.
///
/// Controls layout detection behavior in the extraction pipeline.
/// When set on [`ExtractionConfig`](super::ExtractionConfig), layout detection
/// is enabled for PDF extraction.
/// </summary>
public sealed class LayoutDetectionConfig
{
    /// <summary>
    /// Confidence threshold override (None = use model default).
    /// </summary>
    [JsonPropertyName("confidence_threshold")]
    public float? ConfidenceThreshold { get; set; } = null;

    /// <summary>
    /// Whether to apply postprocessing heuristics (default: true).
    /// </summary>
    [JsonPropertyName("apply_heuristics")]
    public bool ApplyHeuristics { get; set; } = true;

    /// <summary>
    /// Table structure recognition model.
    ///
    /// Controls which model is used for table cell detection within layout-detected
    /// table regions. Defaults to [`TableModel::Tatr`].
    /// </summary>
    [JsonPropertyName("table_model")]
    public TableModel TableModel { get; set; } = default;

}
