// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4b179bc667bec8a3a6cc85db6bd6e9993de87d1f25f8e06dc570f5fb329bc191
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Layout detection configuration.
///
/// Controls layout detection behavior in the extraction pipeline.
/// When set on [`ExtractionConfig`](super::ExtractionConfig), layout detection
/// is enabled for PDF extraction.
/// </summary>
public sealed class LayoutDetectionConfig
{
    /// <summary>
    /// Confidence threshold override (None = use model default).
    /// </summary>
    [JsonPropertyName("confidence_threshold")]
    public float? ConfidenceThreshold { get; set; } = null;

    /// <summary>
    /// Whether to apply postprocessing heuristics (default: true).
    /// </summary>
    [JsonPropertyName("apply_heuristics")]
    public bool ApplyHeuristics { get; set; } = true;

    /// <summary>
    /// Table structure recognition model.
    ///
    /// Controls which model is used for table cell detection within layout-detected
    /// table regions. Defaults to [`TableModel::Tatr`].
    /// </summary>
    [JsonPropertyName("table_model")]
    public TableModel? TableModel { get; set; } = null;

    /// <summary>
    /// Hardware acceleration for ONNX models (layout detection + table structure).
    ///
    /// When set, controls which execution provider (CPU, CUDA, CoreML, TensorRT)
    /// is used for inference. Defaults to `None` (auto-select per platform).
    /// </summary>
    [JsonPropertyName("acceleration")]
    public AccelerationConfig? Acceleration { get; set; } = null;

}
