// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Model manifest entry for cache management.
/// </summary>
public sealed class ManifestEntryResponse
{
    /// <summary>
    /// Relative path within the cache directory
    /// </summary>
    [JsonPropertyName("relative_path")]
    public string RelativePath { get; set; } = "";

    /// <summary>
    /// SHA256 checksum of the model file
    /// </summary>
    [JsonPropertyName("sha256")]
    public string Sha256 { get; set; } = "";

    /// <summary>
    /// Expected file size in bytes
    /// </summary>
    [JsonPropertyName("size_bytes")]
    public ulong SizeBytes { get; set; } = 0;

    /// <summary>
    /// HuggingFace source URL for downloading
    /// </summary>
    [JsonPropertyName("source_url")]
    public string SourceUrl { get; set; } = "";

}
