// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a726fd2becb539907801a18c9c4a1cc5668a8725a47a0a6cf2f368732d96355c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Model manifest response.
/// </summary>
public sealed class ManifestResponse
{
    /// <summary>
    /// Kreuzberg version
    /// </summary>
    [JsonPropertyName("kreuzberg_version")]
    public string KreuzbergVersion { get; set; } = "";

    /// <summary>
    /// Total size of all models in bytes
    /// </summary>
    [JsonPropertyName("total_size_bytes")]
    public ulong TotalSizeBytes { get; set; } = 0;

    /// <summary>
    /// Number of models in the manifest
    /// </summary>
    [JsonPropertyName("model_count")]
    public ulong ModelCount { get; set; } = 0;

    /// <summary>
    /// Individual model entries
    /// </summary>
    [JsonPropertyName("models")]
    public List<ManifestEntryResponse> Models { get; set; } = [];

}
