// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5405bbb5a3f80397035420afcd65aeb74caa2c76a78429c47770b85ed3fef5ee
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A merged chunk produced by [`merge_segments`].
/// </summary>
public sealed class MergedChunk
{
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

    [JsonPropertyName("byte_start")]
    public ulong ByteStart { get; set; } = 0;

    [JsonPropertyName("byte_end")]
    public ulong ByteEnd { get; set; } = 0;

}
