// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class NativeTextStats
{
    [JsonPropertyName("non_whitespace")]
    public ulong NonWhitespace { get; set; } = 0;

    [JsonPropertyName("alnum")]
    public ulong Alnum { get; set; } = 0;

    [JsonPropertyName("meaningful_words")]
    public ulong MeaningfulWords { get; set; } = 0;

    [JsonPropertyName("alnum_ratio")]
    public double AlnumRatio { get; set; } = 0.0;

    /// <summary>
    /// Count of Unicode replacement characters (U+FFFD) indicating encoding failures.
    /// </summary>
    [JsonPropertyName("garbage_char_count")]
    public ulong GarbageCharCount { get; set; } = 0;

    /// <summary>
    /// Fraction of whitespace-delimited words that are 1-2 characters (0.0-1.0).
    /// High values indicate fragmented/garbled text extraction.
    /// </summary>
    [JsonPropertyName("fragmented_word_ratio")]
    public double FragmentedWordRatio { get; set; } = 0.0;

    /// <summary>
    /// Fraction of consecutive word pairs that are identical (0.0-1.0).
    /// High values indicate column scrambling where text is duplicated.
    /// </summary>
    [JsonPropertyName("consecutive_repeat_ratio")]
    public double ConsecutiveRepeatRatio { get; set; } = 0.0;

    /// <summary>
    /// Average word length (by chars). Very low values indicate garbled extraction.
    /// </summary>
    [JsonPropertyName("avg_word_length")]
    public double AvgWordLength { get; set; } = 0.0;

    /// <summary>
    /// Total word count (whitespace-delimited).
    /// </summary>
    [JsonPropertyName("word_count")]
    public ulong WordCount { get; set; } = 0;

}
