// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6457d4631c5f62843fc75a5adc51d9b6152588db59454c1752739b4086d6de5a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class Note
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = "";

    [JsonPropertyName("note_type")]
    public string NoteType { get; set; } = "";

    [JsonPropertyName("paragraphs")]
    public List<string> Paragraphs { get; set; } = [];

}
