// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e2dc2f889e85cfaf37a1ffd083e6040d888afd5da86b6be2ed287935b8a54c54
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class Note
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = "";

    [JsonPropertyName("note_type")]
    public string NoteType { get; set; } = "";

    [JsonPropertyName("paragraphs")]
    public List<string> Paragraphs { get; set; } = [];

}
