// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6d0b22667440b184771565602b8db4a52d14490523298d9dc956322d20fa42fa
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Hierarchical level of an OCR element.
///
/// Maps to Tesseract's page segmentation hierarchy and provides
/// equivalent semantics for PaddleOCR.
/// </summary>
public enum OcrElementLevel
{
    /// <summary>
    /// Individual word
    /// </summary>
    [JsonPropertyName("word")]
    Word,
    /// <summary>
    /// Line of text (default for PaddleOCR)
    /// </summary>
    [JsonPropertyName("line")]
    Line,
    /// <summary>
    /// Paragraph or text block
    /// </summary>
    [JsonPropertyName("block")]
    Block,
    /// <summary>
    /// Page-level element
    /// </summary>
    [JsonPropertyName("page")]
    Page,
}
