// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8777e013428ccf26143c6da2423e8fcf6a032a8a9a853d490bf61ba6dbe30dce
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Hierarchical level of an OCR element.
///
/// Maps to Tesseract's page segmentation hierarchy and provides
/// equivalent semantics for PaddleOCR.
/// </summary>
public enum OcrElementLevel
{
    /// <summary>
    /// Individual word
    /// </summary>
    [JsonPropertyName("word")]
    Word,
    /// <summary>
    /// Line of text (default for PaddleOCR)
    /// </summary>
    [JsonPropertyName("line")]
    Line,
    /// <summary>
    /// Paragraph or text block
    /// </summary>
    [JsonPropertyName("block")]
    Block,
    /// <summary>
    /// Page-level element
    /// </summary>
    [JsonPropertyName("page")]
    Page,
}
