// This file is auto-generated by alef. DO NOT EDIT.
using System;

namespace Kreuzberg;

/// <summary>
/// High-performance ODT extractor using native Rust XML parsing.
///
/// This extractor provides:
/// - Fast text extraction via roxmltree XML parsing
/// - Comprehensive metadata extraction from meta.xml
/// - Table extraction with row and cell support
/// - Formatting preservation (bold, italic, strikeout)
/// - Support for headings, paragraphs, and special elements
/// </summary>
public sealed class OdtExtractor : IDisposable
{
    internal IntPtr Handle { get; }

    internal OdtExtractor(IntPtr handle)
    {
        Handle = handle;
    }

    public void Dispose()
    {
        // Native free will be called by the runtime
    }
}
