// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:004ac69cddeec6ec8776d9f1a32fea407fedb3c2134524ce095887388a4d7c1a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Page hierarchy structure containing heading levels and block information.
///
/// Used when PDF text hierarchy extraction is enabled. Contains hierarchical
/// blocks with heading levels (H1-H6) for semantic document structure.
/// </summary>
public sealed class PageHierarchy
{
    /// <summary>
    /// Number of hierarchy blocks on this page
    /// </summary>
    [JsonPropertyName("block_count")]
    public ulong BlockCount { get; set; } = 0;

    /// <summary>
    /// Hierarchical blocks with heading levels
    /// </summary>
    [JsonPropertyName("blocks")]
    public List<HierarchicalBlock> Blocks { get; set; } = [];

}
