// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Layout detection results for a single page.
/// </summary>
public sealed class PageLayoutResult
{
    [JsonPropertyName("page_index")]
    public ulong PageIndex { get; set; } = 0;

    [JsonPropertyName("regions")]
    public List<string> Regions { get; set; } = [];

    [JsonPropertyName("page_width_pts")]
    public float PageWidthPts { get; set; } = 0.0;

    [JsonPropertyName("page_height_pts")]
    public float PageHeightPts { get; set; } = 0.0;

    /// <summary>
    /// Width of the rendered image used for layout detection (pixels).
    /// </summary>
    [JsonPropertyName("render_width_px")]
    public uint RenderWidthPx { get; set; } = 0;

    /// <summary>
    /// Height of the rendered image used for layout detection (pixels).
    /// </summary>
    [JsonPropertyName("render_height_px")]
    public uint RenderHeightPx { get; set; } = 0;

}
