// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class PageRenderOptions
{
    [JsonPropertyName("target_dpi")]
    public int TargetDpi { get; set; } = 300;

    [JsonPropertyName("max_image_dimension")]
    public int MaxImageDimension { get; set; } = 65536;

    [JsonPropertyName("auto_adjust_dpi")]
    public bool AutoAdjustDpi { get; set; } = true;

    [JsonPropertyName("min_dpi")]
    public int MinDpi { get; set; } = 72;

    [JsonPropertyName("max_dpi")]
    public int MaxDpi { get; set; } = 600;

}
