// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// PDF extraction backend selection.
///
/// Controls which PDF library is used for text extraction:
/// - `Pdfium`: pdfium-render (default, C++ based, mature)
/// - `PdfOxide`: pdf_oxide (pure Rust, faster, requires `pdf-oxide` feature)
/// - `Auto`: automatically select based on available features
/// </summary>
public enum PdfBackend
{
    /// <summary>
    /// Use pdfium-render backend (default).
    /// </summary>
    [JsonPropertyName("pdfium")]
    Pdfium,
    /// <summary>
    /// Use pdf_oxide backend (pure Rust). Requires `pdf-oxide` feature.
    /// </summary>
    [JsonPropertyName("pdfoxide")]
    PdfOxide,
    /// <summary>
    /// Automatically select the best available backend.
    /// </summary>
    [JsonPropertyName("auto")]
    Auto,
}
