// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8df3578539407016274b308872c34e370520431bbe5e4eaac14da5db7e8c5421
#nullable enable

using System;

namespace Kreuzberg;

public class PluginException : KreuzbergErrorException
{
    public PluginException(string message) : base(message) { }

    public PluginException(string message, Exception innerException) : base(message, innerException) { }
}
