// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Configuration for the string buffer pool.
/// </summary>
public sealed class PoolConfig
{
    /// <summary>
    /// Maximum buffers per size bucket
    /// </summary>
    [JsonPropertyName("max_buffers_per_size")]
    public ulong MaxBuffersPerSize { get; set; } = 4;

    /// <summary>
    /// Initial capacity for new buffers
    /// </summary>
    [JsonPropertyName("initial_capacity")]
    public ulong InitialCapacity { get; set; } = 4096;

    /// <summary>
    /// Maximum capacity before discarding
    /// </summary>
    [JsonPropertyName("max_capacity_before_discard")]
    public ulong MaxCapacityBeforeDiscard { get; set; } = 65536;

}
