// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:37a43fe31b31cc0bf5240063ea6397b50123785adb02ee875eaa2468c3df4dcb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Error type for pool operations.
/// </summary>
public enum PoolError
{
    /// <summary>
    /// The pool's internal mutex was poisoned.
    ///
    /// This indicates a panic occurred while holding the lock.
    /// The pool is in a locked state and cannot be recovered.
    /// </summary>
    [JsonPropertyName("lockpoisoned")]
    LockPoisoned,
}
