// This file is auto-generated by alef. DO NOT EDIT.
using System;

namespace Kreuzberg;

/// <summary>
/// Registry for post-processor plugins.
///
/// Manages post-processors organized by processing stage.
/// </summary>
public sealed class PostProcessorRegistry : IDisposable
{
    internal IntPtr Handle { get; }

    internal PostProcessorRegistry(IntPtr handle)
    {
        Handle = handle;
    }

    public void Dispose()
    {
        // Native free will be called by the runtime
    }
}
