// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Result of PPT text extraction.
/// </summary>
public sealed class PptExtractionResult
{
    /// <summary>
    /// Extracted text content, with slides separated by double newlines.
    /// </summary>
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

    /// <summary>
    /// Number of slides found.
    /// </summary>
    [JsonPropertyName("slide_count")]
    public ulong SlideCount { get; set; } = 0;

    /// <summary>
    /// Document metadata.
    /// </summary>
    [JsonPropertyName("metadata")]
    public PptMetadata Metadata { get; set; } = default!;

    /// <summary>
    /// Speaker notes text per slide (if available).
    /// </summary>
    [JsonPropertyName("speaker_notes")]
    public List<string> SpeakerNotes { get; set; } = [];

}
