// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d675a24059e0cb2abe0a460978f13f17752adbef5e5f856a2f5ff8149cbb83d8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Page Segmentation Mode for Tesseract OCR
/// </summary>
public enum PsmMode
{
    [JsonPropertyName("osdonly")]
    OsdOnly,
    [JsonPropertyName("autoosd")]
    AutoOsd,
    [JsonPropertyName("autoonly")]
    AutoOnly,
    [JsonPropertyName("auto")]
    Auto,
    [JsonPropertyName("singlecolumn")]
    SingleColumn,
    [JsonPropertyName("singleblockvertical")]
    SingleBlockVertical,
    [JsonPropertyName("singleblock")]
    SingleBlock,
    [JsonPropertyName("singleline")]
    SingleLine,
    [JsonPropertyName("singleword")]
    SingleWord,
    [JsonPropertyName("circleword")]
    CircleWord,
    [JsonPropertyName("singlechar")]
    SingleChar,
}
