// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Pre-computed table markdown for a table detection region.
/// </summary>
public sealed class RecognizedTable
{
    /// <summary>
    /// Detection bbox that this table corresponds to (for matching).
    /// </summary>
    [JsonPropertyName("detection_bbox")]
    public BBox DetectionBbox { get; set; } = default!;

    /// <summary>
    /// Table cells as a 2D vector (rows x columns).
    /// </summary>
    [JsonPropertyName("cells")]
    public List<List<string>> Cells { get; set; } = [];

    /// <summary>
    /// Rendered markdown table.
    /// </summary>
    [JsonPropertyName("markdown")]
    public string Markdown { get; set; } = "";

}
