// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b3bae41df0a69c01a935493972c771dd9cda1479eadc71bcbb094992f378ad2a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

public enum ReductionLevel
{
    [JsonPropertyName("off")]
    Off,
    [JsonPropertyName("light")]
    Light,
    [JsonPropertyName("moderate")]
    Moderate,
    [JsonPropertyName("aggressive")]
    Aggressive,
    [JsonPropertyName("maximum")]
    Maximum,
}
