// This file is auto-generated by alef. DO NOT EDIT.
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Target of a relationship — either a resolved element index or an unresolved key.
/// </summary>
public enum RelationshipTarget
{
    /// <summary>
    /// Resolved: index into `InternalDocument::elements`.
    /// </summary>
    [JsonPropertyName("index")]
    Index,
    /// <summary>
    /// Unresolved: key to be matched against element anchors during derivation.
    /// </summary>
    [JsonPropertyName("key")]
    Key,
}
