// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Fully resolved (flattened) style after walking the inheritance chain.
/// </summary>
public sealed class ResolvedStyle
{
    [JsonPropertyName("paragraph_properties")]
    public string ParagraphProperties { get; set; } = "";

    [JsonPropertyName("run_properties")]
    public RunProperties RunProperties { get; set; } = default!;

}
