// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Row-level properties from `<w:trPr>`.
/// </summary>
public sealed class RowProperties
{
    [JsonPropertyName("height")]
    public int? Height { get; set; } = null;

    [JsonPropertyName("height_rule")]
    public string? HeightRule { get; set; } = null;

    [JsonPropertyName("is_header")]
    public bool IsHeader { get; set; } = false;

    [JsonPropertyName("cant_split")]
    public bool CantSplit { get; set; } = false;

}
