// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:01820eaf7c7d211b3035f38be7dc0812ba610da271e270d2dd59d39a7c537e02
#nullable enable

using System;

namespace Kreuzberg;

public class SecurityException : KreuzbergErrorException
{
    public SecurityException(string message) : base(message) { }

    public SecurityException(string message, Exception innerException) : base(message, innerException) { }
}
