// This file is auto-generated by alef. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class StructuredDataResult
{
    [JsonPropertyName("content")]
    public string Content { get; set; } = "";

    [JsonPropertyName("format")]
    public string Format { get; set; } = "";

    [JsonPropertyName("metadata")]
    public Dictionary<string, string> Metadata { get; set; } = default!;

    [JsonPropertyName("text_fields")]
    public List<string> TextFields { get; set; } = [];

}
