// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0ed2d31e654973cdbe822f18f83563f9ce19d6040d0ea531a5154ef3cc7d9ede
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class StructuredDataResult
{
    [JsonPropertyName("content")]
    public string Content { get; set; } = "";

    [JsonPropertyName("format")]
    public string Format { get; set; } = "";

    [JsonPropertyName("metadata")]
    public Dictionary<string, string> Metadata { get; set; } = default!;

    [JsonPropertyName("text_fields")]
    public List<string> TextFields { get; set; } = [];

}
