// This file is auto-generated by alef. DO NOT EDIT.
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// The type of a style definition in DOCX.
/// </summary>
public enum StyleType
{
    [JsonPropertyName("paragraph")]
    Paragraph,
    [JsonPropertyName("character")]
    Character,
    [JsonPropertyName("table")]
    Table,
    [JsonPropertyName("numbering")]
    Numbering,
}
