// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:23cd17989dd1e984bd779198ed0ffb2c039e87efec6132ad827f021d15294411
#nullable enable

using System;

namespace Kreuzberg;

public class TimeoutException : KreuzbergErrorException
{
    public TimeoutException(string message) : base(message) { }

    public TimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
