// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a11be9c0fda534a647c5a1a628b5aa30194964d9a943f260c81aa4bb45724a26
#nullable enable

using System;

namespace Kreuzberg;

public class TimeoutException : KreuzbergErrorException
{
    public TimeoutException(string message) : base(message) { }

    public TimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
