// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:95b8bc575545e57330ad7091f505a07a99a3826768e8fd0b866c07e806a7b3aa
#nullable enable

using System;

namespace Kreuzberg;

public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
