// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0c3b8b25adb8eecb2d79e80cb561871e0b79518bb87dc992367d83a32e9643cc
#nullable enable

using System;

namespace Kreuzberg;

public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
