// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:84a78d3f9c498206d68c48dc3c835b8d23f2c683eedff9ba409e124c9f9b78ce
#nullable enable

using System;

namespace Kreuzberg;

public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
