// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c0a959bd6a03ef5961dfc8db70836cdafa4a9ab449a568a6db98ba6902310330
#nullable enable

using System;

namespace Kreuzberg;

public class ValidationException : KreuzbergErrorException
{
    public ValidationException(string message) : base(message) { }

    public ValidationException(string message, Exception innerException) : base(message, innerException) { }
}
