// This file is auto-generated by alef. DO NOT EDIT.
using System;

namespace Kreuzberg;

/// <summary>
/// Registry for validator plugins.
///
/// Manages validators with priority-based execution order.
/// </summary>
public sealed class ValidatorRegistry : IDisposable
{
    internal IntPtr Handle { get; }

    internal ValidatorRegistry(IntPtr handle)
    {
        Handle = handle;
    }

    public void Dispose()
    {
        // Native free will be called by the runtime
    }
}
