// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9fbb222d128f45e2ed42e736f716140fbacac60101ddd60918907eed98a91f15
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Version response.
/// </summary>
public sealed class VersionResponse
{
    /// <summary>
    /// Kreuzberg version string
    /// </summary>
    [JsonPropertyName("version")]
    public string Version { get; set; } = "";

}
