// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Cache warm request.
/// </summary>
public sealed class WarmRequest
{
    /// <summary>
    /// Download all embedding model presets
    /// </summary>
    [JsonPropertyName("all_embeddings")]
    public bool AllEmbeddings { get; set; } = false;

    /// <summary>
    /// Specific embedding model preset to download
    /// </summary>
    [JsonPropertyName("embedding_model")]
    public string? EmbeddingModel { get; set; } = null;

}
