// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7dcf11c0b1b962405d82664b78f0a648cc04192f9e0c7d4c3f15b93626020ded
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Cache warm request.
/// </summary>
public sealed class WarmRequest
{
    /// <summary>
    /// Download all embedding model presets
    /// </summary>
    [JsonPropertyName("all_embeddings")]
    public bool AllEmbeddings { get; set; } = false;

    /// <summary>
    /// Specific embedding model preset to download
    /// </summary>
    [JsonPropertyName("embedding_model")]
    public string? EmbeddingModel { get; set; } = null;

}
