// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f059e1b772308da62ea9e5093ad379a6f9015d5cebce2dcb1beca0a7a620930c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// XML metadata extracted during XML parsing.
///
/// Provides statistics about XML document structure.
/// </summary>
public sealed class XmlMetadata
{
    /// <summary>
    /// Total number of XML elements processed
    /// </summary>
    [JsonPropertyName("element_count")]
    public ulong ElementCount { get; set; } = 0;

    /// <summary>
    /// List of unique element tag names (sorted)
    /// </summary>
    [JsonPropertyName("unique_elements")]
    public List<string> UniqueElements { get; set; } = [];

}
