// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;

public class ArchiveMetadataBuilder {

    private String format = "";
    private long fileCount = 0;
    private List<String> fileList = List.of();
    private long totalSize = 0;
    private Optional<Long> compressedSize = Optional.empty();

    public ArchiveMetadataBuilder withFormat(String value) {
        this.format = value;
        return this;
    }

    public ArchiveMetadataBuilder withFileCount(long value) {
        this.fileCount = value;
        return this;
    }

    public ArchiveMetadataBuilder withFileList(List<String> value) {
        this.fileList = value;
        return this;
    }

    public ArchiveMetadataBuilder withTotalSize(long value) {
        this.totalSize = value;
        return this;
    }

    public ArchiveMetadataBuilder withCompressedSize(Optional<Long> value) {
        this.compressedSize = value;
        return this;
    }

    public ArchiveMetadata build() {
        return new ArchiveMetadata(
            format,
            fileCount,
            fileList,
            totalSize,
            compressedSize
        );
    }
}
