// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

public record ArchiveEntry(
    String path,
    @JsonProperty("mime_type") String mimeType,
    ExtractionResult result
) {
}
