// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.List;
import java.util.Map;
import java.util.Optional;

public class BibtexMetadataBuilder {

    private long entryCount = 0;
    private List<String> citationKeys = List.of();
    private List<String> authors = List.of();
    private Optional<YearRange> yearRange = Optional.empty();
    private Optional<Map<String, Long>> entryTypes = Optional.empty();

    public BibtexMetadataBuilder withEntryCount(long value) {
        this.entryCount = value;
        return this;
    }

    public BibtexMetadataBuilder withCitationKeys(List<String> value) {
        this.citationKeys = value;
        return this;
    }

    public BibtexMetadataBuilder withAuthors(List<String> value) {
        this.authors = value;
        return this;
    }

    public BibtexMetadataBuilder withYearRange(Optional<YearRange> value) {
        this.yearRange = value;
        return this;
    }

    public BibtexMetadataBuilder withEntryTypes(Optional<Map<String, Long>> value) {
        this.entryTypes = value;
        return this;
    }

    public BibtexMetadata build() {
        return new BibtexMetadata(
            entryCount,
            citationKeys,
            authors,
            yearRange,
            entryTypes
        );
    }
}
