// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * BibTeX bibliography extractor.
 * 
 * Parses BibTeX files and extracts structured bibliography data including
 * entries, authors, publication years, and entry type distribution.
 */
public class BibtexExtractor implements AutoCloseable {
    private final MemorySegment handle;

    BibtexExtractor(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_BIBTEX_EXTRACTOR_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free BibtexExtractor: " + e.getMessage(), e);
            }
        }
    }
}
