// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

public record CacheStatsResponse(
    String directory,
    @JsonProperty("total_files") long totalFiles,
    @JsonProperty("total_size_mb") double totalSizeMb,
    @JsonProperty("available_space_mb") double availableSpaceMb,
    @JsonProperty("oldest_file_age_days") double oldestFileAgeDays,
    @JsonProperty("newest_file_age_days") double newestFileAgeDays
) {
}
