// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.Optional;

public record CellShading(Optional<String> fill, Optional<String> color, Optional<String> val) {
    public static CellShadingBuilder builder() {
        return new CellShadingBuilder();
    }
}
