// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record Chunk(
    String content,
    @JsonProperty("chunk_type") ChunkType chunkType,
    Optional<List<Float>> embedding,
    ChunkMetadata metadata
) {
}
