// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum ContentLayer {
    Body("body"),
    Header("header"),
    Footer("footer"),
    Footnote("footnote");

    private final String value;

    ContentLayer(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @JsonCreator
    public static ContentLayer fromValue(String value) {
        for (ContentLayer e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
