// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;


public class ContentFilterConfigBuilder {

    private boolean includeHeaders = false;
    private boolean includeFooters = false;
    private boolean stripRepeatingText = false;
    private boolean includeWatermarks = false;

    public ContentFilterConfigBuilder withIncludeHeaders(boolean value) {
        this.includeHeaders = value;
        return this;
    }

    public ContentFilterConfigBuilder withIncludeFooters(boolean value) {
        this.includeFooters = value;
        return this;
    }

    public ContentFilterConfigBuilder withStripRepeatingText(boolean value) {
        this.stripRepeatingText = value;
        return this;
    }

    public ContentFilterConfigBuilder withIncludeWatermarks(boolean value) {
        this.includeWatermarks = value;
        return this;
    }

    public ContentFilterConfig build() {
        return new ContentFilterConfig(
            includeHeaders,
            includeFooters,
            stripRepeatingText,
            includeWatermarks
        );
    }
}
