// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;

public class CsvMetadataBuilder {

    private long rowCount = 0;
    private long columnCount = 0;
    private Optional<String> delimiter = Optional.empty();
    private boolean hasHeader = false;
    private Optional<List<String>> columnTypes = Optional.empty();

    public CsvMetadataBuilder withRowCount(long value) {
        this.rowCount = value;
        return this;
    }

    public CsvMetadataBuilder withColumnCount(long value) {
        this.columnCount = value;
        return this;
    }

    public CsvMetadataBuilder withDelimiter(Optional<String> value) {
        this.delimiter = value;
        return this;
    }

    public CsvMetadataBuilder withHasHeader(boolean value) {
        this.hasHeader = value;
        return this;
    }

    public CsvMetadataBuilder withColumnTypes(Optional<List<String>> value) {
        this.columnTypes = value;
        return this;
    }

    public CsvMetadata build() {
        return new CsvMetadata(
            rowCount,
            columnCount,
            delimiter,
            hasHeader,
            columnTypes
        );
    }
}
