// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.Optional;

public record DjotLink(
    String url,
    String text,
    Optional<String> title,
    Optional<Attributes> attributes
) {
}
