// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record DocMetadata(
    Optional<String> title,
    Optional<String> subject,
    Optional<String> author,
    @JsonProperty("last_author") Optional<String> lastAuthor,
    Optional<String> created,
    Optional<String> modified,
    @JsonProperty("revision_number") Optional<String> revisionNumber
) {
    public static DocMetadataBuilder builder() {
        return new DocMetadataBuilder();
    }
}
