// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record Document(
    List<String> paragraphs,
    List<Table> tables,
    List<HeaderFooter> headers,
    List<HeaderFooter> footers,
    List<Note> footnotes,
    List<Note> endnotes,
    @JsonProperty("numbering_defs") String numberingDefs,
    List<DocumentElement> elements,
    @JsonProperty("style_catalog") Optional<StyleCatalog> styleCatalog,
    Optional<Theme> theme,
    List<SectionProperties> sections,
    List<Drawing> drawings,
    @JsonProperty("image_relationships") String imageRelationships
) {
    public static DocumentBuilder builder() {
        return new DocumentBuilder();
    }
}
