// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;

public class DocumentBuilder {

    private List<String> paragraphs = List.of();
    private List<Table> tables = List.of();
    private List<HeaderFooter> headers = List.of();
    private List<HeaderFooter> footers = List.of();
    private List<Note> footnotes = List.of();
    private List<Note> endnotes = List.of();
    private String numberingDefs = "";
    private List<DocumentElement> elements = List.of();
    private Optional<StyleCatalog> styleCatalog = Optional.empty();
    private Optional<Theme> theme = Optional.empty();
    private List<SectionProperties> sections = List.of();
    private List<Drawing> drawings = List.of();
    private String imageRelationships = "";

    public DocumentBuilder withParagraphs(List<String> value) {
        this.paragraphs = value;
        return this;
    }

    public DocumentBuilder withTables(List<Table> value) {
        this.tables = value;
        return this;
    }

    public DocumentBuilder withHeaders(List<HeaderFooter> value) {
        this.headers = value;
        return this;
    }

    public DocumentBuilder withFooters(List<HeaderFooter> value) {
        this.footers = value;
        return this;
    }

    public DocumentBuilder withFootnotes(List<Note> value) {
        this.footnotes = value;
        return this;
    }

    public DocumentBuilder withEndnotes(List<Note> value) {
        this.endnotes = value;
        return this;
    }

    public DocumentBuilder withNumberingDefs(String value) {
        this.numberingDefs = value;
        return this;
    }

    public DocumentBuilder withElements(List<DocumentElement> value) {
        this.elements = value;
        return this;
    }

    public DocumentBuilder withStyleCatalog(Optional<StyleCatalog> value) {
        this.styleCatalog = value;
        return this;
    }

    public DocumentBuilder withTheme(Optional<Theme> value) {
        this.theme = value;
        return this;
    }

    public DocumentBuilder withSections(List<SectionProperties> value) {
        this.sections = value;
        return this;
    }

    public DocumentBuilder withDrawings(List<Drawing> value) {
        this.drawings = value;
        return this;
    }

    public DocumentBuilder withImageRelationships(String value) {
        this.imageRelationships = value;
        return this;
    }

    public Document build() {
        return new Document(
            paragraphs,
            tables,
            headers,
            footers,
            footnotes,
            endnotes,
            numberingDefs,
            elements,
            styleCatalog,
            theme,
            sections,
            drawings,
            imageRelationships
        );
    }
}
