// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * Unique identifier for semantic elements.
 * 
 * Wraps a string identifier that is deterministically generated
 * from element type, content, and page number.
 */
public class ElementId implements AutoCloseable {
    private final MemorySegment handle;

    ElementId(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_ELEMENT_ID_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free ElementId: " + e.getMessage(), e);
            }
        }
    }
}
