// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record EmailAttachment(
    Optional<String> name,
    Optional<String> filename,
    @JsonProperty("mime_type") Optional<String> mimeType,
    Optional<Long> size,
    @JsonProperty("is_image") boolean isImage,
    Optional<byte[]> data
) {
}
