// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;

public class EmailMetadataBuilder {

    private Optional<String> fromEmail = Optional.empty();
    private Optional<String> fromName = Optional.empty();
    private List<String> toEmails = List.of();
    private List<String> ccEmails = List.of();
    private List<String> bccEmails = List.of();
    private Optional<String> messageId = Optional.empty();
    private List<String> attachments = List.of();

    public EmailMetadataBuilder withFromEmail(Optional<String> value) {
        this.fromEmail = value;
        return this;
    }

    public EmailMetadataBuilder withFromName(Optional<String> value) {
        this.fromName = value;
        return this;
    }

    public EmailMetadataBuilder withToEmails(List<String> value) {
        this.toEmails = value;
        return this;
    }

    public EmailMetadataBuilder withCcEmails(List<String> value) {
        this.ccEmails = value;
        return this;
    }

    public EmailMetadataBuilder withBccEmails(List<String> value) {
        this.bccEmails = value;
        return this;
    }

    public EmailMetadataBuilder withMessageId(Optional<String> value) {
        this.messageId = value;
        return this;
    }

    public EmailMetadataBuilder withAttachments(List<String> value) {
        this.attachments = value;
        return this;
    }

    public EmailMetadata build() {
        return new EmailMetadata(
            fromEmail,
            fromName,
            toEmails,
            ccEmails,
            bccEmails,
            messageId,
            attachments
        );
    }
}
