// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record EmailMetadata(
    @JsonProperty("from_email") Optional<String> fromEmail,
    @JsonProperty("from_name") Optional<String> fromName,
    @JsonProperty("to_emails") List<String> toEmails,
    @JsonProperty("cc_emails") List<String> ccEmails,
    @JsonProperty("bcc_emails") List<String> bccEmails,
    @JsonProperty("message_id") Optional<String> messageId,
    List<String> attachments
) {
    public static EmailMetadataBuilder builder() {
        return new EmailMetadataBuilder();
    }
}
