// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record EmbeddedFile(
    String name,
    byte[] data,
    @JsonProperty("mime_type") Optional<String> mimeType
) {
}
