// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record EmbedTextParams(
    List<String> texts,
    Optional<String> preset,
    Optional<String> model,
    @JsonProperty("api_key") Optional<String> apiKey
) {
}
