// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * Empty parameters for tools that take no arguments.
 * 
 * This generates `{"type": "object", "properties": {}}` which is required by
 * the MCP specification, unlike `()` which generates `{"const": null}`.
 */
public class EmptyParams implements AutoCloseable {
    private final MemorySegment handle;

    EmptyParams(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_EMPTY_PARAMS_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free EmptyParams: " + e.getMessage(), e);
            }
        }
    }
}
