// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * EPUB format extractor using permissive-licensed dependencies.
 * 
 * Extracts content and metadata from EPUB files (both EPUB2 and EPUB3)
 * using native Rust parsing without GPL-licensed dependencies.
 */
public class EpubExtractor implements AutoCloseable {
    private final MemorySegment handle;

    EpubExtractor(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_EPUB_EXTRACTOR_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free EpubExtractor: " + e.getMessage(), e);
            }
        }
    }
}
