// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record ErrorResponse(
    @JsonProperty("error_type") String errorType,
    String message,
    Optional<String> traceback,
    @JsonProperty("status_code") short statusCode
) {
}
