// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record ExcelSheet(
    String name,
    String markdown,
    @JsonProperty("row_count") long rowCount,
    @JsonProperty("col_count") long colCount,
    @JsonProperty("cell_count") long cellCount,
    @JsonProperty("table_cells") Optional<List<List<String>>> tableCells
) {
}
