// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * Builder for composing an extraction service with Tower middleware layers.
 * 
 * Layers are applied in the order: Tracing → Metrics → Timeout → ConcurrencyLimit → Service.
 */
public class ExtractionServiceBuilder implements AutoCloseable {
    private final MemorySegment handle;

    ExtractionServiceBuilder(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_EXTRACTION_SERVICE_BUILDER_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free ExtractionServiceBuilder: " + e.getMessage(), e);
            }
        }
    }
}
