// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;

public record FictionBookMetadata(
    List<String> genres,
    List<String> sequences,
    Optional<String> annotation
) {
    public static FictionBookMetadataBuilder builder() {
        return new FictionBookMetadataBuilder();
    }
}
