// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;

public class FictionBookMetadataBuilder {

    private List<String> genres = List.of();
    private List<String> sequences = List.of();
    private Optional<String> annotation = Optional.empty();

    public FictionBookMetadataBuilder withGenres(List<String> value) {
        this.genres = value;
        return this;
    }

    public FictionBookMetadataBuilder withSequences(List<String> value) {
        this.sequences = value;
        return this;
    }

    public FictionBookMetadataBuilder withAnnotation(Optional<String> value) {
        this.annotation = value;
        return this;
    }

    public FictionBookMetadata build() {
        return new FictionBookMetadata(
            genres,
            sequences,
            annotation
        );
    }
}
