// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

public record HeaderFooter(
    List<String> paragraphs,
    List<Table> tables,
    @JsonProperty("header_type") String headerType
) {
    public static HeaderFooterBuilder builder() {
        return new HeaderFooterBuilder();
    }
}
