// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

public record HierarchyBlock(
    String text,
    BoundingBox bbox,
    @JsonProperty("font_size") float fontSize,
    @JsonProperty("hierarchy_level") String hierarchyLevel
) {
}
