// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.List;
import java.util.Map;
import java.util.Optional;

public class HtmlMetadataBuilder {

    private Optional<String> title = Optional.empty();
    private Optional<String> description = Optional.empty();
    private List<String> keywords = List.of();
    private Optional<String> author = Optional.empty();
    private Optional<String> canonicalUrl = Optional.empty();
    private Optional<String> baseHref = Optional.empty();
    private Optional<String> language = Optional.empty();
    private Optional<TextDirection> textDirection = Optional.empty();
    private Map<String, String> openGraph = Map.of();
    private Map<String, String> twitterCard = Map.of();
    private Map<String, String> metaTags = Map.of();
    private List<HeaderMetadata> headers = List.of();
    private List<LinkMetadata> links = List.of();
    private List<ImageMetadataType> images = List.of();
    private List<StructuredData> structuredData = List.of();

    public HtmlMetadataBuilder withTitle(Optional<String> value) {
        this.title = value;
        return this;
    }

    public HtmlMetadataBuilder withDescription(Optional<String> value) {
        this.description = value;
        return this;
    }

    public HtmlMetadataBuilder withKeywords(List<String> value) {
        this.keywords = value;
        return this;
    }

    public HtmlMetadataBuilder withAuthor(Optional<String> value) {
        this.author = value;
        return this;
    }

    public HtmlMetadataBuilder withCanonicalUrl(Optional<String> value) {
        this.canonicalUrl = value;
        return this;
    }

    public HtmlMetadataBuilder withBaseHref(Optional<String> value) {
        this.baseHref = value;
        return this;
    }

    public HtmlMetadataBuilder withLanguage(Optional<String> value) {
        this.language = value;
        return this;
    }

    public HtmlMetadataBuilder withTextDirection(Optional<TextDirection> value) {
        this.textDirection = value;
        return this;
    }

    public HtmlMetadataBuilder withOpenGraph(Map<String, String> value) {
        this.openGraph = value;
        return this;
    }

    public HtmlMetadataBuilder withTwitterCard(Map<String, String> value) {
        this.twitterCard = value;
        return this;
    }

    public HtmlMetadataBuilder withMetaTags(Map<String, String> value) {
        this.metaTags = value;
        return this;
    }

    public HtmlMetadataBuilder withHeaders(List<HeaderMetadata> value) {
        this.headers = value;
        return this;
    }

    public HtmlMetadataBuilder withLinks(List<LinkMetadata> value) {
        this.links = value;
        return this;
    }

    public HtmlMetadataBuilder withImages(List<ImageMetadataType> value) {
        this.images = value;
        return this;
    }

    public HtmlMetadataBuilder withStructuredData(List<StructuredData> value) {
        this.structuredData = value;
        return this;
    }

    public HtmlMetadata build() {
        return new HtmlMetadata(
            title,
            description,
            keywords,
            author,
            canonicalUrl,
            baseHref,
            language,
            textDirection,
            openGraph,
            twitterCard,
            metaTags,
            headers,
            links,
            images,
            structuredData
        );
    }
}
