// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

public class IoException extends KreuzbergErrorException {
    public IoException(String message) {
        super(message);
    }

    public IoException(String message, Throwable cause) {
        super(message, cause);
    }
}
