// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record JatsMetadata(
    Optional<String> copyright,
    Optional<String> license,
    @JsonProperty("history_dates") Map<String, String> historyDates,
    @JsonProperty("contributor_roles") List<ContributorRole> contributorRoles
) {
    public static JatsMetadataBuilder builder() {
        return new JatsMetadataBuilder();
    }
}
