// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * Apple Keynote presentation extractor.
 * 
 * Supports `.key` files (modern iWork format, 2013+).
 * 
 * Extracts slide text and speaker notes from the IWA container:
 * ZIP → Snappy → protobuf text fields.
 */
public class KeynoteExtractor implements AutoCloseable {
    private final MemorySegment handle;

    KeynoteExtractor(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_KEYNOTE_EXTRACTOR_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free KeynoteExtractor: " + e.getMessage(), e);
            }
        }
    }
}
