// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * Common interface for all layout detection model backends.
 */
public class LayoutModel implements AutoCloseable {
    private final MemorySegment handle;

    LayoutModel(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_LAYOUT_MODEL_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free LayoutModel: " + e.getMessage(), e);
            }
        }
    }
}
