// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.Optional;

public class LlmConfigBuilder {

    private String model = "";
    private Optional<String> apiKey = Optional.empty();
    private Optional<String> baseUrl = Optional.empty();
    private Optional<Long> timeoutSecs = Optional.empty();
    private Optional<Integer> maxRetries = Optional.empty();
    private Optional<Double> temperature = Optional.empty();
    private Optional<Long> maxTokens = Optional.empty();

    public LlmConfigBuilder withModel(String value) {
        this.model = value;
        return this;
    }

    public LlmConfigBuilder withApiKey(Optional<String> value) {
        this.apiKey = value;
        return this;
    }

    public LlmConfigBuilder withBaseUrl(Optional<String> value) {
        this.baseUrl = value;
        return this;
    }

    public LlmConfigBuilder withTimeoutSecs(Optional<Long> value) {
        this.timeoutSecs = value;
        return this;
    }

    public LlmConfigBuilder withMaxRetries(Optional<Integer> value) {
        this.maxRetries = value;
        return this;
    }

    public LlmConfigBuilder withTemperature(Optional<Double> value) {
        this.temperature = value;
        return this;
    }

    public LlmConfigBuilder withMaxTokens(Optional<Long> value) {
        this.maxTokens = value;
        return this;
    }

    public LlmConfig build() {
        return new LlmConfig(
            model,
            apiKey,
            baseUrl,
            timeoutSecs,
            maxRetries,
            temperature,
            maxTokens
        );
    }
}
