// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;

public class MetadataBuilder {

    private Optional<String> title = Optional.empty();
    private Optional<String> subject = Optional.empty();
    private Optional<List<String>> authors = Optional.empty();
    private Optional<List<String>> keywords = Optional.empty();
    private Optional<String> language = Optional.empty();
    private Optional<String> createdAt = Optional.empty();
    private Optional<String> modifiedAt = Optional.empty();
    private Optional<String> createdBy = Optional.empty();
    private Optional<String> modifiedBy = Optional.empty();
    private Optional<PageStructure> pages = Optional.empty();
    private Optional<FormatMetadata> format = Optional.empty();
    private Optional<ImagePreprocessingMetadata> imagePreprocessing = Optional.empty();
    private Optional<Object> jsonSchema = Optional.empty();
    private Optional<ErrorMetadata> error = Optional.empty();
    private Optional<Long> extractionDurationMs = Optional.empty();
    private Optional<String> category = Optional.empty();
    private Optional<List<String>> tags = Optional.empty();
    private Optional<String> documentVersion = Optional.empty();
    private Optional<String> abstractText = Optional.empty();
    private Optional<String> outputFormat = Optional.empty();
    private String additional = "";

    public MetadataBuilder withTitle(Optional<String> value) {
        this.title = value;
        return this;
    }

    public MetadataBuilder withSubject(Optional<String> value) {
        this.subject = value;
        return this;
    }

    public MetadataBuilder withAuthors(Optional<List<String>> value) {
        this.authors = value;
        return this;
    }

    public MetadataBuilder withKeywords(Optional<List<String>> value) {
        this.keywords = value;
        return this;
    }

    public MetadataBuilder withLanguage(Optional<String> value) {
        this.language = value;
        return this;
    }

    public MetadataBuilder withCreatedAt(Optional<String> value) {
        this.createdAt = value;
        return this;
    }

    public MetadataBuilder withModifiedAt(Optional<String> value) {
        this.modifiedAt = value;
        return this;
    }

    public MetadataBuilder withCreatedBy(Optional<String> value) {
        this.createdBy = value;
        return this;
    }

    public MetadataBuilder withModifiedBy(Optional<String> value) {
        this.modifiedBy = value;
        return this;
    }

    public MetadataBuilder withPages(Optional<PageStructure> value) {
        this.pages = value;
        return this;
    }

    public MetadataBuilder withFormat(Optional<FormatMetadata> value) {
        this.format = value;
        return this;
    }

    public MetadataBuilder withImagePreprocessing(Optional<ImagePreprocessingMetadata> value) {
        this.imagePreprocessing = value;
        return this;
    }

    public MetadataBuilder withJsonSchema(Optional<Object> value) {
        this.jsonSchema = value;
        return this;
    }

    public MetadataBuilder withError(Optional<ErrorMetadata> value) {
        this.error = value;
        return this;
    }

    public MetadataBuilder withExtractionDurationMs(Optional<Long> value) {
        this.extractionDurationMs = value;
        return this;
    }

    public MetadataBuilder withCategory(Optional<String> value) {
        this.category = value;
        return this;
    }

    public MetadataBuilder withTags(Optional<List<String>> value) {
        this.tags = value;
        return this;
    }

    public MetadataBuilder withDocumentVersion(Optional<String> value) {
        this.documentVersion = value;
        return this;
    }

    public MetadataBuilder withAbstractText(Optional<String> value) {
        this.abstractText = value;
        return this;
    }

    public MetadataBuilder withOutputFormat(Optional<String> value) {
        this.outputFormat = value;
        return this;
    }

    public MetadataBuilder withAdditional(String value) {
        this.additional = value;
        return this;
    }

    public Metadata build() {
        return new Metadata(
            title,
            subject,
            authors,
            keywords,
            language,
            createdAt,
            modifiedAt,
            createdBy,
            modifiedBy,
            pages,
            format,
            imagePreprocessing,
            jsonSchema,
            error,
            extractionDurationMs,
            category,
            tags,
            documentVersion,
            abstractText,
            outputFormat,
            additional
        );
    }
}
