// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

public record ModelPaths(
    @JsonProperty("det_model") java.nio.file.Path detModel,
    @JsonProperty("cls_model") java.nio.file.Path clsModel,
    @JsonProperty("rec_model") java.nio.file.Path recModel,
    @JsonProperty("dict_file") java.nio.file.Path dictFile
) {
}
