// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

public record NativeTextStats(
    @JsonProperty("non_whitespace") long nonWhitespace,
    long alnum,
    @JsonProperty("meaningful_words") long meaningfulWords,
    @JsonProperty("alnum_ratio") double alnumRatio,
    @JsonProperty("garbage_char_count") long garbageCharCount,
    @JsonProperty("fragmented_word_ratio") double fragmentedWordRatio,
    @JsonProperty("consecutive_repeat_ratio") double consecutiveRepeatRatio,
    @JsonProperty("avg_word_length") double avgWordLength,
    @JsonProperty("word_count") long wordCount
) {
}
