// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;


public class OcrElementConfigBuilder {

    private boolean includeElements = false;
    private OcrElementLevel minLevel = null;
    private double minConfidence = 0.0;
    private boolean buildHierarchy = false;

    public OcrElementConfigBuilder withIncludeElements(boolean value) {
        this.includeElements = value;
        return this;
    }

    public OcrElementConfigBuilder withMinLevel(OcrElementLevel value) {
        this.minLevel = value;
        return this;
    }

    public OcrElementConfigBuilder withMinConfidence(double value) {
        this.minConfidence = value;
        return this;
    }

    public OcrElementConfigBuilder withBuildHierarchy(boolean value) {
        this.buildHierarchy = value;
        return this;
    }

    public OcrElementConfig build() {
        return new OcrElementConfig(
            includeElements,
            minLevel,
            minConfidence,
            buildHierarchy
        );
    }
}
