// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

public class OcrException extends KreuzbergErrorException {
    public OcrException(String message) {
        super(message);
    }

    public OcrException(String message, Throwable cause) {
        super(message, cause);
    }
}
