// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record OdtProperties(
    Optional<String> title,
    Optional<String> subject,
    Optional<String> creator,
    @JsonProperty("initial_creator") Optional<String> initialCreator,
    Optional<String> keywords,
    Optional<String> description,
    Optional<String> date,
    @JsonProperty("creation_date") Optional<String> creationDate,
    Optional<String> language,
    Optional<String> generator,
    @JsonProperty("editing_duration") Optional<String> editingDuration,
    @JsonProperty("editing_cycles") Optional<String> editingCycles,
    @JsonProperty("page_count") Optional<Integer> pageCount,
    @JsonProperty("word_count") Optional<Integer> wordCount,
    @JsonProperty("character_count") Optional<Integer> characterCount,
    @JsonProperty("paragraph_count") Optional<Integer> paragraphCount,
    @JsonProperty("table_count") Optional<Integer> tableCount,
    @JsonProperty("image_count") Optional<Integer> imageCount
) {
    public static OdtPropertiesBuilder builder() {
        return new OdtPropertiesBuilder();
    }
}
