// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum OutputFormat {
    Plain("plain"),
    Markdown("markdown"),
    Djot("djot"),
    Html("html"),
    Json("json"),
    Structured("structured"),
    Custom("custom");

    private final String value;

    OutputFormat(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @JsonCreator
    public static OutputFormat fromValue(String value) {
        for (OutputFormat e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
