// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.Optional;

public class PaddleOcrConfigBuilder {

    private String language = "";
    private Optional<java.nio.file.Path> cacheDir = Optional.empty();
    private boolean useAngleCls = false;
    private boolean enableTableDetection = false;
    private float detDbThresh = 0.0;
    private float detDbBoxThresh = 0.0;
    private float detDbUnclipRatio = 0.0;
    private int detLimitSideLen = 0;
    private int recBatchNum = 0;
    private int padding = 0;
    private float dropScore = 0.0;
    private String modelTier = "";

    public PaddleOcrConfigBuilder withLanguage(String value) {
        this.language = value;
        return this;
    }

    public PaddleOcrConfigBuilder withCacheDir(Optional<java.nio.file.Path> value) {
        this.cacheDir = value;
        return this;
    }

    public PaddleOcrConfigBuilder withUseAngleCls(boolean value) {
        this.useAngleCls = value;
        return this;
    }

    public PaddleOcrConfigBuilder withEnableTableDetection(boolean value) {
        this.enableTableDetection = value;
        return this;
    }

    public PaddleOcrConfigBuilder withDetDbThresh(float value) {
        this.detDbThresh = value;
        return this;
    }

    public PaddleOcrConfigBuilder withDetDbBoxThresh(float value) {
        this.detDbBoxThresh = value;
        return this;
    }

    public PaddleOcrConfigBuilder withDetDbUnclipRatio(float value) {
        this.detDbUnclipRatio = value;
        return this;
    }

    public PaddleOcrConfigBuilder withDetLimitSideLen(int value) {
        this.detLimitSideLen = value;
        return this;
    }

    public PaddleOcrConfigBuilder withRecBatchNum(int value) {
        this.recBatchNum = value;
        return this;
    }

    public PaddleOcrConfigBuilder withPadding(int value) {
        this.padding = value;
        return this;
    }

    public PaddleOcrConfigBuilder withDropScore(float value) {
        this.dropScore = value;
        return this;
    }

    public PaddleOcrConfigBuilder withModelTier(String value) {
        this.modelTier = value;
        return this;
    }

    public PaddleOcrConfig build() {
        return new PaddleOcrConfig(
            language,
            cacheDir,
            useAngleCls,
            enableTableDetection,
            detDbThresh,
            detDbBoxThresh,
            detDbUnclipRatio,
            detLimitSideLen,
            recBatchNum,
            padding,
            dropScore,
            modelTier
        );
    }
}
