// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.Optional;

public class PageMarginsBuilder {

    private Optional<Integer> top = Optional.empty();
    private Optional<Integer> right = Optional.empty();
    private Optional<Integer> bottom = Optional.empty();
    private Optional<Integer> left = Optional.empty();
    private Optional<Integer> header = Optional.empty();
    private Optional<Integer> footer = Optional.empty();
    private Optional<Integer> gutter = Optional.empty();

    public PageMarginsBuilder withTop(Optional<Integer> value) {
        this.top = value;
        return this;
    }

    public PageMarginsBuilder withRight(Optional<Integer> value) {
        this.right = value;
        return this;
    }

    public PageMarginsBuilder withBottom(Optional<Integer> value) {
        this.bottom = value;
        return this;
    }

    public PageMarginsBuilder withLeft(Optional<Integer> value) {
        this.left = value;
        return this;
    }

    public PageMarginsBuilder withHeader(Optional<Integer> value) {
        this.header = value;
        return this;
    }

    public PageMarginsBuilder withFooter(Optional<Integer> value) {
        this.footer = value;
        return this;
    }

    public PageMarginsBuilder withGutter(Optional<Integer> value) {
        this.gutter = value;
        return this;
    }

    public PageMargins build() {
        return new PageMargins(
            top,
            right,
            bottom,
            left,
            header,
            footer,
            gutter
        );
    }
}
