// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record PageContent(
    @JsonProperty("page_number") long pageNumber,
    String content,
    List<String> tables,
    List<ExtractedImage> images,
    Optional<PageHierarchy> hierarchy,
    @JsonProperty("is_blank") Optional<Boolean> isBlank
) {
}
