// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record PdfExtractionMetadata(
    Optional<String> title,
    Optional<String> subject,
    Optional<List<String>> authors,
    Optional<List<String>> keywords,
    @JsonProperty("created_at") Optional<String> createdAt,
    @JsonProperty("modified_at") Optional<String> modifiedAt,
    @JsonProperty("created_by") Optional<String> createdBy,
    @JsonProperty("pdf_specific") PdfMetadata pdfSpecific,
    @JsonProperty("page_structure") Optional<PageStructure> pageStructure
) {
}
