// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

public class PdfImageExtractor implements AutoCloseable {
    private final MemorySegment handle;

    PdfImageExtractor(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_PDF_IMAGE_EXTRACTOR_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free PdfImageExtractor: " + e.getMessage(), e);
            }
        }
    }
}
