// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

public record PoolMetrics(
    @JsonProperty("total_acquires") String totalAcquires,
    @JsonProperty("total_cache_hits") String totalCacheHits,
    @JsonProperty("peak_items_stored") String peakItemsStored,
    @JsonProperty("total_creations") String totalCreations
) {
    public static PoolMetricsBuilder builder() {
        return new PoolMetricsBuilder();
    }
}
