// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record Position(
    @JsonProperty("relative_from") String relativeFrom,
    Optional<Long> offset
) {
}
