// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * Native PPT extractor using OLE/CFB parsing.
 * 
 * This extractor handles PowerPoint 97-2003 binary (.ppt) files without
 * requiring LibreOffice, providing ~50x faster extraction.
 */
public class PptExtractor implements AutoCloseable {
    private final MemorySegment handle;

    PptExtractor(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_PPT_EXTRACTOR_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free PptExtractor: " + e.getMessage(), e);
            }
        }
    }
}
