// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum RelationshipKind {
    FootnoteReference("footnote_reference"),
    CitationReference("citation_reference"),
    InternalLink("internal_link"),
    Caption("caption"),
    Label("label"),
    TocEntry("toc_entry"),
    CrossReference("cross_reference");

    private final String value;

    RelationshipKind(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @JsonCreator
    public static RelationshipKind fromValue(String value) {
        for (RelationshipKind e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
