// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * Registry for document renderer plugins.
 * 
 * Manages renderers that convert [`InternalDocument`] to output format strings.
 * 
 * # Thread Safety
 * 
 * The registry is thread-safe and can be accessed concurrently from multiple threads.
 * 
 * # Example
 * 
 * ```rust,no_run
 * use kreuzberg::plugins::registry::RendererRegistry;
 * use std::sync::Arc;
 * 
 * let registry = RendererRegistry::new();
 * let available = registry.list();
 * // Built-in renderers: "markdown", "html", "djot", "plain"
 * ```
 */
public class RendererRegistry implements AutoCloseable {
    private final MemorySegment handle;

    RendererRegistry(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_RENDERER_REGISTRY_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free RendererRegistry: " + e.getMessage(), e);
            }
        }
    }
}
