// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;


public class ResolvedStyleBuilder {

    private String paragraphProperties = "";
    private RunProperties runProperties = null;

    public ResolvedStyleBuilder withParagraphProperties(String value) {
        this.paragraphProperties = value;
        return this;
    }

    public ResolvedStyleBuilder withRunProperties(RunProperties value) {
        this.runProperties = value;
        return this;
    }

    public ResolvedStyle build() {
        return new ResolvedStyle(
            paragraphProperties,
            runProperties
        );
    }
}
