// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.List;

public record Section(List<String> paragraphs) {
    public static SectionBuilder builder() {
        return new SectionBuilder();
    }
}
