// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record StructuredExtractionConfig(
    Object schema,
    @JsonProperty("schema_name") String schemaName,
    @JsonProperty("schema_description") Optional<String> schemaDescription,
    boolean strict,
    Optional<String> prompt,
    LlmConfig llm
) {
}
