// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;


public class StyleCatalogBuilder {

    private String styles = "";
    private String defaultParagraphProperties = "";
    private RunProperties defaultRunProperties = null;

    public StyleCatalogBuilder withStyles(String value) {
        this.styles = value;
        return this;
    }

    public StyleCatalogBuilder withDefaultParagraphProperties(String value) {
        this.defaultParagraphProperties = value;
        return this;
    }

    public StyleCatalogBuilder withDefaultRunProperties(RunProperties value) {
        this.defaultRunProperties = value;
        return this;
    }

    public StyleCatalog build() {
        return new StyleCatalog(
            styles,
            defaultParagraphProperties,
            defaultRunProperties
        );
    }
}
