// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record TableBorders(
    Optional<String> top,
    Optional<String> bottom,
    Optional<String> left,
    Optional<String> right,
    @JsonProperty("inside_h") Optional<String> insideH,
    @JsonProperty("inside_v") Optional<String> insideV
) {
    public static TableBordersBuilder builder() {
        return new TableBordersBuilder();
    }
}
