// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * Native Tesseract OCR backend.
 * 
 * This backend wraps the OcrProcessor and implements the OcrBackend trait,
 * allowing it to be used through the plugin system.
 * 
 * # Thread Safety
 * 
 * Uses Arc for shared ownership and is thread-safe (Send + Sync).
 */
public class TesseractBackend implements AutoCloseable {
    private final MemorySegment handle;

    TesseractBackend(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_TESSERACT_BACKEND_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free TesseractBackend: " + e.getMessage(), e);
            }
        }
    }
}
