// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.Optional;

public class TreeSitterProcessConfigBuilder {

    private boolean structure = false;
    private boolean imports = false;
    private boolean exports = false;
    private boolean comments = false;
    private boolean docstrings = false;
    private boolean symbols = false;
    private boolean diagnostics = false;
    private Optional<Long> chunkMaxSize = Optional.empty();
    private CodeContentMode contentMode = null;

    public TreeSitterProcessConfigBuilder withStructure(boolean value) {
        this.structure = value;
        return this;
    }

    public TreeSitterProcessConfigBuilder withImports(boolean value) {
        this.imports = value;
        return this;
    }

    public TreeSitterProcessConfigBuilder withExports(boolean value) {
        this.exports = value;
        return this;
    }

    public TreeSitterProcessConfigBuilder withComments(boolean value) {
        this.comments = value;
        return this;
    }

    public TreeSitterProcessConfigBuilder withDocstrings(boolean value) {
        this.docstrings = value;
        return this;
    }

    public TreeSitterProcessConfigBuilder withSymbols(boolean value) {
        this.symbols = value;
        return this;
    }

    public TreeSitterProcessConfigBuilder withDiagnostics(boolean value) {
        this.diagnostics = value;
        return this;
    }

    public TreeSitterProcessConfigBuilder withChunkMaxSize(Optional<Long> value) {
        this.chunkMaxSize = value;
        return this;
    }

    public TreeSitterProcessConfigBuilder withContentMode(CodeContentMode value) {
        this.contentMode = value;
        return this;
    }

    public TreeSitterProcessConfig build() {
        return new TreeSitterProcessConfig(
            structure,
            imports,
            exports,
            comments,
            docstrings,
            symbols,
            diagnostics,
            chunkMaxSize,
            contentMode
        );
    }
}
