// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

public class UnsupportedFormatException extends KreuzbergErrorException {
    public UnsupportedFormatException(String message) {
        super(message);
    }

    public UnsupportedFormatException(String message, Throwable cause) {
        super(message, cause);
    }
}
