// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum UriKind {
    Hyperlink("hyperlink"),
    Image("image"),
    Anchor("anchor"),
    Citation("citation"),
    Reference("reference"),
    Email("email");

    private final String value;

    UriKind(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @JsonCreator
    public static UriKind fromValue(String value) {
        for (UriKind e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
