// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

public class ValidationException extends KreuzbergErrorException {
    public ValidationException(String message) {
        super(message);
    }

    public ValidationException(String message, Throwable cause) {
        super(message, cause);
    }
}
