// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * XML extractor.
 * 
 * Extracts text content from XML files, preserving element structure information.
 */
public class XmlExtractor implements AutoCloseable {
    private final MemorySegment handle;

    XmlExtractor(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_XML_EXTRACTOR_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free XmlExtractor: " + e.getMessage(), e);
            }
        }
    }
}
