// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

public record XmlMetadata(
    @JsonProperty("element_count") long elementCount,
    @JsonProperty("unique_elements") List<String> uniqueElements
) {
}
