# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: cache_ops

test_that("generate_cache_key_complex: Complex cache key", {
  result <- generate_cache_key(parts = c("hash_abc", "config_v2", "markdown"))
  expect_true(nchar(result$result) >= 5)
})

test_that("validate_cache_key_invalid: Invalid cache key", {
  expect_error(validate_cache_key(key = ""))
})
