# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: embed_extra

test_that("embed_normalize_unit: Normalize unit vector", {
  result <- normalize(data = c(1.0, 0.0, 0.0))
})

test_that("embed_normalize_zero: Normalize zero vector", {
  result <- normalize(data = c(0.0, 0.0, 0.0))
})
