# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f777cdce1378425a16834511b6893bca9245f4721025c06ca4744a9b0d84626e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: uri

test_that("classify_uri_anchor: Classify fragment URI", {
  result <- classify_uri(url = "#section-header")
})

test_that("classify_uri_email: Classify mailto URI", {
  result <- classify_uri(url = "mailto:user@example.com")
})

test_that("classify_uri_https: Classify HTTPS URL", {
  result <- classify_uri(url = "https://example.com/page")
})
