# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4f2c97b414fe5cda6dbc8e313c5b73fafe49e8bde0786988b766937fc8cfcd62
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: parsing

test_that("parse_json: Parse JSON document format", {
  result <- extract_file_sync(path = "json/simple.json")
  expect_true(nchar(result$content) >= 5)
})

test_that("parse_toml: Parse TOML document format", {
  result <- extract_file_sync(path = "data_formats/cargo.toml")
  expect_true(nchar(result$content) >= 5)
})

test_that("parse_xml: Parse XML document format", {
  result <- extract_file_sync(path = "xml/simple_note.xml")
  expect_true(nchar(result$content) >= 5)
})

test_that("parse_yaml: Parse YAML document format", {
  result <- extract_file_sync(path = "test_fixtures/config.yaml")
  expect_true(nchar(result$content) >= 5)
})
