# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: table_ops

test_that("excel_to_markdown_basic: Excel bytes to markdown (empty error)", {
  expect_error(excel_to_markdown(bytes = ""))
})

test_that("excel_to_text_basic: Excel bytes to text (empty error)", {
  expect_error(excel_to_text(bytes = ""))
})
