# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3afaa025717db9c50e815b63bf146831dbc14db8dd6f3694d6f89ffc508b6c47
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: embed_extra

test_that("embed_normalize_unit: Normalize unit vector", {
  result <- normalize(data = c(1.0, 0.0, 0.0))
})

test_that("embed_normalize_zero: Normalize zero vector", {
  result <- normalize(data = c(0.0, 0.0, 0.0))
})
