# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b931427cc08162251a406e8bc60b48f89d9b9d826fc4d4a43c208d79e6408466
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: table

test_that("table_csv_extraction: CSV file extraction produces content", {
  result <- extract_file_sync(path = "csv/stanley_cups.csv")
  expect_true(nchar(result$content) >= 10)
})

test_that("table_html_extraction: HTML table extraction produces markdown format", {
  result <- extract_file_sync(path = "html/simple_table.html", config = list("output_format" = "markdown"))
  expect_true(any(sapply(c("|"), function(v) grepl(v, result$content, fixed = TRUE))))
})

test_that("table_xlsx_markdown: XLSX extraction produces markdown table format", {
  result <- extract_file_sync(path = "xlsx/stanley_cups.xlsx", config = list("output_format" = "markdown"))
  expect_true(any(sapply(c("|", "---"), function(v) grepl(v, result$content, fixed = TRUE))))
})
