# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0e6af8bd4ee2b36325bad3b012a54c0565bf19af172d4b46171d84d345895ca4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: xml

test_that("xml_plant_catalog: XML plant catalog to validate streaming XML extraction.", {
  result <- extract_file(path = "xml/plant_catalog.xml")
  expect_equal(trimws(result$mime_type), "application/xml")
  expect_true(nchar(result$content) >= 100)
})
