# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ba55501947b9b76573e8a3f8095ad4f3a0de5eb4e73cf66661879ad3e5e05f82
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: mime_utilities

test_that("mime_detect_bytes: Detect MIME type from file bytes", {
  result <- extract_file()
  expect_true(grepl("pdf", result$result, fixed = TRUE))
})

test_that("mime_detect_image: Detect MIME type from PNG image bytes", {
  result <- extract_file()
  expect_true(grepl("png", result$result, fixed = TRUE))
})

test_that("mime_detect_path: Detect MIME type from file path", {
  result <- extract_file()
  expect_true(grepl("text", result$result, fixed = TRUE))
})

test_that("mime_get_extensions: Get file extensions for a MIME type", {
  result <- get_extensions_for_mime()
  expect_true(grepl("pdf", result$result, fixed = TRUE))
})

test_that("mime_list_supported: List all supported MIME types and file extensions", {
  result <- list_supported_formats(NULL)
})
