# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:86bb6673c83a7430210c5b8e352555d210dc2c61a900e5ddc56ef7f1e0a08175
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: validator_management

test_that("validators_clear: Clear all validators and verify list is empty", {
  result <- extract_file()
  expect_equal(result$result, "")
})

test_that("validators_list: List all registered validators", {
  result <- list_validators(NULL)
})
