# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: text_processing

test_that("text_clean_extracted: Extract and clean text content from document", {
  result <- extract_file_sync(path = "json/simple.json")
  expect_true(nchar(result$content) >= 5)
})

test_that("text_normalize_whitespace: Extract text with whitespace normalization (no consecutive spaces)", {
  result <- extract_file_sync(path = "pdf/fake_memo.pdf")
  expect_false(grepl("  ", result$content, fixed = TRUE))
})
