# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: embed_extra

test_that("embed_normalize_unit: Normalize unit vector", {
  result <- normalize(data = c(1.0, 0.0, 0.0))
})

test_that("embed_normalize_zero: Normalize zero vector", {
  result <- normalize(data = c(0.0, 0.0, 0.0))
})
