// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:32c4fc655145bc576d5c563c76eea1de9b8c5c14a3ec0dd2810299b0e37c0a6b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from 'vitest';
import { extractFile, extract_file_sync, type ExtractionConfig } from 'kreuzberg';

describe('document', () => {
  it('doc_metadata_docx: Extract DOCX metadata', () => {
    const result = extract_file_sync("vendored/markitdown/test.docx");
    expect(result.metadata.length).toBeGreaterThan(0);
  });

  it('doc_metadata_pdf: Extract PDF metadata', () => {
    const result = extract_file_sync("pdf/fake_memo.pdf");
    expect(result.metadata.length).toBeGreaterThan(0);
  });

  it('doc_structure_docx: Extract DOCX document structure with include_document_structure config', () => {
    const result = extract_file_sync("vendored/markitdown/test.docx", { include_document_structure: true } as ExtractionConfig);
    expect(result.documentStructure.length).toBeGreaterThan(0);
  });

  it('doc_structure_html: Extract HTML document structure with include_document_structure config', () => {
    const result = extract_file_sync("html/html.html", { include_document_structure: true } as ExtractionConfig);
    expect(result.documentStructure.length).toBeGreaterThan(0);
  });

  it('doc_structure_pdf: Extract PDF document structure with include_document_structure config', () => {
    const result = extract_file_sync("pdf/fake_memo.pdf", { include_document_structure: true } as ExtractionConfig);
    expect(result.documentStructure.length).toBeGreaterThan(0);
  });
});
