// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f4877982a683f17b969a783cf5ceda13ab43ed605f208b551cea869652ea1b14
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from 'vitest';
import { extractFile, normalize } from 'kreuzberg';

describe('embed_extra', () => {
  it('embed_normalize_unit: Normalize unit vector', () => {
    normalize([1.0, 0.0, 0.0] as ExtractionConfig);
  });

  it('embed_normalize_zero: Normalize zero vector', () => {
    normalize([0.0, 0.0, 0.0] as ExtractionConfig);
  });
});
