// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:20138394f593e4f46424298c39b798df029c4a54f3a861bfdfca322c07fba7a7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from 'vitest';
import { extractFile, normalize } from 'kreuzberg';

describe('embed_extra', () => {
  it('embed_normalize_unit: Normalize unit vector', () => {
    normalize([1.0, 0.0, 0.0] as ExtractionConfig);
  });

  it('embed_normalize_zero: Normalize zero vector', () => {
    normalize([0.0, 0.0, 0.0] as ExtractionConfig);
  });
});
