// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fc0c250b6f1e20f39b7c3d077b0ea75e3d0ea8f77a9b8b2fed3667b5529ef1e4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from 'vitest';
import { extractFile, extract_file_sync, type ExtractionConfig } from 'kreuzberg';

describe('embeddings', () => {
  it('embedding_disabled: Tests chunking without embeddings - chunks should not have embedding vectors', () => {
    const result = extract_file_sync("pdf/fake_memo.pdf", { chunking: { max_chars: 500, max_overlap: 50 } } as ExtractionConfig);
    expect(result.mimeType.trim()).toBe("application/pdf");
    expect(result.content.length).toBeGreaterThanOrEqual(10);
    expect(result.chunks.length).toBeGreaterThanOrEqual(1);
    expect(result.chunksHaveContent).toBe(true);
  });
});
