// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from 'vitest';
import { extractFile, list_document_extractors, list_ocr_backends, list_post_processors, list_validators } from 'kreuzberg';

describe('registry', () => {
  it('list_document_extractors: List document extractors', () => {
    list_document_extractors({  });
  });

  it('list_ocr_backends: List OCR backends', () => {
    list_ocr_backends({  });
  });

  it('list_post_processors: List post-processors', () => {
    list_post_processors({  });
  });

  it('list_validators: List validators', () => {
    list_validators({  });
  });
});
