// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8bc520cf060bb2786ffbf9c4c4066e08e0d90a9a5e497c61f06e1636525455df
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from 'vitest';
import { extractFile, extract_file_sync, type ExtractionConfig } from 'kreuzberg';

describe('table', () => {
  it('table_csv_extraction: CSV file extraction produces content', () => {
    const result = extract_file_sync("csv/stanley_cups.csv");
    expect(result.content.length).toBeGreaterThanOrEqual(10);
  });

  it('table_html_extraction: HTML table extraction produces markdown format', () => {
    const result = extract_file_sync("html/simple_table.html", { output_format: "markdown" } as ExtractionConfig);
    expect(["|"].some((v) => result.content.includes(v))).toBe(true);
  });

  it('table_xlsx_markdown: XLSX extraction produces markdown table format', () => {
    const result = extract_file_sync("xlsx/stanley_cups.xlsx", { output_format: "markdown" } as ExtractionConfig);
    expect(["|", "---"].some((v) => result.content.includes(v))).toBe(true);
  });
});
