// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:35713c11fe660e0f3225c457608f3b8f85d85a73d0ed90e3b652b92208de3d43
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from 'vitest';
import { extractFile, classify_uri } from 'kreuzberg';

describe('uri', () => {
  it('classify_uri_anchor: Classify fragment URI', () => {
    classify_uri("#section-header");
  });

  it('classify_uri_email: Classify mailto URI', () => {
    classify_uri("mailto:user@example.com");
  });

  it('classify_uri_https: Classify HTTPS URL', () => {
    classify_uri("https://example.com/page");
  });
});
