// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e489c116ae860433aa86bf79aa16e681f3f6c1f73c22845cfb1ea07236f690ff
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from 'vitest';
import { extractFile } from 'kreuzberg';

describe('xml', () => {
  it('xml_plant_catalog: XML plant catalog to validate streaming XML extraction.', async () => {
    const result = await extractFile("xml/plant_catalog.xml");
    expect(result.mimeType.trim()).toBe("application/xml");
    expect(result.content.length).toBeGreaterThanOrEqual(100);
  });
});
