# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2ee7f23c899fc3158c76969f5a2a0638cd35ace20c7e1cb8412a777b08d352a8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: uri."""

from kreuzberg import classify_uri


def test_classify_uri_anchor() -> None:
    """Classify fragment URI."""
    url = "#section-header"
    _ = classify_uri(url=url)


def test_classify_uri_email() -> None:
    """Classify mailto URI."""
    url = "mailto:user@example.com"
    _ = classify_uri(url=url)


def test_classify_uri_https() -> None:
    """Classify HTTPS URL."""
    url = "https://example.com/page"
    _ = classify_uri(url=url)
