# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: configuration."""

import pytest
from kreuzberg import extract_file


@pytest.mark.asyncio
async def test_config_discover() -> None:
    """Discover configuration from current or parent directories."""
    path = ""
    result = await extract_file(path=path)
    assert result.result.chunking  # noqa: S101
    assert result.result.chunking.max_chars == 50  # noqa: S101


@pytest.mark.asyncio
async def test_config_from_file() -> None:
    """Load configuration from a TOML file."""
    path = ""
    result = await extract_file(path=path)
    assert result.result.chunking  # noqa: S101
    assert result.result.chunking.max_chars == 100  # noqa: S101
    assert result.result.chunking.max_overlap == 20  # noqa: S101
    assert result.result.language_detection  # noqa: S101
    assert result.result.language_detection.enabled is False  # noqa: S101
