# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: document_extractor_management."""

import pytest
from kreuzberg import extract_file, list_document_extractors


@pytest.mark.asyncio
async def test_extractors_clear() -> None:
    """Clear all document extractors and verify list is empty."""
    path = ""
    result = await extract_file(path=path)
    assert not result.result  # noqa: S101


def test_extractors_list() -> None:
    """List all registered document extractors."""
    _ = list_document_extractors()


@pytest.mark.asyncio
async def test_extractors_unregister() -> None:
    """Unregister nonexistent document extractor gracefully."""
    path = ""
    _ = await extract_file(path=path)
