# This file is auto-generated by alef. DO NOT EDIT.
"""E2e tests for category: document_extractor_management."""
import pytest

from kreuzberg import extract_file


@pytest.mark.asyncio
async def test_extractors_clear() -> None:
    """Clear all document extractors and verify list is empty."""
    path = ""
    result = await extract_file(path=path)
    assert not result.result

@pytest.mark.asyncio
async def test_extractors_list() -> None:
    """List all registered document extractors."""
    path = ""
    _ = await extract_file(path=path)

@pytest.mark.asyncio
async def test_extractors_unregister() -> None:
    """Unregister nonexistent document extractor gracefully."""
    path = ""
    _ = await extract_file(path=path)

