# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6064ff0940e570849a2d8be80c054dff71793a4540381ba0e4afdf36e2ca06d4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: text_processing."""

from kreuzberg import extract_file_sync


def test_text_clean_extracted() -> None:
    """Extract and clean text content from document."""
    path = "json/simple.json"
    result = extract_file_sync(path=path)
    assert len(result.content) >= 5  # noqa: S101


def test_text_normalize_whitespace() -> None:
    """Extract text with whitespace normalization (no consecutive spaces)."""
    path = "pdf/fake_memo.pdf"
    result = extract_file_sync(path=path)
    assert result.content is None or "  " not in result.content  # noqa: S101
