# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d6979c9998c31fcab954b1e2d0db5bf237de822871b337c4ac39cae96b302ca5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: parsing."""

import pytest  # noqa: F401
from kreuzberg import extract_file_sync


def test_parse_json() -> None:
    """Parse JSON document format."""
    path = "json/simple.json"
    result = extract_file_sync(path=path)
    assert len(result.content) >= 5  # noqa: S101


def test_parse_toml() -> None:
    """Parse TOML document format."""
    path = "data_formats/cargo.toml"
    result = extract_file_sync(path=path)
    assert len(result.content) >= 5  # noqa: S101


def test_parse_xml() -> None:
    """Parse XML document format."""
    path = "xml/simple_note.xml"
    result = extract_file_sync(path=path)
    assert len(result.content) >= 5  # noqa: S101


def test_parse_yaml() -> None:
    """Parse YAML document format."""
    path = "test_fixtures/config.yaml"
    result = extract_file_sync(path=path)
    assert len(result.content) >= 5  # noqa: S101
