# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1d30b0ce82c6bf73a636d56eaa95a497a3ad0ae3a3c951bf6b4af68f971d9234
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: registry_operations."""

import pytest  # noqa: F401
from kreuzberg import get_extensions_for_mime, list_supported_formats


def test_extensions_docx() -> None:
    """Get file extensions for DOCX MIME type."""
    mime_type = ""
    _ = get_extensions_for_mime(mime_type=mime_type)


def test_extensions_html() -> None:
    """Get file extensions for HTML MIME type."""
    mime_type = ""
    _ = get_extensions_for_mime(mime_type=mime_type)


def test_extensions_pdf() -> None:
    """Get file extensions for PDF MIME type."""
    mime_type = ""
    result = get_extensions_for_mime(mime_type=mime_type)
    assert "pdf" in result.result  # noqa: S101


def test_list_formats_all() -> None:
    """List all supported formats and their extensions."""
    _ = list_supported_formats()
