// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:94a6e233ac49307346290e9480a980efd312aebe1b736fd5e88f04653e162dc7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;

/** E2e tests for category: batch. */
class BatchTest {
    @Test
    void testBatchBytesInvalidMime() throws Exception {
        // batch_extract_bytes_sync invalid MIME
        var result = Kreuzberg.batchExtractBytesSync(items);
    }

    @Test
    void testBatchFileAsyncBasic() throws Exception {
        // Extract text from multiple files asynchronously
        var result = Kreuzberg.batchExtractFile(paths);
    }

    @Test
    void testBatchFileAsyncNotFound() throws Exception {
        // batch_extract_file async nonexistent
        var result = Kreuzberg.batchExtractFile(paths);
    }

    @Test
    void testBatchFileNotFound() throws Exception {
        // batch_extract_file_sync nonexistent
        var result = Kreuzberg.batchExtractFileSync(paths);
    }

    @Test
    void testBatchFilePartial() throws Exception {
        // batch_extract_file_sync mixed
        var result = Kreuzberg.batchExtractFileSync(paths);
    }

    @Test
    void testBatchFileSyncBasic() throws Exception {
        // Extract text from multiple files synchronously
        var result = Kreuzberg.batchExtractFileSync(paths);
    }

}
