// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:91b9e412b6ee67c764a994463c7ddc7c244fd7506e53ab5c18e6378428d43c59
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;

/** E2e tests for category: cache_ops. */
class CacheOpsTest {
    @Test
    void testGenerateCacheKeyComplex() throws Exception {
        // Complex cache key
        var result = Kreuzberg.generateCacheKey(parts);
        assertTrue(result.result().length() >= 5, "expected length >= 5");
    }

    @Test
    void testValidateCacheKeyInvalid() throws Exception {
        // Invalid cache key
        assertThrows(Exception.class, () -> Kreuzberg.validateCacheKey(""));
    }

}
