// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b2205b2385b34526ca298a2793bf5d1b3b681685db6bc35b9d06d6cb570968c2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;

/** E2e tests for category: email. */
class EmailTest {
    @Test
    void testEmailEmlHtmlBody() throws Exception {
        // EML with HTML body content.
        var result = Kreuzberg.extractFile("email/html_only.eml");
        assertEquals("message/rfc822", result.mimeType().trim());
        assertTrue(result.content().length() >= 10, "expected length >= 10");
    }

    @Test
    void testEmailEmlMultipart() throws Exception {
        // EML with multipart MIME content.
        var result = Kreuzberg.extractFile("email/html_email_multipart.eml");
        assertEquals("message/rfc822", result.mimeType().trim());
        assertTrue(result.content().length() >= 10, "expected length >= 10");
    }

    @Test
    void testEmailEmlUtf16() throws Exception {
        // UTF-16 encoded EML file with BOM.
        var result = Kreuzberg.extractFile("vendored/unstructured/eml/fake-email-utf-16.eml");
        assertEquals("message/rfc822", result.mimeType().trim());
        assertTrue(result.content().length() >= 50, "expected length >= 50");
        assertTrue(result.content().contains("Test Email") || result.content().contains("Roses are red"), "expected to contain at least one of the specified values");
    }

    @Test
    void testEmailMsgBasic() throws Exception {
        // Outlook MSG file extraction.
        var result = Kreuzberg.extractFile("email/fake_email.msg");
        assertEquals("application/vnd.ms-outlook", result.mimeType().trim());
        assertTrue(result.content().length() >= 10, "expected length >= 10");
    }

    @Test
    void testEmailPstEmpty() throws Exception {
        // Empty Outlook PST archive with no messages.
        var result = Kreuzberg.extractFile("email/empty.pst");
        assertEquals("application/vnd.ms-outlook-pst", result.mimeType().trim());
    }

    @Test
    void testEmailSampleEml() throws Exception {
        // Sample EML email file to verify email parsing.
        var result = Kreuzberg.extractFile("email/sample_email.eml");
        assertEquals("message/rfc822", result.mimeType().trim());
        assertTrue(result.content().length() >= 20, "expected length >= 20");
    }

}
