// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4935d7c369696d98a329e844d6e9b4ec9787eeab9cb42a465920e93f922f1c4a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;

/** E2e tests for category: embed_extra. */
class EmbedExtraTest {
    @Test
    void testEmbedNormalizeUnit() throws Exception {
        // Normalize unit vector
        var result = Kreuzberg.normalize(data);
    }

    @Test
    void testEmbedNormalizeZero() throws Exception {
        // Normalize zero vector
        var result = Kreuzberg.normalize(data);
    }

}
