// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4436fca816f6c02fe9bd42b5743207be6c572f17d38035177602eb9fd9568b75
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;

/** E2e tests for category: extraction. */
class ExtractionTest {
    @Test
    void testExtractDocBasic() throws Exception {
        // Extract text from a DOC file containing unit test lists
        var result = Kreuzberg.extractDocText("doc/unit_test_lists.doc".getBytes());
        assertTrue(result.content().length() >= 10, "expected length >= 10");
    }

    @Test
    void testExtractEmailBasic() throws Exception {
        // Extract content from an email file in EML format
        var result = Kreuzberg.extractEmailContent("email/html_email_multipart.eml".getBytes());
    }

    @Test
    void testExtractPdfBasic() throws Exception {
        // Extract text from a basic PDF document containing memo content
        var result = Kreuzberg.extractTextFromPdf("pdf/fake_memo.pdf".getBytes());
        assertTrue(result.content().length() >= 50, "expected length >= 50");
    }

    @Test
    void testExtractPdfCode() throws Exception {
        // Extract text from PDF containing code snippets and formulas
        var result = Kreuzberg.extractTextFromPdf("pdf/code_and_formula.pdf".getBytes());
        assertTrue(result.content().length() >= 20, "expected length >= 20");
    }

    @Test
    void testExtractPptxBasic() throws Exception {
        // Extract text from a PowerPoint presentation file
        var result = Kreuzberg.extractPptxFromBytes("pptx/powerpoint_sample.pptx".getBytes());
    }

}
