// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import dev.kreuzberg.ExtractionConfig;

/** E2e tests for category: image. */
class ImageTest {

    private static final ObjectMapper MAPPER = new ObjectMapper().registerModule(new Jdk8Module());
    @Test
    void testImageMetadataOnly() throws Exception {
        // JPEG image to validate metadata extraction without OCR.
        var result = Kreuzberg.extractFile("images/example.jpg", config);
        assertEquals("image/jpeg", result.mimeType().trim());
        assertTrue(result.content().orElse("").length() <= 200, "expected length <= 200");
    }

    @Test
    void testImageSvgBasic() throws Exception {
        // SVG image extraction.
        var result = Kreuzberg.extractFile("xml/simple_svg.svg");
        assertEquals("image/svg+xml", result.mimeType().trim());
        assertTrue(result.content().orElse("").length() >= 5, "expected length >= 5");
    }

}
