// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:516f203a96288b05dcbbc305c851cbd6822d87584f5a9c03adca7fca4aeb4137
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import dev.kreuzberg.ExtractionConfig;

/** E2e tests for category: language. */
class LanguageTest {

    private static final ObjectMapper MAPPER = new ObjectMapper().registerModule(new Jdk8Module());
    @Test
    void testLangDetectConfig() throws Exception {
        // Language detection with specific language config
        var result = Kreuzberg.extractFileSync("semantic/mixed_topics.txt", config);
    }

    @Test
    void testLangDetectEnglish() throws Exception {
        // Language detection works on English text
        var result = Kreuzberg.extractFileSync("semantic/mixed_topics.txt", config);
    }

}
