// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0861752dd92298c12bc49765668527b5f17fe74511675ed8959c54c1eca2d262
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;

/** E2e tests for category: post_processor_management. */
class PostProcessorManagementTest {
    @Test
    void testPostProcessorsClear() throws Exception {
        // Clear all post-processors and verify list is empty
        var result = Kreuzberg.extractFile("");
    }

    @Test
    void testPostProcessorsList() throws Exception {
        // List all registered post-processors
        var result = Kreuzberg.listPostProcessors();
    }

}
