// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7a1b2366117971281b7e0a79300b923d404cf7a78dc9ea4e28a7362126ec8b65
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;

/** E2e tests for category: registry_operations. */
class RegistryOperationsTest {
    @Test
    void testExtensionsDocx() throws Exception {
        // Get file extensions for DOCX MIME type
        var result = Kreuzberg.getExtensionsForMime("");
    }

    @Test
    void testExtensionsHtml() throws Exception {
        // Get file extensions for HTML MIME type
        var result = Kreuzberg.getExtensionsForMime("");
    }

    @Test
    void testExtensionsPdf() throws Exception {
        // Get file extensions for PDF MIME type
        var result = Kreuzberg.getExtensionsForMime("");
        assertTrue(result.result().contains("pdf"), "expected to contain: " + "pdf");
    }

    @Test
    void testListFormatsAll() throws Exception {
        // List all supported formats and their extensions
        var result = Kreuzberg.listSupportedFormats();
    }

}
