// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bf68bfd847ccd2d107ec3586eb0c0c88d7c2ad49eb88f718e56da509660ef05a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import dev.kreuzberg.ExtractionConfig;

/** E2e tests for category: table. */
class TableTest {

    private static final ObjectMapper MAPPER = new ObjectMapper().registerModule(new Jdk8Module());
    @Test
    void testTableCsvExtraction() throws Exception {
        // CSV file extraction produces content
        var result = Kreuzberg.extractFileSync("csv/stanley_cups.csv");
        assertTrue(result.content().length() >= 10, "expected length >= 10");
    }

    @Test
    void testTableHtmlExtraction() throws Exception {
        // HTML table extraction produces markdown format
        var result = Kreuzberg.extractFileSync("html/simple_table.html", config);
        assertTrue(result.content().contains("|"), "expected to contain at least one of the specified values");
    }

    @Test
    void testTableXlsxMarkdown() throws Exception {
        // XLSX extraction produces markdown table format
        var result = Kreuzberg.extractFileSync("xlsx/stanley_cups.xlsx", config);
        assertTrue(result.content().contains("|") || result.content().contains("---"), "expected to contain at least one of the specified values");
    }

}
