// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;

/** E2e tests for category: uri. */
class UriTest {
    @Test
    void testClassifyUriAnchor() throws Exception {
        // Classify fragment URI
        var result = Kreuzberg.classifyUri("#section-header");
    }

    @Test
    void testClassifyUriEmail() throws Exception {
        // Classify mailto URI
        var result = Kreuzberg.classifyUri("mailto:user@example.com");
    }

    @Test
    void testClassifyUriHttps() throws Exception {
        // Classify HTTPS URL
        var result = Kreuzberg.classifyUri("https://example.com/page");
    }

}
