// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;

/** E2e tests for category: xml. */
class XmlTest {
    @Test
    void testXmlPlantCatalog() throws Exception {
        // XML plant catalog to validate streaming XML extraction.
        var result = Kreuzberg.extractFile("xml/plant_catalog.xml");
        assertEquals("application/xml", result.mimeType().trim());
        assertTrue(result.content().orElse("").length() >= 100, "expected length >= 100");
    }

}
