# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:acdaad05fd8f98be691338edaffe7e2f1edc2867cf022c28f2dd9790b5247388
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Kreuzberg
  VERSION = '4.9.5'
end
