# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fb2c6b762fd9f231320d18bc6be91f1a73583d82633c3ce8ccfae1d01e925da4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Kreuzberg
  VERSION = '4.10.0.pre.rc.14'
end
