# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:90031298adc504f00e0e44a5a6e4c9180a5dec8b76058533b1e88aff75991420
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Kreuzberg
  VERSION = '4.10.0.pre.rc.9'
end
