<?php
// This file is auto-generated by alef. DO NOT EDIT.
// Type stubs for the native PHP extension — declares classes
// provided at runtime by the compiled Rust extension (.so/.dll).
// Include this in phpstan.neon scanFiles for static analysis.

declare(strict_types=1);

namespace Kreuzberg {

class KreuzbergException extends \RuntimeException
{
    public function getErrorCode(): int { }
}

/**
 * A supported document format entry.
 *
 * Represents a file extension and its corresponding MIME type that Kreuzberg can process.
 */
class SupportedFormat
{
    public string $extension;
    public string $mime_type;

    public function __construct(
        string $extension,
        string $mime_type
    ) { }

    public function getExtension(): string { }
    public function getMimeType(): string { }
}

/**
 * Token usage and cost data for a single LLM call made during extraction.
 *
 * Populated when VLM OCR, structured extraction, or LLM-based embeddings
 * are used. Multiple entries may be present when multiple LLM calls occur
 * within one extraction (e.g. VLM OCR + structured extraction).
 */
class LlmUsage
{
    public string $model;
    public string $source;
    public ?int $input_tokens;
    public ?int $output_tokens;
    public ?int $total_tokens;
    public ?float $estimated_cost;
    public ?string $finish_reason;

    public function __construct(
        string $model,
        string $source,
        ?int $input_tokens = null,
        ?int $output_tokens = null,
        ?int $total_tokens = null,
        ?float $estimated_cost = null,
        ?string $finish_reason = null
    ) { }

    public function getModel(): string { }
    public function getSource(): string { }
    public function getInputTokens(): ?int { }
    public function getOutputTokens(): ?int { }
    public function getTotalTokens(): ?int { }
    public function getEstimatedCost(): ?float { }
    public function getFinishReason(): ?string { }
}

class KreuzbergApi
{
    public static function isValidFormatField(string $field): bool { }
    public static function detectMimeType(string $path, bool $check_exists): string { }
    public static function validateMimeType(string $mime_type): string { }
    public static function detectMimeTypeFromBytes(string $content): string { }
    public static function getExtensionsForMime(string $mime_type): array { }
    public static function listSupportedFormats(): array { }
}

} // end namespace
