// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a3deaa6a8ebe456a52e6ff040471f383b01988208acc996b83438ad2ac931ee7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Optional;

/**
 * Archive (ZIP/TAR/7Z) metadata.
 *
 * <p>Extracted from compressed archive files containing file lists and size information.
 */
public record ArchiveMetadata(
    /** Archive format ("ZIP", "TAR", "7Z", etc.) */
    String format,
    /** Total number of files in the archive */
    @JsonProperty("file_count") long fileCount,
    /** List of file paths within the archive */
    @JsonProperty("file_list") List<String> fileList,
    /** Total uncompressed size in bytes */
    @JsonProperty("total_size") long totalSize,
    /** Compressed size in bytes (if available) */
    @JsonProperty("compressed_size") Optional<Long> compressedSize) {
  public static ArchiveMetadataBuilder builder() {
    return new ArchiveMetadataBuilder();
  }
}
