// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A single file extracted from an archive.
 *
 * When archives (ZIP, TAR, 7Z, GZIP) are extracted with recursive extraction
 * enabled, each processable file produces its own full {@code ExtractionResult}.
 */
public record ArchiveEntry(
    /** Archive-relative file path (e.g. "folder/document.pdf"). */
    String path,
    /** Detected MIME type of the file. */
    @JsonProperty("mime_type") String mimeType,
    /** Full extraction result for this file. */
    ExtractionResult result
) {
}
