// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:45ccc9edcd5110fb19e1eb352722ff0b777f650c32198a119d0b49b1f651b114
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * BibTeX bibliography metadata.
 */
public class BibtexMetadataBuilder {

    private long entryCount = 0;
    private List<String> citationKeys = List.of();
    private List<String> authors = List.of();
    private Optional<YearRange> yearRange = Optional.empty();
    private Optional<Map<String, Long>> entryTypes = Optional.empty();

    /** Sets the entryCount field. */
    public BibtexMetadataBuilder withEntryCount(final long value) {
        this.entryCount = value;
        return this;
    }

    /** Sets the citationKeys field. */
    public BibtexMetadataBuilder withCitationKeys(final List<String> value) {
        this.citationKeys = value;
        return this;
    }

    /** Sets the authors field. */
    public BibtexMetadataBuilder withAuthors(final List<String> value) {
        this.authors = value;
        return this;
    }

    /** Sets the yearRange field. */
    public BibtexMetadataBuilder withYearRange(final Optional<YearRange> value) {
        this.yearRange = value;
        return this;
    }

    /** Sets the entryTypes field. */
    public BibtexMetadataBuilder withEntryTypes(final Optional<Map<String, Long>> value) {
        this.entryTypes = value;
        return this;
    }

    /** Builds the BibtexMetadata instance. */
    public BibtexMetadata build() {
        return new BibtexMetadata(
            entryCount,
            citationKeys,
            authors,
            yearRange,
            entryTypes
        );
    }
}
