// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8e67da4b549f1a4cf2d22137a6dd7ccd0670ca87d8ac87e322ad160dbe0f72bc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Request parameters for cache warm (model download).
 */
public record CacheWarmParams(
    /** Download all embedding model presets */
    @JsonProperty("all_embeddings") boolean allEmbeddings,
    /** Specific embedding preset name to download (e.g. "balanced", "speed", "quality") */
    @JsonProperty("embedding_model") Optional<String> embeddingModel
) {
}
