// DO NOT EDIT - auto-generated by alef
// alef:hash:2d9a6b09f210d8b08b0ae7417404bdb37c8061b2381534d3f39fa15b07155631
package dev.kreuzberg;

public class CancelledException extends KreuzbergErrorException {
  /** Creates a new CancelledException with the given message. */
  public CancelledException(final String message) {
    super(message);
  }

  /** Creates a new CancelledException with the given message and cause. */
  public CancelledException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
