// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6f37a92b13f6b214deb485fb9efbc3077744c88f0305ad107f8db009f47c2c13
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Chunk request with text and configuration.
 */
public record ChunkRequest(
    /** Text to chunk (must not be empty) */
    String text,
    /** Optional chunking configuration */
    Optional<String> config,
    /** Chunker type (text, markdown, yaml, or semantic) */
    @JsonProperty("chunker_type") String chunkerType
) {
}
