// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6166ee6b16089f295bc97002566e605e150e179dc83154882b158c4b5386a909
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Result of a text chunking operation.
 *
 * <p>Contains the generated chunks and metadata about the chunking.
 */
public record ChunkingResult(List<Chunk> chunks, @JsonProperty("chunk_count") long chunkCount) {}
