// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:315f195c77088a10d0ac7de7f89f67bbe95dc93946025650fae23220d8e1f533
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CSV/TSV file metadata.
 */
public record CsvMetadata(
    @JsonProperty("row_count") long rowCount,
    @JsonProperty("column_count") long columnCount,
    Optional<String> delimiter,
    @JsonProperty("has_header") boolean hasHeader,
    @JsonProperty("column_types") Optional<List<String>> columnTypes
) {
    public static CsvMetadataBuilder builder() {
        return new CsvMetadataBuilder();
    }
}
