// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Optional;

/** CSV/TSV file metadata. */
public record CsvMetadata(
    @JsonProperty("row_count") long rowCount,
    @JsonProperty("column_count") long columnCount,
    Optional<String> delimiter,
    @JsonProperty("has_header") boolean hasHeader,
    @JsonProperty("column_types") Optional<List<String>> columnTypes) {
  public static CsvMetadataBuilder builder() {
    return new CsvMetadataBuilder();
  }
}
