// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:361d5235a8fa26ad17e38a6f1084d67a69c3e6cfe3fac7eeef77ac21bb05b123
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * dBASE field information.
 */
public record DbfFieldInfo(String name, @JsonProperty("field_type") String fieldType) {
}
