// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:249af8b47a4b623c2380a2424d586e05b93fb179bccc09cb0331d382aa00eeae
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** dBASE (DBF) file metadata. */
public record DbfMetadata(
    @JsonProperty("record_count") long recordCount,
    @JsonProperty("field_count") long fieldCount,
    List<DbfFieldInfo> fields) {
  public static DbfMetadataBuilder builder() {
    return new DbfMetadataBuilder();
  }
}
