// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3c760d93f821f874951df8e4ddc5c6dc1e89359e2e976dd3ecee21f19d1142be
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * MIME type detection response.
 */
public record DetectResponse(
    /** Detected MIME type */
    @JsonProperty("mime_type") String mimeType,
    /** Original filename (if provided) */
    Optional<String> filename
) {
}
