// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:34c0284776481b15ca6ddc5bd85104fb6253dfebc8b54cb5c30857876425505c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/** A detected structural boundary in the text. */
public record DetectedBoundary(
    /** Byte offset of the start of the line in the original text. */
    @JsonProperty("byte_offset") long byteOffset,
    /** Whether this boundary looks like a header/section title. */
    @JsonProperty("is_header") boolean isHeader) {}
