// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:595fc3c50e228bf40556713f4532ce977cd7f993e459a50f2d249ae2b1b536e1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;

/** Image element in Djot. */
public record DjotImage(
    /** Image source URL or path */
    String src,
    /** Alternative text */
    String alt,
    /** Optional title */
    Optional<String> title,
    /** Element attributes */
    Optional<String> attributes) {}
