// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;

/** Link element in Djot. */
public record DjotLink(
    /** Link URL */
    String url,
    /** Link text content */
    String text,
    /** Optional title */
    Optional<String> title,
    /** Element attributes */
    Optional<String> attributes) {}
