// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d7e9aa7e906b4321bad46b9a07eae8d7430502f38e6c00b48f76a6cc9f46b731
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

/**
 * OpenWebUI "Docling" engine response format.
 *
 * <p>Returned by {@code POST /v1/convert/file} for docling-serve compatibility.
 */
public record DoclingCompatResponse(String document, String status) {}
