// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ca3960ccb2678e0affec028484794e46b2c00fa231161a9af42a2c722a5c225b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;


/**
 * OpenWebUI "Docling" engine response format.
 *
 * Returned by {@code POST /v1/convert/file} for docling-serve compatibility.
 */
public record DoclingCompatResponse(String document, String status) {
}
