// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:17bbebf8dc803e34b1c108e1a6c7b5c37f467396374d8f4892ed3f83b43dc36d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

/** A resolved relationship between two nodes in the document tree. */
public record DocumentRelationship(int source, int target, RelationshipKind kind) {}
