// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

/** A resolved relationship between two nodes in the document tree. */
public record DocumentRelationship(int source, int target, RelationshipKind kind) {}
