// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;
import java.util.Optional;

/** Metadata for a semantic element. */
public record ElementMetadata(
    /** Page number (1-indexed) */
    @JsonProperty("page_number") Optional<Long> pageNumber,
    /** Source filename or document name */
    Optional<String> filename,
    /** Bounding box coordinates if available */
    Optional<String> coordinates,
    /** Position index in the element sequence */
    @JsonProperty("element_index") Optional<Long> elementIndex,
    /** Additional custom metadata */
    Map<String, String> additional) {}
