// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d04aefab62a1cc02c13e74569be9dc3aeff4edd5348719d9d718135cdf246519
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Map;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Metadata for a semantic element.
 */
public record ElementMetadata(
    /** Page number (1-indexed) */
    @JsonProperty("page_number") Optional<Long> pageNumber,
    /** Source filename or document name */
    Optional<String> filename,
    /** Bounding box coordinates if available */
    Optional<String> coordinates,
    /** Position index in the element sequence */
    @JsonProperty("element_index") Optional<Long> elementIndex,
    /** Additional custom metadata */
    Map<String, String> additional
) {
}
