// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c5d66fc27273027c6ddef177a4ce11e1d84b517e4a845e2a6c76d7a53fc9076f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Optional;

/**
 * Email metadata extracted from .eml and .msg files.
 *
 * <p>Includes sender/recipient information, message ID, and attachment list.
 */
public record EmailMetadata(
    /** Sender's email address */
    @JsonProperty("from_email") Optional<String> fromEmail,
    /** Sender's display name */
    @JsonProperty("from_name") Optional<String> fromName,
    /** Primary recipients */
    @JsonProperty("to_emails") List<String> toEmails,
    /** CC recipients */
    @JsonProperty("cc_emails") List<String> ccEmails,
    /** BCC recipients */
    @JsonProperty("bcc_emails") List<String> bccEmails,
    /** Message-ID header value */
    @JsonProperty("message_id") Optional<String> messageId,
    /** List of attachment filenames */
    List<String> attachments) {
  public static EmailMetadataBuilder builder() {
    return new EmailMetadataBuilder();
  }
}
