// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0dbae18e83df442db73bc498d357dc97124dcec2b4b7e501f7001660d07c9b3a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Optional;

/**
 * Email attachment representation.
 *
 * <p>Contains metadata and optionally the content of an email attachment.
 */
public record EmailAttachment(
    /** Attachment name (from Content-Disposition header) */
    Optional<String> name,
    /** Filename of the attachment */
    Optional<String> filename,
    /** MIME type of the attachment */
    @JsonProperty("mime_type") Optional<String> mimeType,
    /** Size in bytes */
    Optional<Long> size,
    /** Whether this attachment is an image */
    @JsonProperty("is_image") boolean isImage,
    /** Attachment data (if extracted). */
    Optional<byte[]> data) {}
