// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:80953e420c04c13a4f57542b75f41866767b6b2b83b919373a08f2e7a04207a4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;

/** Embedding response containing generated embeddings. */
public record EmbedResponse(
    /** Generated embeddings (one per input text) */
    List<List<Float>> embeddings,
    /** Model used for embedding generation */
    String model,
    /** Dimensionality of the embeddings */
    long dimensions,
    /** Number of embeddings generated */
    long count) {}
