// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f0c0343511591cedb12388590f405ce7c3ea8d50deadc21ea0896caed07cf09f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;

/**
 * Embedding request for generating embeddings from text.
 */
public record EmbedRequest(List<String> texts, Optional<EmbeddingConfig> config) {
}
