// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:00c651908899b27a6b0a5f5550471f82cc5c29b9da4550d1e7eade8c8efd13ab
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Optional;

/** EPUB metadata (Dublin Core extensions). */
public record EpubMetadata(
    Optional<String> coverage,
    @JsonProperty("dc_format") Optional<String> dcFormat,
    Optional<String> relation,
    Optional<String> source,
    @JsonProperty("dc_type") Optional<String> dcType,
    @JsonProperty("cover_image") Optional<String> coverImage) {
  public static EpubMetadataBuilder builder() {
    return new EpubMetadataBuilder();
  }
}
