// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:73a09d4da93e0935adf6695fb626979a8b4fdd6fa76ece6bf1de25555f10a682
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Error metadata (for batch operations).
 */
public record ErrorMetadata(@JsonProperty("error_type") String errorType, String message) {
}
