// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Map;

/**
 * Excel workbook representation.
 *
 * <p>Contains all sheets from an Excel file (.xlsx, .xls, etc.) with extracted content and
 * metadata.
 */
public record ExcelWorkbook(List<ExcelSheet> sheets, Map<String, String> metadata) {}
