// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:43a6cdb8773c66275314c5715d75a1dfa3b3876d66335fb6db7bbd7495be876e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;

/**
 * Excel/spreadsheet metadata.
 *
 * <p>Contains information about sheets in Excel, OpenDocument Calc, and other spreadsheet formats
 * (.xlsx, .xls, .ods, etc.).
 */
public class ExcelMetadataBuilder {

  private long sheetCount = 0;
  private List<String> sheetNames = List.of();

  /** Sets the sheetCount field. */
  public ExcelMetadataBuilder withSheetCount(final long value) {
    this.sheetCount = value;
    return this;
  }

  /** Sets the sheetNames field. */
  public ExcelMetadataBuilder withSheetNames(final List<String> value) {
    this.sheetNames = value;
    return this;
  }

  /** Builds the ExcelMetadata instance. */
  public ExcelMetadata build() {
    return new ExcelMetadata(sheetCount, sheetNames);
  }
}
