// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Excel/spreadsheet metadata.
 *
 * <p>Contains information about sheets in Excel, OpenDocument Calc, and other spreadsheet formats
 * (.xlsx, .xls, .ods, etc.).
 */
public record ExcelMetadata(
    /** Total number of sheets in the workbook */
    @JsonProperty("sheet_count") long sheetCount,
    /** Names of all sheets in order */
    @JsonProperty("sheet_names") List<String> sheetNames) {
  public static ExcelMetadataBuilder builder() {
    return new ExcelMetadataBuilder();
  }
}
