// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:904e7ebcc20a73e69ef937796a7dd9f9500cd2b12187abfe0fe9630e7a4dab8a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Single Excel worksheet.
 *
 * Represents one sheet from an Excel workbook with its content
 * converted to Markdown format and dimensional statistics.
 */
public record ExcelSheet(
    /** Sheet name as it appears in Excel */
    String name,
    /** Sheet content converted to Markdown tables */
    String markdown,
    /** Number of rows */
    @JsonProperty("row_count") long rowCount,
    /** Number of columns */
    @JsonProperty("col_count") long colCount,
    /** Total number of non-empty cells */
    @JsonProperty("cell_count") long cellCount,
    /** Pre-extracted table cells (2D vector of cell values) */
    @JsonProperty("table_cells") Optional<List<List<String>>> tableCells
) {
}
