// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b94f7a9ebb2d3eafb7688714654ea9485c84c500e24bf7741cb107f12dddda9e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Excel/spreadsheet metadata.
 *
 * Contains information about sheets in Excel, OpenDocument Calc, and other
 * spreadsheet formats (.xlsx, .xls, .ods, etc.).
 */
public record ExcelMetadata(
    /** Total number of sheets in the workbook */
    @JsonProperty("sheet_count") long sheetCount,
    /** Names of all sheets in order */
    @JsonProperty("sheet_names") List<String> sheetNames
) {
    public static ExcelMetadataBuilder builder() {
        return new ExcelMetadataBuilder();
    }
}
