// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2b0106e919120d55051ba1a263705a72a1f1ad4b0d10168f4631c67be99bdab2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/** Extraction response (list of results). */
public class ExtractResponse implements AutoCloseable {
  private final MemorySegment handle;

  ExtractResponse(MemorySegment handle) {
    this.handle = handle;
  }

  MemorySegment handle() {
    return this.handle;
  }

  @Override
  public void close() {
    if (handle != null && !handle.equals(MemorySegment.NULL)) {
      try {
        NativeLib.KREUZBERG_EXTRACT_RESPONSE_FREE.invoke(handle);
      } catch (Throwable e) {
        throw new RuntimeException("Failed to free ExtractResponse: " + e.getMessage(), e);
      }
    }
  }
}
