// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:29cd73833afc4c993c8ee21fa672ea84656da143b264a743a6596356545e73e8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;

/** Extracted inline image with metadata. */
public record ExtractedInlineImage(
    /** Uses {@code bytes::Bytes} for cheap cloning of large buffers. */
    byte[] data,
    String format,
    Optional<String> filename,
    Optional<String> description,
    Optional<List<Integer>> dimensions,
    List<String> attributes) {}
