// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a543ff9b039a47ae9fec176124330d9c9fb05d21cf0f9618fc25316a776fd26e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;

/**
 * Footnote in Djot.
 */
public record Footnote(String label, List<FormattedBlock> content) {
}
