// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cf035deabb7ef2835bfb4493f408997f284a8ae37f04633c099615b75fcfcf5c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;

/**
 * Footnote in Djot.
 */
public record Footnote(String label, List<FormattedBlock> content) {
}
