// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Individual grid cell with position and span metadata.
 */
public record GridCell(
    /** Cell text content. */
    String content,
    /** Zero-indexed row position. */
    int row,
    /** Zero-indexed column position. */
    int col,
    /** Number of rows this cell spans. */
    @JsonProperty("row_span") int rowSpan,
    /** Number of columns this cell spans. */
    @JsonProperty("col_span") int colSpan,
    /** Whether this is a header cell. */
    @JsonProperty("is_header") boolean isHeader,
    /** Bounding box for this cell (if available). */
    Optional<String> bbox
) {
}
