// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:833bf81c53ead8090fcf88c2fb94ea208bea42e9bccb88634cd656ed03106099
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

public record HeaderFooter(
    List<String> paragraphs, List<String> tables, @JsonProperty("header_type") String headerType) {
  public static HeaderFooterBuilder builder() {
    return new HeaderFooterBuilder();
  }
}
