// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b9d289ce3e3541c58f72f25c16e50e3f712acd71bcdcac1487a89e560fb3232d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

public record HeaderFooter(
    List<String> paragraphs,
    List<String> tables,
    @JsonProperty("header_type") String headerType
) {
    public static HeaderFooterBuilder builder() {
        return new HeaderFooterBuilder();
    }
}
