// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e46e70ff5137a9c313ccebb2b498df34f09beea550cfbaaa60a4680da9108824
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;

/**
 * Heading context for a chunk within a Markdown document.
 *
 * Contains the heading hierarchy from document root to this chunk's section.
 */
public record HeadingContext(List<HeadingLevel> headings) {
}
