// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:df9d00f67610eb848e633d0ee3677783bc7c96e823cf415ba3cc6c2f0c437707
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;

/**
 * Heading context for a chunk within a Markdown document.
 *
 * Contains the heading hierarchy from document root to this chunk's section.
 */
public record HeadingContext(List<HeadingLevel> headings) {
}
