// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8c4aacd75cda2c4ee65d336f5d9198ed1fddf881863662316df5f3fa98b67a31
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;

/** Health check response. */
public record HealthResponse(String status, String version, Optional<String> plugins) {}
