// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:126a70b32d4c457cd2b8d331f2f9f696c039e4c95e92a4dfe302ef8d21e038dd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;

/** Result of HTML extraction with optional images and warnings. */
public record HtmlExtractionResult(
    String markdown, List<ExtractedInlineImage> images, List<String> warnings) {}
