// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5a8c3e055ea98eeff1e9e2b6ca52d8983ddeb9caf27b2c61088e84298b715ae4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Image element metadata.
 */
public record ImageMetadataType(
    /** Image source (URL, data URI, or SVG content) */
    String src,
    /** Alternative text from alt attribute */
    Optional<String> alt,
    /** Title attribute */
    Optional<String> title,
    /** Image dimensions as (width, height) if available */
    Optional<List<Integer>> dimensions,
    /** Image type classification */
    @JsonProperty("image_type") ImageType imageType,
    /** Additional attributes as key-value pairs */
    List<String> attributes
) {
}
