// DO NOT EDIT - auto-generated by alef
// alef:hash:dc2a2ccc76386299426c2d295d440f384ab044f470a29d0ebb2643c3b9321b9d
package dev.kreuzberg;

public class ImageProcessingException extends KreuzbergErrorException {
  /** Creates a new ImageProcessingException with the given message. */
  public ImageProcessingException(final String message) {
    super(message);
  }

  /** Creates a new ImageProcessingException with the given message and cause. */
  public ImageProcessingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
