// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4fb9c84594e6d2f4a5c701e9705170c646c0a5844632803ce9909024161cabc0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Server information response.
 */
public record InfoResponse(String version, @JsonProperty("rust_backend") boolean rustBackend) {
}
