// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8da59e548fb02523f1742295ca0fb140749829c5104ebab10567a48bca291387
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Map;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Inline element within a block.
 *
 * Represents text with formatting, links, images, etc.
 */
public record InlineElement(
    /** Type of inline element */
    @JsonProperty("element_type") InlineType elementType,
    /** Text content */
    String content,
    /** Element attributes */
    Optional<String> attributes,
    /** Additional metadata (e.g., href for links, src/alt for images) */
    Optional<Map<String, String>> metadata
) {
}
