// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fa64bae184ecf2e7311dfed15fb3ad779c0a33b6ce5d34e7b535f0c850d974a7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/** JATS (Journal Article Tag Suite) metadata. */
public record JatsMetadata(
    Optional<String> copyright,
    Optional<String> license,
    @JsonProperty("history_dates") Map<String, String> historyDates,
    @JsonProperty("contributor_roles") List<ContributorRole> contributorRoles) {
  public static JatsMetadataBuilder builder() {
    return new JatsMetadataBuilder();
  }
}
