// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c66db2b79b6eee56468fa2f87e0b4961a4ebf5bc38a8e27735273a9e50026a87
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;

/**
 * Extracted keyword with metadata.
 */
public record Keyword(
    /** The keyword text. */
    String text,
    /** Relevance score (higher is better, algorithm-specific range). */
    float score,
    /** Algorithm that extracted this keyword. */
    KeywordAlgorithm algorithm,
    /** Optional positions where keyword appears in text (character offsets). */
    Optional<List<Long>> positions
) {
}
