// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5830f8d736a562c77e93654053055705ddede4f152de4d7a535ca97d66cadf45
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/** A single layout detection result. */
public record LayoutDetection(
    @JsonProperty("class_name") LayoutClass className, float confidence, BBox bbox) {}
