// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8e66418e0b5131778fd43af771ef0bdfa32bb7280ebfdf4bcc46397f819a3b26
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A single layout detection result.
 */
public record LayoutDetection(
    @JsonProperty("class_name") LayoutClass className,
    float confidence,
    BBox bbox
) {
}
