// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** Model manifest response. */
public record ManifestResponse(
    /** Kreuzberg version */
    @JsonProperty("kreuzberg_version") String kreuzbergVersion,
    /** Total size of all models in bytes */
    @JsonProperty("total_size_bytes") long totalSizeBytes,
    /** Number of models in the manifest */
    @JsonProperty("model_count") long modelCount,
    /** Individual model entries */
    List<ManifestEntryResponse> models) {}
