// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4fdf4af36691da1aad2c8e2ed71531e261a8232bae1ee56daac0492d010069a7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/** A merged chunk produced by [{@code merge_segments}]. */
public record MergedChunk(
    String text,
    @JsonProperty("byte_start") long byteStart,
    @JsonProperty("byte_end") long byteEnd) {}
