// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1bd229f7aee1d83560a9d54c4934efc4945dfb7c3005519d4de45846224879dd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/** Combined paths to all models needed for OCR (backward compatibility). */
public record ModelPaths(
    /** Path to the detection model directory. */
    @JsonProperty("det_model") java.nio.file.Path detModel,
    /** Path to the classification model directory. */
    @JsonProperty("cls_model") java.nio.file.Path clsModel,
    /** Path to the recognition model directory. */
    @JsonProperty("rec_model") java.nio.file.Path recModel,
    /** Path to the character dictionary file. */
    @JsonProperty("dict_file") java.nio.file.Path dictFile) {}
