// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bac154e8db5a47ed432b285fa83161e88b6063bee831f3dbe93a358f2345683
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

public record OcrCacheStats(
    @JsonProperty("total_files") long totalFiles,
    @JsonProperty("total_size_mb") double totalSizeMb
) {
    public static OcrCacheStatsBuilder builder() {
        return new OcrCacheStatsBuilder();
    }
}
