// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;

/**
 * Confidence scores for an OCR element.
 *
 * <p>Separates detection confidence (how confident that text exists at this location) from
 * recognition confidence (how confident about the actual text content).
 */
public record OcrConfidence(Optional<Double> detection, double recognition) {
  public static OcrConfidenceBuilder builder() {
    return new OcrConfidenceBuilder();
  }
}
