// DO NOT EDIT - auto-generated by alef
// alef:hash:177593a40eae10f97b81e0a9e6b710aaa08a89feceed73e4f2a2bfc44082afe7
package dev.kreuzberg;

public class OcrException extends KreuzbergErrorException {
    /** Creates a new OcrException with the given message. */
    public OcrException(final String message) {
        super(message);
    }

    /** Creates a new OcrException with the given message and cause. */
    public OcrException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
