// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6ffa9ea840bca9a558da6700b90119450aece8fe9fac59f0312186f95c2c00b3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Optional;

/** Rotation information for an OCR element. */
public record OcrRotation(
    /** Rotation angle in degrees (0, 90, 180, 270 for PaddleOCR). */
    @JsonProperty("angle_degrees") double angleDegrees,
    /** Confidence score for the rotation detection. */
    Optional<Double> confidence) {}
