// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9af9a5736a3bdc49dbd4b0d780ade421d498a28b8dc8a35e3ce30a6721878679
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * OpenWebUI "External" engine response format.
 *
 * Returned by {@code PUT /process} for the OpenWebUI external document loader.
 */
public record OpenWebDocumentResponse(
    /** Extracted text content */
    @JsonProperty("page_content") String pageContent,
    /** Document metadata */
    String metadata
) {
}
