// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4deba1c26de3fea12ab2ee89066af61c2320bdf59145796a76700eda889f9044
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;


/**
 * Document orientation detection result.
 */
public record OrientationResult(int degrees, float confidence) {
}
