// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9595e8f860b43a6f68e2623afe14bdc71d4ab7e4dd852d21af8a8d22233572e1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;


/**
 * Document orientation detection result.
 */
public record OrientationResult(int degrees, float confidence) {
}
