// DO NOT EDIT - auto-generated by alef
// alef:hash:a4ce265d1182c1baff9e06b2dd738c466a40eaee6b4f52d00eba78f8fc2a0d29
package dev.kreuzberg;

public class OtherException extends KreuzbergErrorException {
    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
