// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a721c4556bd6fe48b98dcb521150ea0ee2497ac4bc869b835dd2db961e86fd8b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Page hierarchy structure containing heading levels and block information.
 *
 * Used when PDF text hierarchy extraction is enabled. Contains hierarchical
 * blocks with heading levels (H1-H6) for semantic document structure.
 */
public record PageHierarchy(
    /** Number of hierarchy blocks on this page */
    @JsonProperty("block_count") long blockCount,
    /** Hierarchical blocks with heading levels */
    List<HierarchicalBlock> blocks
) {
}
