// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6ced6d3e8624cfc5687091be7873f06e97b90c738b5aeeaeae7f2d1c4691578b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Metadata for individual page/slide/sheet.
 *
 * Captures per-page information including dimensions, content counts,
 * and visibility state (for presentations).
 */
public record PageInfo(
    /** Page number (1-indexed) */
    long number,
    /** Page title (usually for presentations) */
    Optional<String> title,
    /** Dimensions in points (PDF) or pixels (images): (width, height) */
    Optional<List<Double>> dimensions,
    /** Number of images on this page */
    @JsonProperty("image_count") Optional<Long> imageCount,
    /** Number of tables on this page */
    @JsonProperty("table_count") Optional<Long> tableCount,
    /** Whether this page is hidden (e.g., in presentations) */
    Optional<Boolean> hidden,
    /** Whether this page is blank (no meaningful text, no images, no tables) */
    @JsonProperty("is_blank") Optional<Boolean> isBlank,
    /** Whether this page contains non-trivial vector graphics (paths, shapes, curves) */
    @JsonProperty("has_vector_graphics") boolean hasVectorGraphics
) {
}
