// DO NOT EDIT - auto-generated by alef
// alef:hash:5c3ad0b9b2d1df7f4fa984577ffce41d70677bd538764b401fdd2f1891b39288
package dev.kreuzberg;

public class ParsingException extends KreuzbergErrorException {
    /** Creates a new ParsingException with the given message. */
    public ParsingException(final String message) {
        super(message);
    }

    /** Creates a new ParsingException with the given message and cause. */
    public ParsingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
