// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:93a5466ecab60a3a33d67c78c53a998fd323afbe3bdd8b293174ced9d6bce7c7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Error type for pool operations.
 */
public enum PoolError {
    /** The pool's internal mutex was poisoned. */
    LockPoisoned("lockpoisoned");

    /** The string value. */
    private final String value;

    PoolError(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static PoolError fromValue(final String value) {
        for (PoolError e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
