// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4f2a6ee6a79f458feb19b89ee9ae7c49da7d0b15a7cf98c92323eb87ce62a009
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;


/**
 * A non-fatal warning from a processing pipeline stage.
 *
 * Captures errors from optional features that don't prevent extraction
 * but may indicate degraded results.
 */
public record ProcessingWarning(String source, String message) {
}
