// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Outlook PST archive metadata.
 */
public record PstMetadata(@JsonProperty("message_count") long messageCount) {
    public static PstMetadataBuilder builder() {
        return new PstMetadataBuilder();
    }
}
