// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1433de7d2117d87401d766ade0de539d6185f7f46ce3558020c4204ed4e96b35
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;


/**
 * Outlook PST archive metadata.
 */
public class PstMetadataBuilder {

    private long messageCount = 0;

    /** Sets the messageCount field. */
    public PstMetadataBuilder withMessageCount(final long value) {
        this.messageCount = value;
        return this;
    }

    /** Builds the PstMetadata instance. */
    public PstMetadata build() {
        return new PstMetadata(
            messageCount
        );
    }
}
