// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * RAKE-specific parameters.
 */
public record RakeParams(
    /** Minimum word length to consider (default: 1). */
    @JsonProperty("min_word_length") long minWordLength,
    /** Maximum words in a keyword phrase (default: 3). */
    @JsonProperty("max_words_per_phrase") long maxWordsPerPhrase
) {
    public static RakeParamsBuilder builder() {
        return new RakeParamsBuilder();
    }
}
