// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Pre-computed table markdown for a table detection region.
 */
public record RecognizedTable(
    /** Detection bbox that this table corresponds to (for matching). */
    @JsonProperty("detection_bbox") BBox detectionBbox,
    /** Table cells as a 2D vector (rows x columns). */
    List<List<String>> cells,
    /** Rendered markdown table. */
    String markdown
) {
}
