// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0cb7a626b957161cb6559aad2019667c1af032c6e5b769916157138d8689fe49
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Pre-computed table markdown for a table detection region.
 */
public record RecognizedTable(
    /** Detection bbox that this table corresponds to (for matching). */
    @JsonProperty("detection_bbox") BBox detectionBbox,
    /** Table cells as a 2D vector (rows x columns). */
    List<List<String>> cells,
    /** Rendered markdown table. */
    String markdown
) {
}
