// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b8b0f7b180ccf0ae28791005b1237931ad476e363aabb20d6f6260dcb028302a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;


/**
 * Fully resolved (flattened) style after walking the inheritance chain.
 */
public class ResolvedStyleBuilder {

    private String paragraphProperties = "";
    private String runProperties = "";

    /** Sets the paragraphProperties field. */
    public ResolvedStyleBuilder withParagraphProperties(final String value) {
        this.paragraphProperties = value;
        return this;
    }

    /** Sets the runProperties field. */
    public ResolvedStyleBuilder withRunProperties(final String value) {
        this.runProperties = value;
        return this;
    }

    /** Builds the ResolvedStyle instance. */
    public ResolvedStyle build() {
        return new ResolvedStyle(
            paragraphProperties,
            runProperties
        );
    }
}
