// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Fully resolved (flattened) style after walking the inheritance chain.
 */
public record ResolvedStyle(
    @JsonProperty("paragraph_properties") String paragraphProperties,
    @JsonProperty("run_properties") String runProperties
) {
    public static ResolvedStyleBuilder builder() {
        return new ResolvedStyleBuilder();
    }
}
