// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;


/**
 * Fully resolved (flattened) style after walking the inheritance chain.
 */
public class ResolvedStyleBuilder {

    private String paragraphProperties = "";
    private String runProperties = "";

    /** Sets the paragraphProperties field. */
    public ResolvedStyleBuilder withParagraphProperties(final String value) {
        this.paragraphProperties = value;
        return this;
    }

    /** Sets the runProperties field. */
    public ResolvedStyleBuilder withRunProperties(final String value) {
        this.runProperties = value;
        return this;
    }

    /** Builds the ResolvedStyle instance. */
    public ResolvedStyle build() {
        return new ResolvedStyle(
            paragraphProperties,
            runProperties
        );
    }
}
