// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:512b38a2ba709903d538af8dde51cd9a0e2f7944220f7876b9b43c65f08cd376
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Response from structured extraction endpoint.
 */
public record StructuredExtractionResponse(
    /** Structured data conforming to the provided JSON schema */
    @JsonProperty("structured_output") Object structuredOutput,
    /** Extracted document text content */
    String content,
    /** Detected MIME type of the input file */
    @JsonProperty("mime_type") String mimeType
) {
}
