// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:182091ad21d82583887009eb1adb10f3192467526a632864eb393810b3dc5a25
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A supported document format entry.
 *
 * Represents a file extension and its corresponding MIME type that Kreuzberg can process.
 */
public record SupportedFormat(String extension, @JsonProperty("mime_type") String mimeType) {
}
