// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:866b28d89b7b4485d8a730f18e34457fe318936d3c1e624ddfd506fb17b2aa0a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Table-level properties from {@code <w:tblPr>}.
 */
public record TableProperties(
    @JsonProperty("style_id") Optional<String> styleId,
    Optional<String> width,
    Optional<String> alignment,
    Optional<String> layout,
    Optional<String> look,
    Optional<String> borders,
    @JsonProperty("cell_margins") Optional<String> cellMargins,
    Optional<String> indent,
    Optional<String> caption
) {
    public static TablePropertiesBuilder builder() {
        return new TablePropertiesBuilder();
    }
}
