// DO NOT EDIT - auto-generated by alef
// alef:hash:5978f27bb2c05cf10ec066c90fe564857b2b66740d905a42d1f69b2e103d50ad
package dev.kreuzberg;

public class TimeoutException extends KreuzbergErrorException {
    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
