// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:01507856cccf574e70d0b2658d9735a74e819068ecf6a56622897be71a3f4dba
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Token reduction configuration.
 */
public record TokenReductionOptions(
    /** Reduction mode: "off", "light", "moderate", "aggressive", "maximum" */
    String mode,
    /** Preserve important words (capitalized, technical terms) */
    @JsonProperty("preserve_important_words") boolean preserveImportantWords
) {
}
