// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cf664c135c0c551ed7edd26f33b59624080a490e0f6058d517b0afbc65b1fed2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Token reduction configuration.
 */
public record TokenReductionOptions(
    /** Reduction mode: "off", "light", "moderate", "aggressive", "maximum" */
    String mode,
    /** Preserve important words (capitalized, technical terms) */
    @JsonProperty("preserve_important_words") boolean preserveImportantWords
) {
}
