// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6e4bd1e4d935c287ede31648fe3442cb266c31d18ad1a1d0580b3ced819f5ea8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;

/**
 * Configuration for tree-sitter language pack integration.
 *
 * Controls grammar download behavior and code analysis options.
 *
 * # Example (TOML)
 *
 * {@code }{@code toml}
 * [tree_sitter]
 * languages = ["python", "rust"]
 * groups = ["web"]
 *
 * [tree_sitter.process]
 * structure = true
 * comments = true
 * docstrings = true
 * {@code }{@code }
 */
public class TreeSitterConfigBuilder {

    private boolean enabled = false;
    private Optional<java.nio.file.Path> cacheDir = Optional.empty();
    private Optional<List<String>> languages = Optional.empty();
    private Optional<List<String>> groups = Optional.empty();
    private TreeSitterProcessConfig process = null;

    /** Sets the enabled field. */
    public TreeSitterConfigBuilder withEnabled(final boolean value) {
        this.enabled = value;
        return this;
    }

    /** Sets the cacheDir field. */
    public TreeSitterConfigBuilder withCacheDir(final Optional<java.nio.file.Path> value) {
        this.cacheDir = value;
        return this;
    }

    /** Sets the languages field. */
    public TreeSitterConfigBuilder withLanguages(final Optional<List<String>> value) {
        this.languages = value;
        return this;
    }

    /** Sets the groups field. */
    public TreeSitterConfigBuilder withGroups(final Optional<List<String>> value) {
        this.groups = value;
        return this;
    }

    /** Sets the process field. */
    public TreeSitterConfigBuilder withProcess(final TreeSitterProcessConfig value) {
        this.process = value;
        return this;
    }

    /** Builds the TreeSitterConfig instance. */
    public TreeSitterConfig build() {
        return new TreeSitterConfig(
            enabled,
            cacheDir,
            languages,
            groups,
            process
        );
    }
}
