// DO NOT EDIT - auto-generated by alef
// alef:hash:2885c179c3d6fcc6d56e9636a427e37e6a8744bb7ea28475a13300cc766f1914
package dev.kreuzberg;

public class ValidationException extends KreuzbergErrorException {
    /** Creates a new ValidationException with the given message. */
    public ValidationException(final String message) {
        super(message);
    }

    /** Creates a new ValidationException with the given message and cause. */
    public ValidationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
