// DO NOT EDIT - auto-generated by alef
// alef:hash:cda28e827548a408eb64aa06b71e14530502911c9ed65e041ce0b2d3949cd94a
package dev.kreuzberg;

public class ValidationException extends KreuzbergErrorException {
    /** Creates a new ValidationException with the given message. */
    public ValidationException(final String message) {
        super(message);
    }

    /** Creates a new ValidationException with the given message and cause. */
    public ValidationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
