// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:53ce981dae3259b9f8676cbe20a7806ab9137cd0431433430e37ff70ad6871bd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;


/**
 * Version response.
 */
public record VersionResponse(String version) {
}
