// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Cache warm request.
 */
public record WarmRequest(
    /** Download all embedding model presets */
    @JsonProperty("all_embeddings") boolean allEmbeddings,
    /** Specific embedding model preset to download */
    @JsonProperty("embedding_model") Optional<String> embeddingModel
) {
    public static WarmRequestBuilder builder() {
        return new WarmRequestBuilder();
    }
}
