// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ce88053a2e56353e45e7b9a0b8b66a0cc573d566a261ebd0050ddef3b8fa3fc6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * XML extraction result.
 *
 * Contains extracted text content from XML files along with
 * structural statistics about the XML document.
 */
public record XmlExtractionResult(
    /** Extracted text content (XML structure filtered out) */
    String content,
    /** Total number of XML elements processed */
    @JsonProperty("element_count") long elementCount,
    /** List of unique element names found (sorted) */
    @JsonProperty("unique_elements") List<String> uniqueElements
) {
}
