# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f379e3061a6ad0c4a29e0c4a34237c6018c68225c83fb76278b06a0acc22d8d6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.AnchorProperties do
  @moduledoc "Properties for anchored drawings."

  defstruct behind_doc: false,
            layout_in_cell: false,
            relative_height: 0,
            position_h: "",
            position_v: "",
            wrap_type: ""
end
