# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cb740aa9357a85228f6f248a7c1eb5b4019c37d91f10e30553f5451647b4bd87
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ApiState do
  @moduledoc "API server state."

  defstruct default_config: nil,
            extraction_service: ""
end
