# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.BatchProcessorConfig do
  @moduledoc "Configuration for batch processing with pooling optimizations."

  defstruct string_pool_size: 10,
            string_buffer_capacity: 8_192,
            byte_pool_size: 10,
            byte_buffer_capacity: 65_536,
            max_concurrent: nil
end
