# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.BibtexMetadata do
  @moduledoc "BibTeX bibliography metadata."

  defstruct entry_count: 0,
            citation_keys: [],
            authors: [],
            year_range: nil,
            entry_types: %{}
end
