# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.BorderStyle do
  @moduledoc "A single border specification."

  defstruct style: "",
            size: nil,
            color: nil,
            space: nil
end
