# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4a1d559d3ee3cb6f1241754c3397c351c1ee6c6a2036808ce4f0f340743984a0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CacheWarmParams do
  @moduledoc "Request parameters for cache warm (model download)."

  defstruct all_embeddings: false,
            embedding_model: nil
end
