# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:aac9cf21fe919e3e693eb0af1153312b93318574566f1c36ee8908709a709a5b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CacheClearResponse do
  @moduledoc "Cache clear response."

  defstruct directory: "",
            removed_files: 0,
            freed_mb: 0.0
end
