# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkResponse do
  @moduledoc "Chunk response with chunks and metadata."

  defstruct chunks: [],
            chunk_count: 0,
            config: "",
            input_size_bytes: 0,
            chunker_type: ""
end
