# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkTextParams do
  @moduledoc "Request parameters for text chunking."

  defstruct text: "",
            max_characters: nil,
            overlap: nil,
            chunker_type: nil,
            topic_threshold: nil
end
