# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2afde10db7fbf3bbb97e4d3eeb70cced4208d92fdfd03b8ed98173d5eb8cebcc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkRequest do
  @moduledoc "Chunk request with text and configuration."

  defstruct text: "",
            config: nil,
            chunker_type: ""
end
