# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c1b8d1d30d80cb5c6d6ba618fa6f1bf14d2fcd75756e7d834dfb63b8b693acde
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkTextParams do
  @moduledoc "Request parameters for text chunking."

  defstruct text: "",
            max_characters: nil,
            overlap: nil,
            chunker_type: nil,
            topic_threshold: nil
end
