# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c5b753eebff4f7333c3fa3ef00075639e085d736f4fb43cfdead9c8ddeddcc73
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Chunk do
  @moduledoc "A text chunk with optional embedding and metadata."

  defstruct content: "",
            chunk_type: :unknown,
            embedding: nil,
            metadata: nil
end
