# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3acf57f467f9fe5cf9453e9f5af24fb2443996baa6fe523eca5a140ae188a12a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkSizing do
  @moduledoc "How chunk size is measured."

  @type t :: term()

  @type characters :: :characters
  @type tokenizer :: %{type: :tokenizer, model: term(), cache_dir: term()}
end
