# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.ColorScheme do
  @moduledoc "Color scheme containing all 12 standard Office theme colors."

  defstruct name: "",
            dk1: :rgb,
            lt1: :rgb,
            dk2: :rgb,
            lt2: :rgb,
            accent1: :rgb,
            accent2: :rgb,
            accent3: :rgb,
            accent4: :rgb,
            accent5: :rgb,
            accent6: :rgb,
            hlink: :rgb,
            fol_hlink: :rgb
end
