# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6891dfe4d2c97d91b454c249abe15ce35407682779190f09ca9f35b660b22fcb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContentFilterConfig do
  @moduledoc "Cross-extractor content filtering configuration."

  defstruct include_headers: false,
            include_footers: false,
            strip_repeating_text: true,
            include_watermarks: false
end
