# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2b424ace3b8e2ec7050eb11da57cca6146b5e46f4b086896d1027a2ef2fd8fe3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectMimeTypeParams do
  @moduledoc "Request parameters for MIME type detection."

  defstruct path: "",
            use_content: false
end
