# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:93db1ecc1ab17c59220fa55118ffdb46ca37327492e8d0889090c48ed2744409
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectMimeTypeParams do
  @moduledoc "Request parameters for MIME type detection."

  defstruct path: "",
            use_content: false
end
