# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9f3cb60d3f2cfc5ad8c14026767ecc39484ee9197eae67739fd03709dc699af6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotContent do
  @moduledoc "Comprehensive Djot document structure with semantic preservation."

  defstruct plain_text: "",
            blocks: [],
            metadata: nil,
            tables: [],
            images: [],
            links: [],
            footnotes: [],
            attributes: []
end
