# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.DjotContent do
  @moduledoc "Comprehensive Djot document structure with semantic preservation."

  defstruct plain_text: "",
            blocks: [],
            metadata: nil,
            tables: [],
            images: [],
            links: [],
            footnotes: [],
            attributes: []
end
