# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:99fffaa9b3fb05c9b896c54c54b0334ca1860b8d7ee4992f459a368772f087f9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentRelationship do
  @moduledoc "A resolved relationship between two nodes in the document tree."

  defstruct source: 0,
            target: 0,
            kind: :footnote_reference
end
