# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.DocumentRelationship do
  @moduledoc "A resolved relationship between two nodes in the document tree."

  defstruct source: 0,
            target: 0,
            kind: :footnote_reference
end
