# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.DocumentStructure do
  @moduledoc "Top-level structured document representation."

  defstruct nodes: [],
            source_format: "",
            relationships: []
end
