# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.Element do
  @moduledoc "Semantic element extracted from document."

  defstruct element_id: "",
            element_type: :title,
            text: "",
            metadata: nil
end
