# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1065a7045a8ca8098036a48dc24c1c261d37c50478b820c334e56005409505d6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailAttachment do
  @moduledoc "Email attachment representation."

  defstruct name: nil,
            filename: nil,
            mime_type: nil,
            size: nil,
            is_image: false,
            data: nil
end
