# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7d2336d38ab277637d18401e49640261dfbadc1d76d3faa0c013cd8be6003cda
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedRequest do
  @moduledoc "Embedding request for generating embeddings from text."

  defstruct texts: [],
            config: nil
end
