# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedTextParams do
  @moduledoc "Request parameters for embedding generation."

  defstruct texts: [],
            preset: nil,
            model: nil,
            api_key: nil,
            embedding_plugin: nil
end
