# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f59d7aaa682e4cf7d3292970e530e6db35c74cada7374c620292ee4b050b035f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  defstruct name: "",
            data: "",
            mime_type: nil
end
