# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:02733324ee0ada7d386549cf2793dff5ac2d8800f333590c10e9cab0dfdd5409
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedTextParams do
  @moduledoc "Request parameters for embedding generation."

  defstruct texts: [],
            preset: nil,
            model: nil,
            api_key: nil,
            embedding_plugin: nil
end
