# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.EmbedTextParams do
  @moduledoc "Request parameters for embedding generation."

  defstruct texts: [],
            preset: nil,
            model: nil,
            api_key: nil
end
