# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.EmbeddingConfig do
  @moduledoc "Embedding configuration for text chunks."

  defstruct model: :preset,
            normalize: true,
            batch_size: 32,
            show_download_progress: false,
            cache_dir: ""
end
