# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.EpubMetadata do
  @moduledoc "EPUB metadata (Dublin Core extensions)."

  defstruct coverage: "",
            dc_format: "",
            relation: "",
            source: "",
            dc_type: "",
            cover_image: ""
end
