# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:49ecd0d362e6994628aa4790d108429bc87617a6ee5146d89ca9f252dd2e1b99
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelWorkbook do
  @moduledoc "Excel workbook representation."

  defstruct sheets: [],
            metadata: %{}
end
