# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:41b6e26bc4f6faa0ec08aba536361b3fcd60b6bbc0e7fe2fa92fdb764b3e9c44
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractBytesParams do
  @moduledoc "Request parameters for bytes extraction."

  defstruct data: "",
            mime_type: nil,
            config: nil,
            pdf_password: nil,
            response_format: nil
end
