# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractedImage do
  @moduledoc "Extracted image from a document."

  defstruct data: "",
            format: "",
            image_index: 0,
            page_number: nil,
            width: nil,
            height: nil,
            colorspace: nil,
            bits_per_component: nil,
            is_mask: false,
            description: nil,
            ocr_result: nil,
            bounding_box: nil,
            source_path: nil
end
