# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8a452ab5d5a6e7ee27bda9eca31dacea6737a99d7ffed5fb4c9190df5d59e6e5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractStructuredParams do
  @moduledoc "Request parameters for LLM-based structured extraction."

  defstruct path: "",
            schema: "",
            model: "",
            schema_name: "",
            schema_description: nil,
            prompt: nil,
            api_key: nil,
            strict: false
end
