# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7ca56ad24fc776e689da2fa0f543c54cbbfd9e86a40538b14cbde3e820cadc87
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractFileParams do
  @moduledoc "Request parameters for file extraction."

  defstruct path: "",
            mime_type: nil,
            config: nil,
            pdf_password: nil,
            response_format: nil
end
