# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ea4b53713e043f5ef6b837535f6808a327a9dca0939d7f0ed915b507b07ad285
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractFileParams do
  @moduledoc "Request parameters for file extraction."

  defstruct path: "",
            mime_type: nil,
            config: nil,
            pdf_password: nil,
            response_format: nil
end
