# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.ExtractionRequest do
  @moduledoc "A request to extract content from a single document."

  defstruct source: :file,
            config: nil,
            file_overrides: nil
end
