# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.FontScheme do
  @moduledoc "Font scheme containing major (heading) and minor (body) fonts."

  defstruct name: "",
            major_latin: "",
            major_east_asian: "",
            major_complex_script: "",
            minor_latin: "",
            minor_east_asian: "",
            minor_complex_script: ""
end
