# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9f387a6047166a2f77be093b79eecd5bec42916b4dd59eda7a5f07716ae91ca3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FormattedBlock do
  @moduledoc "Block-level element in a Djot document."

  defstruct block_type: :paragraph,
            level: nil,
            inline_content: [],
            attributes: nil,
            language: nil,
            code: nil,
            children: []
end
