# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9f7874b593a79e65db52512bc5d81f05a84f59104a2c6a013582a84f2286e6f9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FormattedBlock do
  @moduledoc "Block-level element in a Djot document."

  defstruct block_type: :paragraph,
            level: nil,
            inline_content: [],
            attributes: nil,
            language: nil,
            code: nil,
            children: []
end
