# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:300ce2cb042dc185bd1415f6d14c66a5e2d85c30724bf76d7deadbec59d894b3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FormattedBlock do
  @moduledoc "Block-level element in a Djot document."

  defstruct block_type: :paragraph,
            level: nil,
            inline_content: [],
            attributes: nil,
            language: nil,
            code: nil,
            children: []
end
