# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e7bfa06b0792e93471bd38529ef82909cb0ade2261fdd62cc466ed4fc695ecde
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeaderFooter do
  @moduledoc false

  defstruct paragraphs: [],
            tables: [],
            header_type: ""
end
