# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.HeaderMetadata do
  @moduledoc "Header/heading element metadata."

  defstruct level: 0,
            text: "",
            id: nil,
            depth: 0,
            html_offset: 0
end
