# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:703e56683c7ae2891c2fc174dba531add39a0f7269f56098b875e580af858d81
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeaderMetadata do
  @moduledoc "Header/heading element metadata."

  defstruct level: 0,
            text: "",
            id: nil,
            depth: 0,
            html_offset: 0
end
