# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b010529e41532c4750e0548ff76a7167f359c0c82fa8b0d54efc83d6fcd1cb83
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeaderMetadata do
  @moduledoc "Header/heading element metadata."

  defstruct level: 0,
            text: "",
            id: nil,
            depth: 0,
            html_offset: 0
end
