# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b337b9413f5e963e3532ac42a2f4240a8ea3c1d55b8f980e205a03c0f1b15500
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HtmlTheme do
  @moduledoc "Built-in HTML theme selection."

  @type t :: :default | :git_hub | :dark | :light | :unstyled

  @default :default
  @git_hub :git_hub
  @dark :dark
  @light :light
  @unstyled :unstyled

  @spec default() :: t()
  def default, do: @default
  @spec git_hub() :: t()
  def git_hub, do: @git_hub
  @spec dark() :: t()
  def dark, do: @dark
  @spec light() :: t()
  def light, do: @light
  @spec unstyled() :: t()
  def unstyled, do: @unstyled
end
