# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5a50c640ea66646785dd25529859259bc3dadd63edd62315656532da6d3e6770
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImagePreprocessingConfig do
  @moduledoc "Image preprocessing configuration for OCR."

  defstruct target_dpi: 300,
            auto_rotate: true,
            deskew: true,
            denoise: false,
            contrast_enhance: false,
            binarization_method: "otsu",
            invert_colors: false
end
