# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.ImageMetadata do
  @moduledoc "Image metadata extracted from image files."

  defstruct width: 0,
            height: 0,
            format: "",
            exif: %{}
end
