# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.ImageExtractionConfig do
  @moduledoc "Image extraction configuration."

  defstruct extract_images: false,
            target_dpi: 0,
            max_image_dimension: 0,
            inject_placeholders: false,
            auto_adjust_dpi: false,
            min_dpi: 0,
            max_dpi: 0
end
