# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e603a7af5e2dc23a89580233401aadf0625d62501acc1b531b9bb85b72d344c2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImageMetadataType do
  @moduledoc "Image element metadata."

  defstruct src: "",
            alt: nil,
            title: nil,
            dimensions: nil,
            image_type: :data_uri,
            attributes: []
end
