# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:829beb7db1bfc2d1b2e5bc155ae05673f7a3907044738e2c7d8c50dad61fd7ad
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.InfoResponse do
  @moduledoc "Server information response."

  defstruct version: "",
            rust_backend: false
end
