# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f413378b768c128b70dcba2af9ac29ebeaf95cb1a7c7b98350d752358cbdb4a0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.InlineElement do
  @moduledoc "Inline element within a block."

  defstruct element_type: :text,
            content: "",
            attributes: nil,
            metadata: nil
end
