# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9a0d19db30e5cecbbbc2ec78abc4c9cbc58c7b669912f3cfa6b02e5472c216f2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.JatsMetadata do
  @moduledoc "JATS (Journal Article Tag Suite) metadata."

  defstruct copyright: "",
            license: "",
            history_dates: %{},
            contributor_roles: []
end
