# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.KeywordConfig do
  @moduledoc "Keyword extraction configuration."

  defstruct algorithm: :yake,
            max_keywords: 10,
            min_score: 0,
            ngram_range: "",
            language: "",
            yake_params: nil,
            rake_params: nil
end
