# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:af63c05edf5c2d90b69911969702649cbaf5400873828dc44b239cf46a60e3fc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Keyword do
  @moduledoc "Extracted keyword with metadata."

  defstruct text: "",
            score: 0.0,
            algorithm: :yake,
            positions: nil
end
