# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.LanguageDetectionConfig do
  @moduledoc "Language detection configuration."

  defstruct enabled: false,
            min_confidence: 0.0,
            detect_multiple: false
end
