# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a1ba41e45ba9d2069866eb6875ef81b6f3dd8367bb0096bba2c219e059225469
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LanguageDetectionConfig do
  @moduledoc "Language detection configuration."

  defstruct enabled: false,
            min_confidence: 0.0,
            detect_multiple: false
end
