# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:55a13e4b80b0c7049abe7457e088536df5516717d4c38b06bf8551c74c8eaadc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LayoutDetection do
  @moduledoc "A single layout detection result."

  defstruct class_name: :caption,
            confidence: 0.0,
            bbox: nil
end
