# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f8cfd951636dd447105424c97bee6a097fda5b578eb28fedea410474d223bc45
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LayoutDetection do
  @moduledoc "A single layout detection result."

  defstruct class_name: :caption,
            confidence: 0.0,
            bbox: nil
end
