# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:03d59f00c3a46518713a456e9ad395bf8e3e7889965e2725ffcf7256916bdaca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LayoutDetection do
  @moduledoc "A single layout detection result."

  defstruct class_name: :caption,
            confidence: 0.0,
            bbox: nil
end
