# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.LayoutTimingReport do
  @moduledoc "Timing breakdown for the entire layout detection run."

  defstruct total_ms: 0.0,
            per_page: []
end
