# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c934a6473ff979db67878da025d3b75cc8caf5b2ff6c1f7cfa3516178aeabb61
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LayoutDetectionConfig do
  @moduledoc "Layout detection configuration."

  defstruct confidence_threshold: nil,
            apply_heuristics: true,
            table_model: :tatr,
            acceleration: nil
end
