# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:335cfd2c1cfc045a3133ade9f7d333957c5fae3fc9fa535238e007ce15a48dbf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LinkMetadata do
  @moduledoc "Link element metadata."

  defstruct href: "",
            text: "",
            title: nil,
            link_type: :anchor,
            rel: [],
            attributes: []
end
