# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.LlmConfig do
  @moduledoc "Configuration for an LLM provider/model via liter-llm."

  defstruct model: "",
            api_key: nil,
            base_url: nil,
            timeout_secs: nil,
            max_retries: nil,
            temperature: nil,
            max_tokens: nil
end
