# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:279640881438d8227d5fb9ee8b216ca1827564e872fd207f43b19474d46447af
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ManifestEntryResponse do
  @moduledoc "Model manifest entry for cache management."

  defstruct relative_path: "",
            sha256: "",
            size_bytes: 0,
            source_url: ""
end
