# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6099fc64a133f4b4a6d2013a2857a84d4d55d88965e701caab7ef283cfb50796
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.MergedChunk do
  @moduledoc "A merged chunk produced by [`merge_segments`]."

  defstruct text: "",
            byte_start: 0,
            byte_end: 0
end
