# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.MultipartApi do
  @moduledoc "Custom Multipart extractor that returns JSON error responses instead of plain text."

  defstruct 0: ""
end
