# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:960f7a4b91913b5e4255badb1b119028e32519f246f68011e2c1e8d3a599ad96
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrConfidence do
  @moduledoc "Confidence scores for an OCR element."

  defstruct detection: 0.0,
            recognition: 0.0
end
