# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e4f113871b3d97f1c33e6d66395e65425cd4e77d3edf171eb3bd56992a52b273
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrTableBoundingBox do
  @moduledoc "Bounding box for an OCR-detected table in pixel coordinates."

  defstruct left: 0,
            top: 0,
            right: 0,
            bottom: 0
end
