# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.OcrConfidence do
  @moduledoc "Confidence scores for an OCR element."

  defstruct detection: 0.0,
            recognition: 0.0
end
