# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5277b509462c946faf79126caad777b82e0bbc16e831a8cfe68ba6dcd57bcabb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrPipelineConfig do
  @moduledoc "Multi-backend OCR pipeline with quality-based fallback."

  defstruct stages: [],
            quality_thresholds: nil
end
