# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8facfd0fb6906e9d2e7f1ea81d48fce6343339335d24152e26ca5e36cb9b88c3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrElementConfig do
  @moduledoc "Configuration for OCR element extraction."

  defstruct include_elements: false,
            min_level: :line,
            min_confidence: 0.0,
            build_hierarchy: false
end
