# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f3cbd7374efeaa05d0117836de5f8c06ba8ad3db47321c023f352b03ae57cdbd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrCacheStats do
  @moduledoc false

  defstruct total_files: 0,
            total_size_mb: 0.0
end
