# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9b63d90b4c015cd0ff5f2a65f4b731cb195627a5f2c5cc7323a784cdc97c8074
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OpenWebDocumentResponse do
  @moduledoc "OpenWebUI \"External\" engine response format."

  defstruct page_content: "",
            metadata: ""
end
