# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.PageConfig do
  @moduledoc "Page extraction and tracking configuration."

  defstruct extract_pages: false,
            insert_page_markers: false,
            marker_format: "

<!-- PAGE {page_num} -->

"
end
