# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e2b18bf31e7abece7a5cbe01ba958b802ddaf5efc3d88d0715a1fe9e3ee2463e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageBoundary do
  @moduledoc "Byte offset boundary for a page."

  defstruct byte_start: 0,
            byte_end: 0,
            page_number: 0
end
