# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a99cf4e3486cc0b8ad6d8317c143894314e10e43c564c880249cd3e501e83654
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageConfig do
  @moduledoc "Page extraction and tracking configuration."

  defstruct extract_pages: false,
            insert_page_markers: false,
            marker_format: "

<!-- PAGE {page_num} -->

"
end
