# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e9a52919daaa856aac466c4f9cd9c73ef720ad03a9514ba7a63f0b5b4e7afd4f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageContent do
  @moduledoc "Content for a single page/slide."

  defstruct page_number: 0,
            content: "",
            tables: [],
            images: [],
            hierarchy: nil,
            is_blank: nil,
            layout_regions: nil
end
