# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.PageStructure do
  @moduledoc "Unified page structure for documents."

  defstruct total_count: 0,
            unit_type: :page,
            boundaries: nil,
            pages: nil
end
