# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:95e1cfed8fd1f35dc3fb633aa1a8f7e0ea103a13d8c4700143e1bce332376c03
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageInfo do
  @moduledoc "Metadata for individual page/slide/sheet."

  defstruct number: 0,
            title: nil,
            dimensions: nil,
            image_count: nil,
            table_count: nil,
            hidden: nil,
            is_blank: nil
end
