# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ace8fe0639765a8cb28cebaead0bfa7b3b46dccdc30104ddb12ddbff76a1e2e8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageStructure do
  @moduledoc "Unified page structure for documents."

  defstruct total_count: 0,
            unit_type: :page,
            boundaries: nil,
            pages: nil
end
