# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PdfBackend do
  @moduledoc "PDF extraction backend selection."

  @type t :: :pdfium | :pdf_oxide | :auto

  @pdfium :pdfium
  @pdf_oxide :pdf_oxide
  @auto :auto

  @spec pdfium() :: t()
  def pdfium, do: @pdfium
  @spec pdf_oxide() :: t()
  def pdf_oxide, do: @pdf_oxide
  @spec auto() :: t()
  def auto, do: @auto
end
