# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:16708b89bca8f19bc40ce21a7437db6be853f3a35a9a9d9ceeff7172904edda4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PdfAnnotation do
  @moduledoc "A PDF annotation extracted from a document page."

  defstruct annotation_type: :text,
            content: nil,
            page_number: 0,
            bounding_box: nil
end
