# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a2b379d22605ec20a7c0f1392116c9641ff8e65582b889a89b3f1e746f34df2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PdfAnnotation do
  @moduledoc "A PDF annotation extracted from a document page."

  defstruct annotation_type: :text,
            content: nil,
            page_number: 0,
            bounding_box: nil
end
