# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cb845e7df3e6f4a76c30c21cb20f223a5b8e88c6acfe63bc647f2dabc3afd2df
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PostProcessorConfig do
  @moduledoc "Post-processor configuration."

  defstruct enabled: true,
            enabled_processors: nil,
            disabled_processors: nil,
            enabled_set: nil,
            disabled_set: nil
end
