# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9f74ebcda2599d6ddd317b3fdb89d1fbe378533c132f73012a719b0793cc8d42
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PostProcessorConfig do
  @moduledoc "Post-processor configuration."

  defstruct enabled: true,
            enabled_processors: nil,
            disabled_processors: nil,
            enabled_set: nil,
            disabled_set: nil
end
