# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PptxAppProperties do
  @moduledoc "Application properties from docProps/app.xml for PPTX"

  defstruct application: "",
            app_version: "",
            total_time: 0,
            company: "",
            doc_security: 0,
            scale_crop: false,
            links_up_to_date: false,
            shared_doc: false,
            hyperlinks_changed: false,
            slides: 0,
            notes: 0,
            hidden_slides: 0,
            multimedia_clips: 0,
            presentation_format: "",
            slide_titles: []
end
