# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a4aa2090e5ac5631f8f69a33b2ecf4c92e5e32abfb0d4fc592e8f797b5d64807
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PptxMetadata do
  @moduledoc "PowerPoint presentation metadata."

  defstruct slide_count: 0,
            slide_names: [],
            image_count: 0,
            table_count: 0
end
