# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ProcessingStage do
  @moduledoc "Processing stages for post-processors."

  @type t :: :early | :middle | :late

  @early :early
  @middle :middle
  @late :late

  @spec early() :: t()
  def early, do: @early
  @spec middle() :: t()
  def middle, do: @middle
  @spec late() :: t()
  def late, do: @late
end
