# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:71e8a4d23e7f2c8fdba9c09eeee3beda42769a67bbb9facdc67bbbb164442adc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.RakeParams do
  @moduledoc "RAKE-specific parameters."

  defstruct min_word_length: 1,
            max_words_per_phrase: 3
end
