# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1ca7a303caceb4c5f1135aa39ab10f336ae3ffaa9b5c0297ab4b5d4f9ac57bbd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.RakeParams do
  @moduledoc "RAKE-specific parameters."

  defstruct min_word_length: 1,
            max_words_per_phrase: 3
end
