# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.RakeParams do
  @moduledoc "RAKE-specific parameters."

  defstruct min_word_length: 1,
            max_words_per_phrase: 3
end
