# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:608b324b91b62f80caeb9e21aa9199be63aa99d05b0f9691f7dca11c8fe56b9f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.RecognizedTable do
  @moduledoc "Pre-computed table markdown for a table detection region."

  defstruct detection_bbox: nil,
            cells: [],
            markdown: ""
end
