# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bcba8ef419baf264f0a5d212eb7a2604fa751ff52ff3bd7ddf1dbd4202b72ce0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.RecognizedTable do
  @moduledoc "Pre-computed table markdown for a table detection region."

  defstruct detection_bbox: nil,
            cells: [],
            markdown: ""
end
