# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d648313c37c419fb60944252d8f07435b66d7de511e62aa3eab479aacfebf7cd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ResolvedStyle do
  @moduledoc "Fully resolved (flattened) style after walking the inheritance chain."

  defstruct paragraph_properties: "",
            run_properties: ""
end
