# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:be7fafd5e6b353f51424fdcd354a249861702b414ff316140a70830d0a552e2f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredData do
  @moduledoc "Structured data (Schema.org, microdata, RDFa) block."

  defstruct data_type: :json_ld,
            raw_json: "",
            schema_type: nil
end
