# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:220b91cae5c0ab19b7084680d81e91094b0570e012eb7bbcf1fa5e302d7e4e51
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredExtractionResponse do
  @moduledoc "Response from structured extraction endpoint."

  defstruct structured_output: "",
            content: "",
            mime_type: ""
end
