# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4984cc8c612b05a9c8ba7fca44f36d8b9bb1a614bbd5aa11e9bcff94b3999d4a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredExtractionConfig do
  @moduledoc "Configuration for LLM-based structured data extraction."

  defstruct schema: "",
            schema_name: "",
            schema_description: nil,
            strict: false,
            prompt: nil,
            llm: nil
end
