# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:27796bbe83343fd36d7ad536abe9b48b51f03474da6c4720a438c97c7d1c3563
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredExtractionConfig do
  @moduledoc "Configuration for LLM-based structured data extraction."

  defstruct schema: "",
            schema_name: "",
            schema_description: nil,
            strict: false,
            prompt: nil,
            llm: nil
end
