# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:596d48e3927bff8592f7083ec6094e6555a98a88e2ab841b65f0818b6d3d0073
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.SupportedFormat do
  @moduledoc "A supported document format entry."

  defstruct extension: "",
            mime_type: ""
end
