# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.TableBorders do
  @moduledoc "Borders for a table (6 borders: top, bottom, left, right, insideH, insideV)."

  defstruct top: "",
            bottom: "",
            left: "",
            right: "",
            inside_h: "",
            inside_v: ""
end
