# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7e9a888aa8d73609e9950749796d8a4d71a3436885c0c45081e4310eb3232d59
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TableProperties do
  @moduledoc "Table-level properties from `<w:tblPr>`."

  defstruct style_id: "",
            width: "",
            alignment: "",
            layout: "",
            look: "",
            borders: "",
            cell_margins: "",
            indent: "",
            caption: ""
end
