# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1a8ca47efed1890e5f76ed17d5cc8c14aba4af0a334fc22fdd8238b3a3f53000
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TextAnnotation do
  @moduledoc "Inline text annotation — byte-range based formatting and links."

  defstruct start: 0,
            end: 0,
            kind: :bold
end
