# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:655ca1877fc373d5dbd0cb9ce8d9d12cc6dcf01ad98866b94fceb0979f1c01fd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TextMetadata do
  @moduledoc "Text/Markdown metadata."

  defstruct line_count: 0,
            word_count: 0,
            character_count: 0,
            headers: [],
            links: [],
            code_blocks: []
end
