# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d071e768e72755c6cfc71fe435ec94d303e7d2784e770ce37460cc3d2cb1d4aa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TokenReductionConfig do
  @moduledoc false

  defstruct level: :moderate,
            language_hint: nil,
            preserve_markdown: false,
            preserve_code: true,
            semantic_threshold: 0.3,
            enable_parallel: true,
            use_simd: true,
            custom_stopwords: nil,
            preserve_patterns: [],
            target_reduction: nil,
            enable_semantic_clustering: false
end
