# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TokenReductionConfig do
  @moduledoc false

  defstruct level: :moderate,
            language_hint: nil,
            preserve_markdown: false,
            preserve_code: true,
            semantic_threshold: 0.3,
            enable_parallel: true,
            use_simd: true,
            custom_stopwords: nil,
            preserve_patterns: [],
            target_reduction: nil,
            enable_semantic_clustering: false
end
