# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:da815fad13e6873dfe369405ae71042026b4c1563eae92c1692cb0ab74ab10c7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TreeSitterConfig do
  @moduledoc "Configuration for tree-sitter language pack integration."

  defstruct enabled: true,
            cache_dir: nil,
            languages: nil,
            groups: nil,
            process: nil
end
