# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6d9f8bcdb72d78b65c059558917c38dc9bebffdbb4d0b7f270fca8082a715161
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.WarmRequest do
  @moduledoc "Cache warm request."

  defstruct all_embeddings: false,
            embedding_model: ""
end
