# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:36c49a2ab557bce21247eeba3079dca5d9ce13af76b67d67ba672bcfa96247e0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.WarmRequest do
  @moduledoc "Cache warm request."

  defstruct all_embeddings: false,
            embedding_model: ""
end
