# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:80b8888f67b5c8d5e0d65f179959d0b3653f6b46951046ebb110c727415f82b8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.XlsxAppProperties do
  @moduledoc "Application properties from docProps/app.xml for XLSX"

  defstruct application: "",
            app_version: "",
            doc_security: 0,
            scale_crop: false,
            links_up_to_date: false,
            shared_doc: false,
            hyperlinks_changed: false,
            company: "",
            worksheet_names: []
end
