# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5a28ebe1bf50af71add2f08ac25ecd727ac6f4f3e7678e4e42bdce386a9e9b57
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.XmlMetadata do
  @moduledoc "XML metadata extracted during XML parsing."

  defstruct element_count: 0,
            unique_elements: []
end
