// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, it, expect } from 'vitest';
import { extract_file } from 'kreuzberg';

describe('configuration', () => {
  it('config_discover: Discover configuration from current or parent directories', async () => {
    const result = await extract_file('');
    expect(result.result.chunking.length).toBeGreaterThan(0);
    expect(result.result.chunking.maxChars).toBe(50);
  });

  it('config_from_file: Load configuration from a TOML file', async () => {
    const result = await extract_file('');
    expect(result.result.chunking.length).toBeGreaterThan(0);
    expect(result.result.chunking.maxChars).toBe(100);
    expect(result.result.chunking.maxOverlap).toBe(20);
    expect(result.result.languageDetection.length).toBeGreaterThan(0);
    expect(result.result.languageDetection.enabled).toBe(false);
  });
});
