// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:42bbf256de582e790ff1ad5d84954ac2c46141c932b92fe724439957cd2aa8a9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, it, expect } from 'vitest';
import { extract_file, extract_file_sync, JsExtractionConfig } from 'kreuzberg';

describe('document', () => {
  it('doc_metadata_docx: Extract DOCX metadata', () => {
    const result = extract_file_sync("vendored/markitdown/test.docx");
    expect(result.metadata.length).toBeGreaterThan(0);
  });

  it('doc_metadata_pdf: Extract PDF metadata', () => {
    const result = extract_file_sync("pdf/fake_memo.pdf");
    expect(result.metadata.length).toBeGreaterThan(0);
  });

  it('doc_structure_docx: Extract DOCX document structure with include_document_structure config', () => {
    const options = new JsExtractionConfig();
    options.includeDocumentStructure = true;
    const result = extract_file_sync("vendored/markitdown/test.docx", options);
    expect(result.documentStructure.length).toBeGreaterThan(0);
  });

  it('doc_structure_html: Extract HTML document structure with include_document_structure config', () => {
    const options = new JsExtractionConfig();
    options.includeDocumentStructure = true;
    const result = extract_file_sync("html/html.html", options);
    expect(result.documentStructure.length).toBeGreaterThan(0);
  });

  it('doc_structure_pdf: Extract PDF document structure with include_document_structure config', () => {
    const options = new JsExtractionConfig();
    options.includeDocumentStructure = true;
    const result = extract_file_sync("pdf/fake_memo.pdf", options);
    expect(result.documentStructure.length).toBeGreaterThan(0);
  });
});
