// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c5fc398268ee0d3402abec0037f26ddb34863867f2b724fb74c154dad80c9b8d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, it, expect } from 'vitest';
import { extract_file, extract_file_sync, JsExtractionConfig } from 'kreuzberg';

describe('embeddings', () => {
  it('embedding_disabled: Tests chunking without embeddings - chunks should not have embedding vectors', () => {
    const options = new JsExtractionConfig();
    options.chunking = { max_chars: 500, max_overlap: 50 };
    const result = extract_file_sync("pdf/fake_memo.pdf", options);
    expect(result.mimeType.trim()).toBe("application/pdf");
    expect(result.content.length).toBeGreaterThanOrEqual(10);
    expect(result.chunks.length).toBeGreaterThanOrEqual(1);
    expect(result.chunksHaveContent).toBe(true);
  });
});
