// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:22ce653a7a854b5c1ee2b13ea76489d7c1df1b8ef303f50f165c478fc2dfca8b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, it, expect } from 'vitest';
import { extract_file, normalize } from 'kreuzberg';

describe('embed_extra', () => {
  it('embed_normalize_unit: Normalize unit vector', () => {
    normalize([1.0, 0.0, 0.0]);
  });

  it('embed_normalize_zero: Normalize zero vector', () => {
    normalize([0.0, 0.0, 0.0]);
  });
});
