// This file is auto-generated by alef. DO NOT EDIT.
import { describe, it, expect } from 'vitest';
import { extract_file } from 'kreuzberg';

describe('embeddings', () => {
  it('embedding_disabled: Tests chunking without embeddings - chunks should not have embedding vectors', async () => {
    const result = await extract_file();
    expect(result.mimeType.trim()).toBe("application/pdf");
    // TODO: unsupported assertion type: min_length
    expect(result.chunks.length).toBeGreaterThanOrEqual(1);
    // TODO: unsupported assertion type: is_true
  });
});
