// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, it, expect } from 'vitest';
import { extract_file, calculate_optimal_dpi } from 'kreuzberg';

describe('image_operations', () => {
  it('optimal_dpi_large: Calculate optimal DPI for large image (3000x4000 pixels, 5MB target)', () => {
    calculate_optimal_dpi(0, 0, 0.0);
  });

  it('optimal_dpi_small: Calculate optimal DPI for small image (800x600 pixels, 1MB target)', () => {
    calculate_optimal_dpi(0, 0, 0.0);
  });

  it('optimal_dpi_tiny: Calculate optimal DPI for tiny image (100x100 pixels, 0.1MB target)', () => {
    calculate_optimal_dpi(0, 0, 0.0);
  });
});
