// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1fc2b1c4f735c837bae3ee8d7d790f9e2fd124da05988b29adfebd3eb1791aad
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, it, expect } from 'vitest';
import { extract_file, extract_file_sync } from 'kreuzberg';

describe('parsing', () => {
  it('parse_json: Parse JSON document format', () => {
    const result = extract_file_sync("json/simple.json");
    expect(result.content.length).toBeGreaterThanOrEqual(5);
  });

  it('parse_toml: Parse TOML document format', () => {
    const result = extract_file_sync("data_formats/cargo.toml");
    expect(result.content.length).toBeGreaterThanOrEqual(5);
  });

  it('parse_xml: Parse XML document format', () => {
    const result = extract_file_sync("xml/simple_note.xml");
    expect(result.content.length).toBeGreaterThanOrEqual(5);
  });

  it('parse_yaml: Parse YAML document format', () => {
    const result = extract_file_sync("test_fixtures/config.yaml");
    expect(result.content.length).toBeGreaterThanOrEqual(5);
  });
});
