// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bf7121165236d8335935af69daeb2e1b4c9ffc05e13c7cbf564ac299e7ef0ab6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, it, expect } from 'vitest';
import { extract_file, get_extensions_for_mime, list_supported_formats } from 'kreuzberg';

describe('registry_operations', () => {
  it('extensions_docx: Get file extensions for DOCX MIME type', () => {
    get_extensions_for_mime('');
  });

  it('extensions_html: Get file extensions for HTML MIME type', () => {
    get_extensions_for_mime('');
  });

  it('extensions_pdf: Get file extensions for PDF MIME type', () => {
    const result = get_extensions_for_mime('');
    expect(result.result).toContain("pdf");
  });

  it('list_formats_all: List all supported formats and their extensions', () => {
    list_supported_formats(null);
  });
});
