// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4fb065fc5d2207fbff7962b51cab3b955b5d7f8d103b4f0aff8e26efafbe5f0e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, it, expect } from 'vitest';
import { extract_file, extract_file_sync, JsExtractionConfig } from 'kreuzberg';

describe('table', () => {
  it('table_csv_extraction: CSV file extraction produces content', () => {
    const result = extract_file_sync("csv/stanley_cups.csv");
    expect(result.content.length).toBeGreaterThanOrEqual(10);
  });

  it('table_html_extraction: HTML table extraction produces markdown format', () => {
    const options = new JsExtractionConfig();
    options.outputFormat = "markdown";
    const result = extract_file_sync("html/simple_table.html", options);
    expect(["|"].some((v) => result.content.includes(v))).toBe(true);
  });

  it('table_xlsx_markdown: XLSX extraction produces markdown table format', () => {
    const options = new JsExtractionConfig();
    options.outputFormat = "markdown";
    const result = extract_file_sync("xlsx/stanley_cups.xlsx", options);
    expect(["|", "---"].some((v) => result.content.includes(v))).toBe(true);
  });
});
