// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:651b0ff91bd0813cdd4ee1fc4fc218eaba1978b7abadce7e357c2303056a180c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, it, expect } from 'vitest';
import { extract_file, classify_uri } from 'kreuzberg';

describe('uri', () => {
  it('classify_uri_anchor: Classify fragment URI', () => {
    classify_uri("#section-header");
  });

  it('classify_uri_email: Classify mailto URI', () => {
    classify_uri("mailto:user@example.com");
  });

  it('classify_uri_https: Classify HTTPS URL', () => {
    classify_uri("https://example.com/page");
  });
});
