// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f231389f0a401242ae771498a308ad4a5608738940a367eab0109af7f74923c4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, it, expect } from 'vitest';
import { extract_file } from 'kreuzberg';

describe('xml', () => {
  it('xml_plant_catalog: XML plant catalog to validate streaming XML extraction.', async () => {
    const result = await extract_file("xml/plant_catalog.xml");
    expect(result.mimeType.trim()).toBe("application/xml");
    expect(result.content.length).toBeGreaterThanOrEqual(100);
  });
});
