# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'

RSpec.describe 'embeddings' do
  it 'embedding_disabled: Tests chunking without embeddings - chunks should not have embedding vectors' do
    result = Kreuzberg.extract_file_sync('pdf/fake_memo.pdf', Kreuzberg::ExtractionConfig.new(chunking: { 'max_chars' => 500, 'max_overlap' => 50 }))
    expect(result.mime_type).to eq('application/pdf')
    expect(result.content.length).to be >= 10
    expect(result.chunks.length).to be >= 1
    expect(result.chunks_have_content).to be true
  end
end
