# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c93f581fa3d91e4253f4b0bfc8c9b68efa49475842492b670ec996bb57c7f44b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'

RSpec.describe 'html' do
  it 'html_complex_layout: Large Wikipedia HTML page to validate complex conversion.' do
    result = Kreuzberg.extract_file('html/taylor_swift.html')
    expect(result.mime_type).to eq('text/html')
    expect(result.content.length).to be >= 1000
  end

  it 'html_simple_table: HTML table converted to markdown should retain structure.' do
    result = Kreuzberg.extract_file('html/simple_table.html')
    expect(result.mime_type).to eq('text/html')
    expect(result.content.length).to be >= 100
    expect(result.content.to_s).to include('Product')
    expect(result.content.to_s).to include('Category')
    expect(result.content.to_s).to include('Price')
    expect(result.content.to_s).to include('Stock')
    expect(result.content.to_s).to include('Laptop')
    expect(result.content.to_s).to include('Electronics')
    expect(result.content.to_s).to include('Sample Data Table')
  end
end
