# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:913f32db1816e25d292ae3f929b98f2f2cf90dfbf79dc63b2b446b2cd12c1c1b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'

RSpec.describe 'image' do
  it 'image_metadata_only: JPEG image to validate metadata extraction without OCR.' do
    result = Kreuzberg.extract_file('images/example.jpg', Kreuzberg::ExtractionConfig.new(disable_ocr: true, ocr: nil))
    expect(result.mime_type).to eq('image/jpeg')
    expect(result.content.length).to be <= 200
  end

  it 'image_svg_basic: SVG image extraction.' do
    result = Kreuzberg.extract_file('xml/simple_svg.svg')
    expect(result.mime_type).to eq('image/svg+xml')
    expect(result.content.length).to be >= 5
  end
end
