# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:826e8d8753593e62e38ec48d503361694927d8d54415dbc33a7ddbe1f4dbc7fb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'

RSpec.describe 'ocr_backend_management' do
  it 'ocr_backends_clear: Clear all OCR backends and verify list is empty' do
    result = Kreuzberg.extract_file('')
    expect(result.result.nil? || result.result.empty?).to be(true)
  end

  it 'ocr_backends_list: List all registered OCR backends' do
    result = Kreuzberg.list_ocr_backends(nil)
    expect(result).not_to be_nil
  end

  it 'ocr_backends_unregister: Unregister nonexistent OCR backend gracefully' do
    result = Kreuzberg.extract_file('')
    expect(result).not_to be_nil
  end
end
