# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'

RSpec.describe 'parsing' do
  it 'parse_json: Parse JSON document format' do
    result = Kreuzberg.extract_file_sync('json/simple.json')
    expect(result.content.length).to be >= 5
  end

  it 'parse_toml: Parse TOML document format' do
    result = Kreuzberg.extract_file_sync('data_formats/cargo.toml')
    expect(result.content.length).to be >= 5
  end

  it 'parse_xml: Parse XML document format' do
    result = Kreuzberg.extract_file_sync('xml/simple_note.xml')
    expect(result.content.length).to be >= 5
  end

  it 'parse_yaml: Parse YAML document format' do
    result = Kreuzberg.extract_file_sync('test_fixtures/config.yaml')
    expect(result.content.length).to be >= 5
  end
end
