# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:46abfb226d9c6b674eb7f53bfedf5e09af37607cf9b54525bc770203aedd02a1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'

RSpec.describe 'table_ops' do
  it 'excel_to_markdown_basic: Excel bytes to markdown (empty error)' do
    expect { Kreuzberg.excel_to_markdown('') }.to raise_error
  end

  it 'excel_to_text_basic: Excel bytes to text (empty error)' do
    expect { Kreuzberg.excel_to_text('') }.to raise_error
  end
end
