# This file is auto-generated by alef. DO NOT EDIT.
# frozen_string_literal: true

require 'kreuzberg'
require 'json'

RSpec.describe 'token_reduction' do
  it 'token_reduction_aggressive: Tests aggressive token reduction mode significantly reduces content' do
    result = Kreuzberg.extract_file('')
    expect(result.mime_type).to eq('application/pdf')
    expect(result.content.length).to be >= 5
    expect(result.content.length).to be <= 150
    expect(result.content).not_to be_empty
  end

  it 'token_reduction_basic: Tests basic token reduction on PDF document' do
    result = Kreuzberg.extract_file('')
    expect(result.mime_type).to eq('application/pdf')
    expect(result.content.length).to be >= 5
    expect(result.content.length).to be <= 200
    expect(result.content).not_to be_empty
  end

  it 'token_reduction_light: Tests light token reduction mode preserves most content' do
    result = Kreuzberg.extract_file('')
    expect(result.mime_type).to eq('application/pdf')
    expect(result.content.length).to be >= 10
    expect(result.content).not_to be_empty
  end

  it 'token_reduction_with_chunking: Tests token reduction combined with chunking' do
    result = Kreuzberg.extract_file('')
    expect(result.mime_type).to eq('application/pdf')
    expect(result.content.length).to be >= 5
    expect(result.content.length).to be <= 200
    expect(result.content).not_to be_empty
    expect(result.chunks.length).to be >= 1
    # TODO: unsupported assertion type: is_true
  end
end
