# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c609641bf4289bc041c0e43d0024b94cf5cbdfc7cf68e5600d3c852487d535c1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'

RSpec.describe 'validator_management' do
  it 'validators_clear: Clear all validators and verify list is empty' do
    result = Kreuzberg.extract_file('')
    expect(result.result.nil? || result.result.empty?).to be(true)
  end

  it 'validators_list: List all registered validators' do
    result = Kreuzberg.list_validators(nil)
    expect(result).not_to be_nil
  end
end
