<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

// Load the e2e project autoloader (PHPUnit, test helpers).
require_once __DIR__ . '/vendor/autoload.php';

// Load the PHP binding package classes via its Composer autoloader.
// The package's autoloader is separate from the e2e project's autoloader
// since the php-ext type prevents direct composer path dependency.
$pkgAutoloader = __DIR__ . '/../../packages/php/vendor/autoload.php';
if (file_exists($pkgAutoloader)) {
    require_once $pkgAutoloader;
}
