// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: batch
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_BatchBytesInvalidMime(t *testing.T) {
	// batch_extract_bytes_sync invalid MIME
	_, err := kreuzberg.batch_extract_bytes_sync(`[{"data":"SGVsbG8=","mime_type":"application/x-nonexistent"}]`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_BatchFileAsyncBasic(t *testing.T) {
	// Extract text from multiple files asynchronously
	_, err := kreuzberg.batch_extract_file(`["pdf/fake_memo.pdf","text/fake_text.txt"]`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_BatchFileAsyncNotFound(t *testing.T) {
	// batch_extract_file async nonexistent
	_, err := kreuzberg.batch_extract_file(`["/nonexistent/a.pdf"]`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_BatchFileNotFound(t *testing.T) {
	// batch_extract_file_sync nonexistent
	_, err := kreuzberg.batch_extract_file_sync(`["/nonexistent/a.pdf","/nonexistent/b.txt"]`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_BatchFilePartial(t *testing.T) {
	// batch_extract_file_sync mixed
	_, err := kreuzberg.batch_extract_file_sync(`["test_documents/text/plain.txt","/nonexistent/missing.pdf"]`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_BatchFileSyncBasic(t *testing.T) {
	// Extract text from multiple files synchronously
	_, err := kreuzberg.batch_extract_file_sync(`["pdf/fake_memo.pdf","text/fake_text.txt"]`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
