// Code generated by alef. DO NOT EDIT.

// E2e tests for category: embeddings
package e2e_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_EmbeddingDisabled(t *testing.T) {
	// Tests chunking without embeddings - chunks should not have embedding vectors
	result, err := kreuzberg.ExtractFile("")
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if strings.TrimSpace(result.MimeType) != `application/pdf` {
		t.Errorf("equals mismatch: got %v", result.MimeType)
	}
	// TODO: unsupported assertion type: min_length
	assert.GreaterOrEqual(t, len(result.Chunks), 1, "expected at least 1 elements")
	// TODO: unsupported assertion type: is_true
}
