// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: embed_extra
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_EmbedNormalizeUnit(t *testing.T) {
	// Normalize unit vector
	_, err := kreuzberg.normalize(`[1.0,0.0,0.0]`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_EmbedNormalizeZero(t *testing.T) {
	// Normalize zero vector
	_, err := kreuzberg.normalize(`[0.0,0.0,0.0]`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
