// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4c7ffb9926e5f133994ddcb5c8f8c180e04bfdb90635b8d324d7519d2068daf5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: embedding_backend_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_EmbeddingBackendLifecycle(t *testing.T) {
	// List/clear lifecycle for embedding backends; asserts the registry surface exists and empty-state operations are non-erroring
	_, err := kreuzberg.ExtractFile("")
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
