// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: image
package e2e_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_ImageMetadataOnly(t *testing.T) {
	// JPEG image to validate metadata extraction without OCR.
	result, err := kreuzberg.ExtractFile(`images/example.jpg`, htmd.NewExtractionConfig(htmd.WithExtractionConfigDisableOcr(true), htmd.WithExtractionConfigOcr(nil)))
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if strings.TrimSpace(result.MimeType) != `image/jpeg` {
		t.Errorf("equals mismatch: got %v", result.MimeType)
	}
	if result.Content != nil {
		assert.LessOrEqual(t, len(*result.Content), 200, "expected length <= 200")
	}
}

func Test_ImageSvgBasic(t *testing.T) {
	// SVG image extraction.
	result, err := kreuzberg.ExtractFile(`xml/simple_svg.svg`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if strings.TrimSpace(result.MimeType) != `image/svg+xml` {
		t.Errorf("equals mismatch: got %v", result.MimeType)
	}
	if result.Content != nil {
		assert.GreaterOrEqual(t, len(*result.Content), 5, "expected length >= 5")
	}
}
