// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a2ce5c96b1ebd5b9693e34c4898b7df83691d68b3c6156392a071902e62cb805
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: language
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_LangDetectConfig(t *testing.T) {
	// Language detection with specific language config
	_, err := kreuzberg.ExtractFileSync(`semantic/mixed_topics.txt`, htmd.NewExtractionConfig(htmd.WithExtractionConfigLanguageDetection(`{"enabled":true,"languages":["en","de","fr"]}`)))
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_LangDetectEnglish(t *testing.T) {
	// Language detection works on English text
	_, err := kreuzberg.ExtractFileSync(`semantic/mixed_topics.txt`, htmd.NewExtractionConfig(htmd.WithExtractionConfigLanguageDetection(`{"enabled":true}`)))
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
