// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5ed8ba14939297eb6d330cc7dd1ae0570f07bd1cae692c2cf4cbacfb94b77f50
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: parsing
package e2e_test

import (
	"testing"

	"github.com/stretchr/testify/assert"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_ParseJson(t *testing.T) {
	// Parse JSON document format
	result, err := kreuzberg.ExtractFileSync(`json/simple.json`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.Content != nil {
		assert.GreaterOrEqual(t, len(*result.Content), 5, "expected length >= 5")
	}
}

func Test_ParseToml(t *testing.T) {
	// Parse TOML document format
	result, err := kreuzberg.ExtractFileSync(`data_formats/cargo.toml`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.Content != nil {
		assert.GreaterOrEqual(t, len(*result.Content), 5, "expected length >= 5")
	}
}

func Test_ParseXml(t *testing.T) {
	// Parse XML document format
	result, err := kreuzberg.ExtractFileSync(`xml/simple_note.xml`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.Content != nil {
		assert.GreaterOrEqual(t, len(*result.Content), 5, "expected length >= 5")
	}
}

func Test_ParseYaml(t *testing.T) {
	// Parse YAML document format
	result, err := kreuzberg.ExtractFileSync(`test_fixtures/config.yaml`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.Content != nil {
		assert.GreaterOrEqual(t, len(*result.Content), 5, "expected length >= 5")
	}
}
