// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d85c5af5baf4e82eddfcf186af7e97a1aec1128688bc8b0fac3cd739ea0a4bb4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: post_processor_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_PostProcessorsClear(t *testing.T) {
	// Clear all post-processors and verify list is empty
	_, err := kreuzberg.ExtractFile("")
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_PostProcessorsList(t *testing.T) {
	// List all registered post-processors
	_, err := kreuzberg.list_post_processors(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
