// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:17ed93d11df8dcdacb512273201f67ec5f3befbc86e0343e83069f62e458535a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: post_processor_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_PostProcessorsClear(t *testing.T) {
	// Clear all post-processors and verify list is empty
	_, err := kreuzberg.ExtractFile("")
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_PostProcessorsList(t *testing.T) {
	// List all registered post-processors
	_, err := kreuzberg.ListPostProcessors(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
