// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bdc98ee33f45e83b11b4af8905fb06c21de6f47a7f9d87cadd7e2a2252cec2dd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: registry_operations
package e2e_test

import (
	"strings"
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_ExtensionsDocx(t *testing.T) {
	// Get file extensions for DOCX MIME type
	_, err := kreuzberg.GetExtensionsForMime("")
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ExtensionsHtml(t *testing.T) {
	// Get file extensions for HTML MIME type
	_, err := kreuzberg.GetExtensionsForMime("")
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ExtensionsPdf(t *testing.T) {
	// Get file extensions for PDF MIME type
	result, err := kreuzberg.GetExtensionsForMime("")
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if !strings.Contains(string(result.Result), `pdf`) {
		t.Errorf("expected to contain %s, got %v", `pdf`, result.Result)
	}
}

func Test_ListFormatsAll(t *testing.T) {
	// List all supported formats and their extensions
	_, err := kreuzberg.ListSupportedFormats(nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
