// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9d30b8381375cac141155840d370f5957a27549a1e5b0f1bb11574c830d25ebf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: registry
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_ListDocumentExtractors(t *testing.T) {
	// List document extractors
	_, err := kreuzberg.list_document_extractors(`{}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListOcrBackends(t *testing.T) {
	// List OCR backends
	_, err := kreuzberg.list_ocr_backends(`{}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListPostProcessors(t *testing.T) {
	// List post-processors
	_, err := kreuzberg.list_post_processors(`{}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListValidators(t *testing.T) {
	// List validators
	_, err := kreuzberg.list_validators(`{}`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
