// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9f152aeacdc78e581bd31f615c077a87be1d44ff5982bd444e5fceafc057aae3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: string_utils
package e2e_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_CamelToSnakeBasic(t *testing.T) {
	// Convert camelCase to snake_case
	result, err := kreuzberg.CamelToSnake(`myVariableName`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if strings.TrimSpace(result.Result) != `my_variable_name` {
		t.Errorf("equals mismatch: got %v", result.Result)
	}
}

func Test_CamelToSnakeSingle(t *testing.T) {
	// Convert single word (no camelCase) remains unchanged
	result, err := kreuzberg.CamelToSnake(`hello`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if strings.TrimSpace(result.Result) != `hello` {
		t.Errorf("equals mismatch: got %v", result.Result)
	}
}

func Test_SanitizeFilenameBasic(t *testing.T) {
	// Sanitize path traversal attempts in filename
	result, err := kreuzberg.SanitizeFilename(`../../etc/passwd`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.GreaterOrEqual(t, len(result.Result), 1, "expected length >= 1")
}

func Test_SanitizeFilenameSpecial(t *testing.T) {
	// Sanitize special characters in filename
	result, err := kreuzberg.SanitizeFilename(`file<>name|test.pdf`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.GreaterOrEqual(t, len(result.Result), 1, "expected length >= 1")
}

func Test_SanitizePathBasic(t *testing.T) {
	// Sanitize path traversal in file path
	result, err := kreuzberg.SanitizePath(`../../../secret/file.txt`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.GreaterOrEqual(t, len(result.Result), 1, "expected length >= 1")
}

func Test_SanitizePathSpaces(t *testing.T) {
	// Sanitize path with spaces
	_, err := kreuzberg.SanitizePath(`my folder/file.txt`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_SanitizePathTraversal(t *testing.T) {
	// Sanitize path traversal
	_, err := kreuzberg.SanitizePath(`../../../etc/passwd`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_SnakeToCamelBasic(t *testing.T) {
	// Convert snake_case to camelCase
	result, err := kreuzberg.SnakeToCamel(`my_variable_name`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if strings.TrimSpace(result.Result) != `myVariableName` {
		t.Errorf("equals mismatch: got %v", result.Result)
	}
}

func Test_SnakeToCamelSingle(t *testing.T) {
	// Convert single word remains unchanged
	result, err := kreuzberg.SnakeToCamel(`hello`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if strings.TrimSpace(result.Result) != `hello` {
		t.Errorf("equals mismatch: got %v", result.Result)
	}
}
