// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dfc4aa632484d9ef9fa2aba167e7d43c08e651c7f1e711aa1cf7dca77ae2e601
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: table_ops
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_ExcelToMarkdownBasic(t *testing.T) {
	// Excel bytes to markdown (empty error)
	_, err := kreuzberg.excel_to_markdown(``)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_ExcelToTextBasic(t *testing.T) {
	// Excel bytes to text (empty error)
	_, err := kreuzberg.excel_to_text(``)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}
