// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:69b1307ab6fde8d24f6d7a106a1920d71cc4484208c7d548f8152eb2dacc47eb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: text_processing
package e2e_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_TextCleanExtracted(t *testing.T) {
	// Extract and clean text content from document
	result, err := kreuzberg.ExtractFileSync(`json/simple.json`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.GreaterOrEqual(t, len(result.Content), 5, "expected length >= 5")
}

func Test_TextNormalizeWhitespace(t *testing.T) {
	// Extract text with whitespace normalization (no consecutive spaces)
	result, err := kreuzberg.ExtractFileSync(`pdf/fake_memo.pdf`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if strings.Contains(string(result.Content), `  `) {
		t.Errorf("expected NOT to contain %s, got %v", `  `, result.Content)
	}
}
