// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:062d0e9c27b55bb62c0d86d684c11850c24823391f397caffdcffb8cd9bed036
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: text_processing
package e2e_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_TextCleanExtracted(t *testing.T) {
	// Extract and clean text content from document
	result, err := kreuzberg.extract_file_sync(`json/simple.json`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.Content != nil {
		assert.GreaterOrEqual(t, len(*result.Content), 5, "expected length >= 5")
	}
}

func Test_TextNormalizeWhitespace(t *testing.T) {
	// Extract text with whitespace normalization (no consecutive spaces)
	result, err := kreuzberg.extract_file_sync(`pdf/fake_memo.pdf`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	var content string
	if result.Content != nil {
		content = *result.Content
	}
	if strings.Contains(string(content), `  `) {
		t.Errorf("expected NOT to contain %s, got %v", `  `, content)
	}
}
