// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f3d56ff3fd0bd8d457d8726f21d047252559a51dcbd95cacc35ad88a2fa433d1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: uri
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_ClassifyUriAnchor(t *testing.T) {
	// Classify fragment URI
	_, err := kreuzberg.ClassifyURI(`#section-header`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ClassifyUriEmail(t *testing.T) {
	// Classify mailto URI
	_, err := kreuzberg.ClassifyURI(`mailto:user@example.com`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ClassifyUriHttps(t *testing.T) {
	// Classify HTTPS URL
	_, err := kreuzberg.ClassifyURI(`https://example.com/page`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
