// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0cb0a25b777dcca00d4c9166af31d4cd28a3ad4812fee8f1529dc7f013b2b695
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: xml
package e2e_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_XmlPlantCatalog(t *testing.T) {
	// XML plant catalog to validate streaming XML extraction.
	result, err := kreuzberg.ExtractFile(`xml/plant_catalog.xml`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if strings.TrimSpace(result.MimeType) != `application/xml` {
		t.Errorf("equals mismatch: got %v", result.MimeType)
	}
	assert.GreaterOrEqual(t, len(result.Content), 100, "expected length >= 100")
}
